export const KHASI_RULESET=Object.freeze({gameId:'khasi-fishflow',rulesetVersion:'mawkar-katiya-das-gupta-1923-1.0.0',traditionalName:'Mawkar Katiya',region:'Khasi Hills, Meghalaya',pitsPerRow:7,openingCounters:5,totalCounters:70});
export const PLAYERS=Object.freeze(['aurora','coral']);
export const otherPlayer=p=>p==='aurora'?'coral':'aurora';
const clone=v=>JSON.parse(JSON.stringify(v));
export function createKhasiState({mode='hotseat',starter='aurora'}={}){return{gameId:KHASI_RULESET.gameId,rulesetVersion:KHASI_RULESET.rulesetVersion,mode,rows:{aurora:Array(7).fill(5),coral:Array(7).fill(5)},active:{aurora:Array(7).fill(true),coral:Array(7).fill(true)},partial:{aurora:null,coral:null},roundExtra:{aurora:0,coral:0},stores:{aurora:0,coral:0},currentPlayer:starter,turn:1,round:1,lastTurn:null,winner:null,winReason:null,history:[]};}
export function route(){return[...Array(7)].map((_,i)=>({player:'aurora',pitIndex:i})).concat([...Array(7)].map((_,i)=>({player:'coral',pitIndex:6-i})));}
const key=p=>`${p.player}:${p.pitIndex}`; const get=(s,p)=>s.rows[p.player][p.pitIndex]; const set=(s,p,v)=>s.rows[p.player][p.pitIndex]=v;
export function getLegalActions(state,player=state.currentPlayer){if(!state||state.winner||player!==state.currentPlayer)return[];return state.rows[player].map((n,i)=>({n,i})).filter(x=>x.n>0&&state.active[player][x.i]&&state.partial[player]!==x.i).map(x=>({type:'sow',pitIndex:x.i}));}
export function validateAction(state,action,player=state.currentPlayer){if(!state||state.winner)return{valid:false,reason:'The match has ended.'};if(player!==state.currentPlayer)return{valid:false,reason:'It is not your turn.'};return getLegalActions(state,player).some(a=>a.pitIndex===action?.pitIndex)?{valid:true}:{valid:false,reason:'Choose an active non-empty pit on your row.'};}
export function applyAction(state,action,player=state.currentPlayer){const v=validateAction(state,action,player);if(!v.valid)return{state,error:v.reason};const next=clone(state),r=route();let cursor=r.findIndex(p=>p.player===player&&p.pitIndex===action.pitIndex),hand=get(next,r[cursor]);set(next,r[cursor],0);let relays=0,captured=0,endpoint=null,steps=0;while(true){while(hand>0){cursor=(cursor+1)%r.length;const pit=r[cursor];set(next,pit,get(next,pit)+1);hand--;steps++;applyRoundHandicap(next,player,pit);if(steps>20000)return{state,error:'Relay safety limit reached.'};}endpoint=r[cursor];const following=r[(cursor+1)%r.length];if(get(next,following)>0){hand=get(next,following);set(next,following,0);cursor=(cursor+1)%r.length;relays++;continue;}const target={player:otherPlayer(following.player),pitIndex:following.pitIndex};captured=get(next,target);set(next,target,0);next.stores[player]+=captured;break;}
next.lastTurn={player,pitIndex:action.pitIndex,relays,captured,endpoint};next.history.push({turn:next.turn,...clone(next.lastTurn)});next.turn++;finishRoundIfNeeded(next);if(!next.winner)next.currentPlayer=otherPlayer(player);return{state:next,error:null};}
function applyRoundHandicap(state,mover,pit){for(const owner of PLAYERS){const target=Number(state.roundExtra[owner]||0);if(owner!==mover&&target>0&&get(state,pit)===target){state.stores[owner]+=target;set(state,pit,0);}}
const opponent=otherPlayer(mover);if(state.partial[opponent]===pit.pitIndex&&pit.player===opponent){state.stores[mover]+=1;set(state,pit,Math.max(0,get(state,pit)-1));}}
function sideTotal(s,p){return s.rows[p].reduce((a,b)=>a+b,0)}
function finishRoundIfNeeded(s){if(sideTotal(s,'aurora')&&sideTotal(s,'coral'))return false;for(const p of PLAYERS)s.stores[p]+=sideTotal(s,p);for(const p of PLAYERS)s.rows[p]=Array(7).fill(0);const stock={...s.stores};if(!stock.aurora||!stock.coral){s.winner=stock.aurora>stock.coral?'aurora':'coral';s.winReason='all-counters-captured';return true;}s.round++;for(const p of PLAYERS){const full=Math.min(7,Math.floor(stock[p]/5));const rem=stock[p]-full*5;s.active[p]=Array(7).fill(false);for(let i=0;i<full;i++){s.rows[p][i]=5;s.active[p][i]=true;}s.partial[p]=null;s.roundExtra[p]=rem;if(rem&&full<7){s.rows[p][full]=rem;s.active[p][full]=true;s.partial[p]=full;}s.stores[p]=0;}return true;}
export function createHandicapDrill(){const s=createKhasiState({mode:'drill'});s.rows={aurora:[5,5,5,5,5,5,5],coral:[5,5,5,5,5,2,0]};s.active={aurora:Array(7).fill(true),coral:[true,true,true,true,true,true,false]};s.partial={aurora:null,coral:5};s.roundExtra={aurora:0,coral:2};s.currentPlayer='aurora';return s;}
export function summary(s,p){return{board:sideTotal(s,p),bank:s.stores[p],active:s.active[p].filter(Boolean).length,partial:s.partial[p],extra:s.roundExtra[p]};}
export function resultTitle(s){return s.winner==='aurora'?'Aurora Current wins':'Coral Current wins';}
export function describeTurn(s){return `${s.currentPlayer==='aurora'?'Aurora':'Coral'} Current chooses an active pit.`;}
