import { useEffect, useState } from "react";
import { ProfileScreen } from "../../screens/ProfileScreen.jsx";
import { createProfile } from "../../network/socketClient.js";
import {
  createAuroraGanjifaRoom, getAuroraGanjifaHistory, getAuroraGanjifaLegalActions,
  getAuroraGanjifaState, getMyAuroraGanjifaRooms, joinAuroraGanjifaRoom,
  listAuroraGanjifaRooms, submitAuroraGanjifaAction
} from "../../network/auroraGanjifaSocketClient.js";
import { AuroraGanjifaTable } from "./AuroraGanjifaTable.jsx";
import { seatName } from "./rules.js";

export function AuroraGanjifaOnline({ profile, onProfileChange, onBack }) {
  const [screen,setScreen]=useState("lobby"); const [room,setRoom]=useState(null); const [rooms,setRooms]=useState([]); const [myRooms,setMyRooms]=useState([]); const [history,setHistory]=useState([]); const [roomCode,setRoomCode]=useState(""); const [legal,setLegal]=useState([]); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  useEffect(()=>{if(profile) refreshLobby();},[profile]);
  useEffect(()=>{function packet(event){if(event.detail?.type!=="ag_room_state")return;const next=event.detail.payload?.room;if(!next||(room&&next.roomCode!==room.roomCode))return;setRoom(next);setScreen("game");refreshLegal(next);}window.addEventListener("server-packet",packet);return()=>window.removeEventListener("server-packet",packet);},[room,profile]);
  async function login(){await createProfile({address:profile.wallet,name:profile.name});}
  async function run(task){try{setBusy(true);setMessage("");return await task();}catch(err){setMessage(err.message||"Request failed.");return null;}finally{setBusy(false);}}
  async function refreshLobby(){await run(async()=>{await login();const [open,mine,past]=await Promise.all([listAuroraGanjifaRooms(),getMyAuroraGanjifaRooms({profile}),getAuroraGanjifaHistory({profile})]);setRooms(open);setMyRooms(mine);setHistory(past);});}
  async function refreshLegal(next=room){if(!profile||!next?.roomCode||next.status!=="playing")return setLegal([]);try{setLegal(await getAuroraGanjifaLegalActions({roomCode:next.roomCode,profile}));}catch{setLegal([]);}}
  function open(next){setRoom(next);setScreen("game");refreshLegal(next);}
  async function create(visibility,playerCount){const next=await run(async()=>{await login();return createAuroraGanjifaRoom({visibility,playerCount,profile});});if(next)open(next);}
  async function join(code=roomCode){const clean=String(code||"").toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,4);if(clean.length!==4)return setMessage("Enter a four-character room code.");const next=await run(async()=>{await login();return joinAuroraGanjifaRoom({roomCode:clean,profile});});if(next)open(next);}
  async function resume(code){const next=await run(async()=>{await login();return getAuroraGanjifaState({roomCode:code,profile});});if(next)open(next);}
  async function play(cardId){const next=await run(()=>submitAuroraGanjifaAction({roomCode:room.roomCode,profile,action:{type:"play-card",cardId}}));if(next)open(next);}
  if(!profile)return <ProfileScreen onComplete={onProfileChange} onBack={onBack}/>;
  if(screen==="history")return <section className="ag-online"><header><button onClick={()=>setScreen("lobby")}>← Lobby</button><h1>Academy History</h1></header><div className="ag-history">{!history.length&&<p>No completed academy deals yet.</p>}{history.map(entry=><article key={entry.id}><strong>{entry.won?"Top Collector":"Deal Complete"}</strong><span>Room {entry.roomCode} · {seatName(entry.team)}</span><small>{entry.rulesetVersion}</small></article>)}</div></section>;
  if(screen==="game"&&room){const me=room.players.find(player=>player.wallet.toLowerCase()===profile.wallet.toLowerCase());const state=room.gameState;return <section className="ag-game" aria-label="Aurora Ganjifa online table"><header className="ag-header"><button onClick={()=>{setScreen("lobby");refreshLobby();}}>← Lobby</button><div><p>PRIVATE-STATE TABLE · {room.rulesetVersion}</p><h1>Room {room.roomCode}</h1></div><button onClick={()=>navigator.clipboard?.writeText(room.roomCode)}>Copy Code</button></header>{room.status==="waiting"?<div className="ag-wait"><h2>Waiting for {room.maxPlayers-room.playerCount} more scholar{room.maxPlayers-room.playerCount===1?"":"s"}</h2><p>Hands are dealt only after every seat joins. Share code <strong>{room.roomCode}</strong>.</p></div>:<><div className="ag-turn"><strong>{room.status==="finished"?(state.isDraw?"Shared highest collection":`${seatName(state.winner)} wins`):state.currentPlayer===me?.seat?"Your turn":`${seatName(state.currentPlayer)} is choosing`}</strong><span>Your hand is the only hand included in this server projection.</span></div><AuroraGanjifaTable state={state} hand={state.privateHand||[]} legalActions={legal} onPlay={play} viewerSeat={me?.seat}/></>}{message&&<p className="ag-message">{message}</p>}<footer className="ag-footer"><span>{me?`You are ${seatName(me.seat)}`:"Spectator projection"}</span><span>{busy?"Syncing…":"Server validates shuffle, private hands and follow-suit."}</span></footer></section>;}
  return <section className="ag-online" aria-label="Aurora Ganjifa online lobby"><header><button onClick={onBack}>← Academy</button><h1>Ganjifa Tables</h1><button onClick={()=>setScreen("history")}>History</button></header><div className="ag-online-grid"><article><h2>Three Scholars</h2><p>32 cards each. Faster teaching table.</p><button disabled={busy} onClick={()=>create("public",3)}>Public Table</button><button disabled={busy} onClick={()=>create("private",3)}>Private Table</button></article><article><h2>Four Scholars</h2><p>24 cards each. Full four-seat circle.</p><button disabled={busy} onClick={()=>create("public",4)}>Public Table</button><button disabled={busy} onClick={()=>create("private",4)}>Private Table</button></article><article><h2>Join by Code</h2><input aria-label="Ganjifa room code" value={roomCode} onChange={e=>setRoomCode(e.target.value.toUpperCase())} maxLength={4} placeholder="ABCD"/><button onClick={()=>join()}>Join Table</button></article><article><h2>Open Tables</h2>{!rooms.length&&<p>No public table is waiting.</p>}{rooms.map(item=><button key={item.roomCode} onClick={()=>join(item.roomCode)}>{item.roomCode} · {item.playerCount}/{item.maxPlayers}</button>)}</article><article className="wide"><h2>Your Reconnectable Tables</h2>{!myRooms.length&&<p>No saved Ganjifa table yet.</p>}{myRooms.map(item=><button key={item.roomCode} onClick={()=>resume(item.roomCode)}>{item.roomCode} · {item.status}</button>)}</article></div>{message&&<p className="ag-message">{message}</p>}<button className="ag-refresh" disabled={busy} onClick={refreshLobby}>{busy?"Syncing…":"Refresh Tables"}</button></section>;
}
