import { useEffect, useRef, useState } from "react";
import { AuroraGanjifaOnline } from "./AuroraGanjifaOnline.jsx";
import { AuroraGanjifaTable } from "./AuroraGanjifaTable.jsx";
import { chooseGanjifaBotAction } from "./bot.js";
import { AURORA_GANJIFA_RULESET, SUITS, applyAction, createAcademyState, createFollowSuitLesson, getLegalActions, seatName } from "./rules.js";

export function AuroraGanjifaAcademyApp({ onExitToLibrary, profile, onProfileChange }) {
  const [screen,setScreen]=useState("cover"); const [mode,setMode]=useState("practice-3"); const [state,setState]=useState(()=>createAcademyState({playerCount:3})); const [message,setMessage]=useState(""); const [revealed,setRevealed]=useState(true); const timer=useRef(null);
  const hotseat=mode.startsWith("hotseat"); const humanSeat="north";
  useEffect(()=>()=>window.clearTimeout(timer.current),[]);
  useEffect(()=>{window.clearTimeout(timer.current);if(screen!=="game"||hotseat||state.phase!=="playing"||state.currentPlayer===humanSeat)return;timer.current=window.setTimeout(()=>{const action=chooseGanjifaBotAction(state,state.currentPlayer);if(!action)return;const result=applyAction(state,action,state.currentPlayer);setState(result.state);setMessage(result.state.lastAction?.trickWinner?`${seatName(result.state.lastAction.trickWinner)} collected the trick.`:`${seatName(state.currentPlayer)} followed the circle.`);},360);},[screen,mode,state,hotseat]);
  function start(nextMode){setMode(nextMode);const playerCount=nextMode.endsWith("4")?4:3;const next=nextMode==="lesson"?createFollowSuitLesson():createAcademyState({playerCount,mode:nextMode,seed:Date.now()});setState(next);setRevealed(!nextMode.startsWith("hotseat"));setMessage(nextMode==="lesson"?"Lead Taj 7. The next scholars must follow Taj, and strong-suit Ace outranks higher numerals.":"");setScreen("game");}
  function play(cardId){const seat=state.currentPlayer;if(!hotseat&&seat!==humanSeat)return;const result=applyAction(state,{type:"play-card",cardId},seat);if(result.error)return setMessage(result.error);setState(result.state);setMessage(result.state.lastAction?.trickWinner?`${seatName(result.state.lastAction.trickWinner)} wins trick ${result.state.lastAction.trickNumber}.`:"Card accepted. The circle moves anticlockwise.");if(hotseat)setRevealed(false);}
  if(screen==="cover")return <section className="ag-cover" aria-label="Aurora Ganjifa Academy cover"><button className="ag-back" onClick={onExitToLibrary}>← All Games</button><div className="ag-cover-orbit" aria-hidden="true">{SUITS.map((suit,index)=><i key={suit.id} style={{"--i":index}}><span>{suit.symbol}</span></i>)}<b>❄</b></div><div className="ag-cover-copy"><p>IGNCA WORKSHOP TEACHING BASELINE</p><h1>AURORA<br/>GANJIFA<br/>ACADEMY</h1><span>Learn India’s circular trick-taking tradition before advanced regional tables unlock.</span><button onClick={()=>setScreen("menu")}>Enter the academy</button></div></section>;
  if(screen==="menu")return <section className="ag-menu"><button className="ag-back" onClick={()=>setScreen("cover")}>← Cover</button><article><p className="ag-eyebrow">MUGHAL GANJIFA · EIGHT SUITS · PRIVATE HANDS</p><h1>Aurora Ganjifa Academy</h1><p>This release teaches the institutional IGNCA workshop baseline. It is not a claim that every Ganjifa region uses one universal rulebook.</p><div className="ag-menu-grid"><button className="primary" onClick={()=>setScreen("online")}>Online Private-State Tables</button><button onClick={()=>start("practice-3")}>Three-Player Practice</button><button onClick={()=>start("practice-4")}>Four-Player Practice</button><button onClick={()=>start("hotseat-3")}>Pass Device · 3 Players</button><button onClick={()=>start("hotseat-4")}>Pass Device · 4 Players</button><button onClick={()=>start("lesson")}>Follow-Suit Lesson</button><button onClick={()=>setScreen("rules")}>How to Play</button></div><div className="ag-boundary">No permanent trump, no Dashavatara payment rules, no Dukkal/Deni forcing system, and no ranked economy are imported into this teaching queue.</div></article></section>;
  if(screen==="online")return <AuroraGanjifaOnline profile={profile} onProfileChange={onProfileChange} onBack={()=>setScreen("menu")}/>;
  if(screen==="rules")return <Rules onBack={()=>setScreen("menu")} onStart={()=>start("practice-3")}/>;
  const viewerSeat=hotseat?state.currentPlayer:humanSeat;const hand=state.hands[viewerSeat]||[];const legal=(hotseat||state.currentPlayer===humanSeat)&&revealed?getLegalActions(state,state.currentPlayer):[];
  return <section className="ag-game" aria-label="Aurora Ganjifa Academy table"><header className="ag-header"><button onClick={()=>setScreen("menu")}>← Academy</button><div><p>{AURORA_GANJIFA_RULESET.rulesetVersion}</p><h1>Aurora Ganjifa Academy</h1></div><button onClick={()=>start(mode)}>New Deal</button></header><div className="ag-turn"><strong>{state.phase==="finished"?(state.isDraw?"Shared highest collection":`${seatName(state.winner)} wins the deal`):hotseat&&!revealed?`Pass to ${seatName(state.currentPlayer)}`:state.currentPlayer===viewerSeat?`${seatName(viewerSeat)} to play`:`${seatName(state.currentPlayer)} is studying the trick`}</strong><span>{state.ledSuit?`Follow ${state.ledSuit.toUpperCase()} when possible.`:"The leader may play any suit."}</span></div>{hotseat&&!revealed?<div className="ag-handoff"><span>◉</span><h2>Private hand protected</h2><p>Only {seatName(state.currentPlayer)} should look at the next screen.</p><button onClick={()=>setRevealed(true)}>Reveal {seatName(state.currentPlayer)} Hand</button></div>:<AuroraGanjifaTable state={state} hand={hand} legalActions={legal} onPlay={play} viewerSeat={viewerSeat} revealHand={revealed}/>} {message&&<p className="ag-message" role="alert">{message}</p>}<footer className="ag-footer"><span>{modeLabel(mode)}</span><span>Strong numerals: Ace high · Weak numerals: Ten high · Raja and Pradhan remain courts</span></footer></section>;
}

function Rules({onBack,onStart}){return <section className="ag-rules"><button className="ag-back" onClick={onBack}>← Academy</button><article><p className="ag-eyebrow">IGNCA WORKSHOP BASELINE</p><h1>Learn the circular pack</h1><div className="ag-rule-grid"><section><strong>1 · Deal the whole pack</strong><p>Mughal teaching uses 96 cards: eight suits of twelve. Divide the cards equally among three or four players and keep every hand private.</p></section><section><strong>2 · Read strong and weak suits</strong><p>Taj, Safed, Samsher and Ghulam are strong: Raja, Pradhan, Ace, 2 through 10. Chang, Surkh, Barat and Qimash are weak: Raja, Pradhan, 10 down to Ace.</p></section><section><strong>3 · Lead and follow</strong><p>The Taj Raja holder opens this digital queue. Play proceeds anticlockwise. Follow the led suit when able; otherwise discard any card.</p></section><section><strong>4 · Resolve the trick</strong><p>Only cards of the led suit compete. Its highest denomination takes every card and leads the next trick. There is no permanent trump.</p></section><section><strong>5 · Win by collection</strong><p>When all hands are empty, the scholar who collected the most cards wins. Equal highest totals are recorded as a shared result.</p></section><section><strong>6 · Protect hidden information</strong><p>Online tables send each wallet only its own hand. Reconnect restores that private projection; room lists and spectators receive counts, never faces.</p></section></div><div className="ag-modern"><strong>Version boundary</strong><span>The Taj Raja opening card and shared-tie policy are declared digital choices. Advanced regional obligations belong in later rulesets after player validation.</span></div><button className="ag-start" onClick={onStart}>Begin Three-Player Practice</button></article></section>}
function modeLabel(mode){if(mode==="lesson")return"Follow-Suit Lesson";if(mode==="practice-4")return"Four-Player Practice";if(mode==="hotseat-3")return"Pass Device · 3 Players";if(mode==="hotseat-4")return"Pass Device · 4 Players";return"Three-Player Practice";}
