export const AURORA_GANJIFA_RULESET = Object.freeze({ gameId: "aurora-ganjifa-academy", rulesetVersion: "ignca-mughal-teaching-baseline-1.0.0", playerCounts: [3,4], cards: 96, permanentTrump: false });
export const SUITS = Object.freeze([
  { id:"taj", name:"Taj", symbol:"♛", class:"strong" }, { id:"safed", name:"Safed", symbol:"◌", class:"strong" },
  { id:"samsher", name:"Samsher", symbol:"⚔", class:"strong" }, { id:"ghulam", name:"Ghulam", symbol:"♞", class:"strong" },
  { id:"chang", name:"Chang", symbol:"◖", class:"weak" }, { id:"surkh", name:"Surkh", symbol:"●", class:"weak" },
  { id:"barat", name:"Barat", symbol:"✦", class:"weak" }, { id:"qimash", name:"Qimash", symbol:"◆", class:"weak" }
]);
const STRONG = new Set(["taj","safed","samsher","ghulam"]);
const RANKS = ["raja","pradhan","1","2","3","4","5","6","7","8","9","10"];
export const SEATS = ["north","west","south","east"];
export function seatName(seat){return ({north:"Aurora North",west:"Glacier West",south:"Ember South",east:"Moonlit East"})[seat]||seat;}
function rankLabel(rank){return rank==="raja"?"Raja":rank==="pradhan"?"Pradhan":rank==="1"?"Ace":rank;}
export function cardStrength(card){if(card.rank==="raja")return 120;if(card.rank==="pradhan")return 110;const n=Number(card.rank);return STRONG.has(card.suit)?20-n:9+n;}
export function makeDeck(){return SUITS.flatMap(s=>RANKS.map(rank=>({id:`${s.id}-${rank}`,suit:s.id,suitName:s.name,suitClass:s.class,symbol:s.symbol,rank,rankLabel:rankLabel(rank),strength:cardStrength({suit:s.id,rank})})));}
function rng(seed){let x=Number(seed||1)>>>0;return()=>{x=(Math.imul(x,1664525)+1013904223)>>>0;return x/4294967296;};}
function shuffle(deck,random){const cards=deck.map(c=>({...c}));for(let i=cards.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]];}return cards;}
function sortHand(hand){return hand.sort((a,b)=>SUITS.findIndex(s=>s.id===a.suit)-SUITS.findIndex(s=>s.id===b.suit)||b.strength-a.strength);}
export function createAcademyState({playerCount=3,seed=Date.now(),mode="practice"}={}){const seats=SEATS.slice(0,playerCount===4?4:3);const deck=shuffle(makeDeck(),rng(seed));const hands=Object.fromEntries(seats.map(s=>[s,[]]));deck.forEach((card,i)=>hands[seats[i%seats.length]].push(card));Object.values(hands).forEach(sortHand);const opener=seats.find(s=>hands[s].some(c=>c.id==="taj-raja"))||seats[0];return{gameId:AURORA_GANJIFA_RULESET.gameId,rulesetVersion:AURORA_GANJIFA_RULESET.rulesetVersion,mode,playerCount:seats.length,seats,hands,currentPlayer:opener,leader:opener,currentTrick:[],ledSuit:null,completedTricks:[],tricksWon:Object.fromEntries(seats.map(s=>[s,0])),capturedCards:Object.fromEntries(seats.map(s=>[s,0])),trickNumber:1,phase:"playing",winner:null,winners:[],isDraw:false,lastAction:null};}
export function createFollowSuitLesson(){const state=createAcademyState({playerCount:3,seed:1,mode:"lesson"});const deck=makeDeck();const get=id=>deck.find(c=>c.id===id);state.hands={north:[get("taj-7"),get("surkh-10")],west:[get("taj-1"),get("surkh-1")],south:[get("taj-10"),get("barat-raja")]};state.currentPlayer="north";state.leader="north";state.currentTrick=[];state.completedTricks=[];state.tricksWon={north:0,west:0,south:0};state.capturedCards={north:0,west:0,south:0};return state;}
function nextSeat(state,seat){return state.seats[(state.seats.indexOf(seat)+1)%state.seats.length];}
export function getLegalActions(state,seat=state.currentPlayer){if(!state||state.phase!=="playing"||seat!==state.currentPlayer)return[];const hand=state.hands[seat]||[];const led=state.currentTrick[0]?.card.suit;const matching=led?hand.filter(c=>c.suit===led):hand;const legal=led&&matching.length?matching:hand;return legal.map(c=>({type:"play-card",seat,cardId:c.id}));}
export function applyAction(state,action,seat=state.currentPlayer){const legal=getLegalActions(state,seat).find(a=>a.cardId===action?.cardId);if(!legal)return{state,error:"Follow the led suit when you hold it."};const next=structuredClone(state);const hand=next.hands[seat];const [played]=hand.splice(hand.findIndex(c=>c.id===legal.cardId),1);next.currentTrick.push({seat,card:played});next.ledSuit=next.currentTrick[0].card.suit;next.lastAction={type:"play-card",seat,cardId:played.id,trickNumber:next.trickNumber};if(next.currentTrick.length<next.playerCount){next.currentPlayer=nextSeat(next,seat);}else{const winning=[...next.currentTrick].filter(p=>p.card.suit===next.ledSuit).sort((a,b)=>b.card.strength-a.card.strength)[0];next.completedTricks.push({number:next.trickNumber,ledSuit:next.ledSuit,winner:winning.seat,cards:next.currentTrick});next.tricksWon[winning.seat]++;next.capturedCards[winning.seat]+=next.playerCount;next.lastAction.trickWinner=winning.seat;next.currentTrick=[];next.ledSuit=null;next.leader=winning.seat;next.currentPlayer=winning.seat;next.trickNumber++;if(next.seats.every(s=>next.hands[s].length===0)){const best=Math.max(...next.seats.map(s=>next.capturedCards[s]));next.winners=next.seats.filter(s=>next.capturedCards[s]===best);next.winner=next.winners.length===1?next.winners[0]:null;next.isDraw=next.winners.length>1;next.phase="finished";}}return{state:next,error:null};}
