const { randomUUID, createHash } = require("crypto");
const { KHASI_FISHFLOW_RULESET, applyAction, createKhasiFishflowState, getLegalActions, getCounts, assertInvariant } = require("./khasiFishflowRules.js");

function createKhasiFishflowService(deps) {
  const { rooms, profiles, sockets, send, ok, fail, walletOf, profileFor, saveRoomSafe, saveHistoryEntry, getHistoryForWallet } = deps;
  const players = (room) => Object.values(room.players || {});
  const sha256 = (value) => createHash("sha256").update(String(value)).digest("hex");
  const code = () => { const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; let out = ""; for (let i = 0; i < 4; i += 1) out += chars[Math.floor(Math.random() * chars.length)]; return rooms.has(out) ? code() : out; };
  const isRoom = (room) => room?.gameId === KHASI_FISHFLOW_RULESET.gameId;
  const normalizeSide = (value) => value === "coral" ? "coral" : "blue";
  const opposite = (side) => side === "blue" ? "coral" : "blue";
  function requireProfile(ws, requestId, payload) { const wallet = walletOf(payload.wallet); if (!wallet || !profiles.has(wallet)) { fail(ws, requestId, "Create profile first."); return null; } sockets.set(wallet, ws); return wallet; }
  function findRoom(ws, requestId, payload) { const room = rooms.get(String(payload.roomCode || "").toUpperCase()); if (!room || !isRoom(room)) { fail(ws, requestId, "Khasi Fishflow room not found."); return null; } return room; }
  function audit(room, event) { room.auditLog ||= []; const previousHash = room.lastAuditHash || null; const body = { at: Date.now(), seq: room.auditLog.length + 1, previousHash, ...event }; const eventHash = sha256(JSON.stringify({ roomCode: room.roomCode, matchId: room.matchId, body })); room.lastAuditHash = eventHash; room.auditLog.push({ ...body, eventHash }); }
  function roomView(room) { const ps = players(room); return { id: room.id, gameId: room.gameId, rulesetVersion: room.rulesetVersion, roomCode: room.roomCode, visibility: room.visibility, status: room.status, matchId: room.matchId, createdAt: room.createdAt, updatedAt: room.updatedAt, startedAt: room.startedAt || null, finalizedAt: room.finalizedAt || null, playerCount: ps.length, maxPlayers: 2, gameState: room.gameState, result: room.result || null, proofHash: room.proofHash || null, players: ps.map((player) => ({ wallet: player.wallet, name: profileFor(player.wallet)?.name || "Player", role: player.side, side: player.side, joinedAt: player.joinedAt })) }; }
  function broadcast(room) { room.updatedAt = Date.now(); saveRoomSafe(room); const packet = { type: "kf_room_state", payload: { room: roomView(room) } }; players(room).forEach((player) => { const socket = sockets.get(player.wallet); if (socket) send(socket, packet); }); }
  function createRoom(ws, requestId, payload = {}) { const wallet = requireProfile(ws, requestId, payload); if (!wallet) return; const roomCode = code(); const side = normalizeSide(payload.side); const now = Date.now(); const room = { id: randomUUID(), gameId: KHASI_FISHFLOW_RULESET.gameId, rulesetVersion: KHASI_FISHFLOW_RULESET.rulesetVersion, roomCode, roomMode: "open_ice", visibility: payload.visibility === "private" ? "private" : "public", status: "waiting", matchId: `kf-${randomUUID()}`, createdAt: now, updatedAt: now, players: { [wallet]: { wallet, side, joinedAt: now } }, gameState: createKhasiFishflowState({ mode: "online", starter: "blue" }), auditLog: [] }; audit(room, { type: "room_created", wallet, side }); rooms.set(roomCode, room); saveRoomSafe(room); ok(ws, requestId, "kf_room_create_result", { room: roomView(room) }); broadcast(room); }
  function listRooms(ws, requestId) { ok(ws, requestId, "kf_room_list_result", { rooms: [...rooms.values()].filter(isRoom).filter((room) => room.visibility === "public" && room.status === "waiting").map(roomView) }); }
  function joinRoom(ws, requestId, payload = {}) { const wallet = requireProfile(ws, requestId, payload); if (!wallet) return; const room = findRoom(ws, requestId, payload); if (!room) return; if (room.players[wallet]) return ok(ws, requestId, "kf_room_join_result", { room: roomView(room) }); if (room.status !== "waiting" || players(room).length >= 2) return fail(ws, requestId, "Room is no longer open."); const side = opposite(players(room)[0].side); room.players[wallet] = { wallet, side, joinedAt: Date.now() }; room.status = "playing"; room.startedAt = Date.now(); audit(room, { type: "player_joined", wallet, side }); ok(ws, requestId, "kf_room_join_result", { room: roomView(room) }); broadcast(room); }
  function getState(ws, requestId, payload = {}) { const wallet = requireProfile(ws, requestId, payload); if (!wallet) return; const room = findRoom(ws, requestId, payload); if (!room) return; if (!room.players[wallet]) return fail(ws, requestId, "Join the room first."); ok(ws, requestId, "kf_game_state_result", { room: roomView(room) }); }
  function legalActions(ws, requestId, payload = {}) { const wallet = requireProfile(ws, requestId, payload); if (!wallet) return; const room = findRoom(ws, requestId, payload); if (!room) return; const player = room.players[wallet]; const actions = player && room.status === "playing" && player.side === room.gameState.currentPlayer ? getLegalActions(room.gameState, player.side) : []; ok(ws, requestId, "kf_legal_actions_result", { actions, room: roomView(room) }); }
  function action(ws, requestId, payload = {}) { const wallet = requireProfile(ws, requestId, payload); if (!wallet) return; const room = findRoom(ws, requestId, payload); if (!room) return; const player = room.players[wallet]; if (!player) return fail(ws, requestId, "Join the room first."); if (room.status !== "playing") return fail(ws, requestId, "Waiting for a second player."); if (player.side !== room.gameState.currentPlayer) return fail(ws, requestId, "It is not your turn."); let result; try { result = applyAction(room.gameState, payload.action, player.side); } catch (error) { return fail(ws, requestId, error.message); } if (result.error) return fail(ws, requestId, result.error); room.gameState = result.state; audit(room, { type: "sow", wallet, side: player.side, action: payload.action, summary: room.gameState.lastTurn }); if (room.gameState.winner) finalize(room); ok(ws, requestId, "kf_game_action_result", { room: roomView(room) }); broadcast(room); }
  async function history(ws, requestId, payload = {}) { const wallet = requireProfile(ws, requestId, payload); if (!wallet) return; try { ok(ws, requestId, "kf_history_result", { history: await getHistoryForWallet(wallet, KHASI_FISHFLOW_RULESET.gameId) }); } catch (error) { fail(ws, requestId, error.message); } }
  function myRooms(ws, requestId, payload = {}) { const wallet = requireProfile(ws, requestId, payload); if (!wallet) return; ok(ws, requestId, "kf_my_rooms_result", { rooms: [...rooms.values()].filter(isRoom).filter((room) => room.players?.[wallet]).map(roomView) }); }
  function finalize(room) { if (room.finalizedAt) return; room.status = "finished"; room.finalizedAt = Date.now(); const winnerPlayer = players(room).find((player) => player.side === room.gameState.winner); room.result = { winner: room.gameState.winner, winnerWallet: winnerPlayer?.wallet || null, reason: room.gameState.winReason, counts: { blue: getCounts(room.gameState).blue, coral: getCounts(room.gameState).coral } }; room.proofHash = sha256(JSON.stringify({ gameId: room.gameId, rulesetVersion: room.rulesetVersion, matchId: room.matchId, gameState: room.gameState, auditLog: room.auditLog })); audit(room, { type: "game_finished", result: room.result, proofHash: room.proofHash }); players(room).forEach((player) => saveHistoryEntry({ id: `${room.matchId}-${player.wallet}`, gameId: room.gameId, rulesetVersion: room.rulesetVersion, roomCode: room.roomCode, matchId: room.matchId, roomMode: "open_ice", wallet: player.wallet, playerName: profileFor(player.wallet)?.name || "Player", team: player.side, position: player.wallet === room.result.winnerWallet ? 1 : 2, won: player.wallet === room.result.winnerWallet, draw: false, points: player.wallet === room.result.winnerWallet ? 18 : 4, startedAt: room.startedAt, finishedAt: room.finalizedAt, proofHash: room.proofHash, result: room.result })); }
  function restoreRoom(room) { if (!isRoom(room)) return false; room.gameState ||= createKhasiFishflowState({ mode: "online" }); room.auditLog ||= []; assertInvariant(room.gameState); return true; }
  return { createRoom, listRooms, joinRoom, getState, legalActions, action, history, myRooms, restoreRoom, roomView };
}
module.exports = { createKhasiFishflowService };
