const RUMA_RULESET = Object.freeze({ gameId: "ruma-ice-puzzle", rulesetVersion: "tchuka-ruma-degrazia-1948-campbell-chavey-1995-1.0.0", ordinaryPits: 4, openingSeedsPerPit: 2, totalSeeds: 8 });
const clone = (value) => JSON.parse(JSON.stringify(value));
function createRumaState({ mode = "classic" } = {}) { return { gameId:RUMA_RULESET.gameId, rulesetVersion:RUMA_RULESET.rulesetVersion, mode, pits:[2,2,2,2], ruma:0, status:"playing", moves:0, lastMove:null, history:[] }; }
function createLastPebbleDrill(){ return { ...createRumaState({mode:"drill"}), pits:[0,0,0,1], ruma:7 }; }
function getLegalStarts(state){ if(!state||state.status!=="playing") return []; return state.pits.map((count,index)=>count>0?index:-1).filter((index)=>index>=0); }
function resolveRumaMove(state,startPit){ let hand=state.pits[startPit]; state.pits[startPit]=0; let cursor=startPit; let sowings=0; let drops=0; const chain=[startPit]; const seen=new Set(); while(true){ const signature=`${cursor}|${hand}|${state.pits.join(",")}|${state.ruma}`; if(seen.has(signature)) return {lost:true,reason:"cycle",sowings,drops,chain,landing:cursor}; seen.add(signature); sowings+=1; let landing=null; while(hand>0){ cursor=(cursor+1)%5; if(cursor===4) state.ruma+=1; else state.pits[cursor]+=1; hand-=1; drops+=1; landing=cursor; } if(landing===4) return {lost:false,reason:"ruma",sowings,drops,chain,landing:"ruma"}; if(state.pits[landing]===1) return {lost:true,reason:"empty-pit",sowings,drops,chain,landing}; hand=state.pits[landing]; state.pits[landing]=0; cursor=landing; chain.push(landing); } }
function applyRumaMove(state,startPit){ if(!state||state.status!=="playing") return {state,error:"This Ruma puzzle is already complete."}; if(!Number.isInteger(startPit)||startPit<0||startPit>=4||state.pits[startPit]<=0) return {state,error:"Choose one non-empty ordinary pit."}; const next=clone(state); const resolved=resolveRumaMove(next,startPit); next.moves+=1; next.lastMove={type:"sow",startPit,...resolved}; next.history.push(clone(next.lastMove)); if(resolved.lost) next.status="lost"; else if(next.ruma===8&&next.pits.every((count)=>count===0)) next.status="won"; assertRumaInvariant(next); return {state:next,error:null}; }
function canForceWin(state,memo=new Map(),visiting=new Set()){ if(state.status==="won") return true; if(state.status==="lost") return false; const key=`${state.pits.join(",")}|${state.ruma}`; if(memo.has(key)) return memo.get(key); if(visiting.has(key)) return false; visiting.add(key); let win=false; for(const pit of getLegalStarts(state)){ if(canForceWin(applyRumaMove(state,pit).state,memo,visiting)){win=true;break;} } visiting.delete(key); memo.set(key,win); return win; }
function getWinningStarts(state){ const memo=new Map(); const visiting=new Set(); return getLegalStarts(state).filter((pit)=>canForceWin(applyRumaMove(state,pit).state,memo,visiting)); }
function assertRumaInvariant(state){ const total=state.ruma+state.pits.reduce((sum,count)=>sum+count,0); if(total!==8) throw new Error(`Tchuka Ruma seed invariant failed: ${total}.`); return true; }
module.exports={RUMA_RULESET,createRumaState,createLastPebbleDrill,getLegalStarts,applyRumaMove,getWinningStarts,assertRumaInvariant};
