// Generated by frontend/scripts/build-sanguo-engine.mjs. Do not edit by hand.
Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
//#region src/games/heritage-arcade/ported/game/sanguoRailGraph.ts
const SOURCE_RAIL_EDGES = [
	["blue-0-0", "blue-0-1"],
	["blue-0-0", "blue-1-2"],
	["blue-0-4", "blue-0-5"],
	["blue-0-4", "blue-1-4"],
	["blue-0-5", "blue-1-4"],
	["blue-0-6", "blue-1-4"],
	["blue-1-0", "blue-1-1"],
	["blue-1-0", "blue-4-0"],
	["blue-0-4", "green-0-4"],
	["blue-1-1", "blue-1-2"],
	["blue-1-1", "blue-2-1"],
	["blue-1-2", "blue-1-3"],
	["blue-1-2", "blue-4-2"],
	["blue-1-3", "blue-1-4"],
	["blue-1-3", "blue-3-3"],
	["blue-1-4", "blue-1-5"],
	["blue-1-4", "blue-2-4"],
	["blue-1-6", "blue-4-6"],
	["blue-1-7", "blue-1-8"],
	["blue-1-7", "blue-2-7"],
	["blue-1-8", "blue-4-8"],
	["blue-0-4", "red-0-4"],
	["blue-2-0", "blue-4-1"],
	["blue-2-1", "blue-4-1"],
	["blue-2-3", "blue-3-4"],
	["blue-2-4", "blue-3-4"],
	["blue-2-5", "blue-2-7"],
	["blue-2-5", "blue-3-8"],
	["blue-3-0", "blue-3-1"],
	["blue-3-0", "blue-4-2"],
	["blue-3-1", "blue-3-2"],
	["blue-3-2", "blue-3-3"],
	["blue-3-4", "blue-3-5"],
	["blue-3-4", "blue-4-3"],
	["blue-3-4", "blue-4-4"],
	["blue-3-4", "blue-4-5"],
	["blue-3-5", "blue-4-2"],
	["blue-3-8", "blue-4-7"],
	["blue-4-0", "blue-4-1"],
	["blue-4-1", "blue-4-2"],
	["blue-4-2", "blue-4-3"],
	["blue-4-3", "blue-4-4"],
	["blue-4-4", "blue-4-5"],
	["blue-4-5", "blue-4-6"],
	["blue-4-6", "blue-4-7"],
	["blue-4-7", "blue-4-8"],
	["green-0-0", "green-0-1"],
	["green-0-0", "green-1-2"],
	["green-0-1", "green-1-2"],
	["green-0-4", "green-0-5"],
	["green-0-4", "green-1-4"],
	["green-0-5", "green-1-4"],
	["green-0-6", "green-1-4"],
	["green-1-0", "green-1-1"],
	["green-1-0", "green-4-0"],
	["green-1-1", "green-1-2"],
	["green-1-1", "green-2-1"],
	["green-1-2", "green-1-3"],
	["green-1-2", "green-4-2"],
	["green-1-3", "green-1-4"],
	["green-1-3", "green-3-3"],
	["green-1-4", "green-1-5"],
	["green-1-4", "green-2-4"],
	["green-1-6", "green-4-6"],
	["green-1-7", "green-1-8"],
	["green-1-7", "green-2-7"],
	["green-1-8", "green-4-8"],
	["green-0-4", "red-0-4"],
	["green-2-0", "green-4-1"],
	["green-2-1", "green-4-1"],
	["green-2-3", "green-3-4"],
	["green-2-4", "green-3-4"],
	["green-2-5", "green-2-7"],
	["green-3-0", "green-3-1"],
	["green-3-0", "green-4-2"],
	["green-3-1", "green-3-2"],
	["green-3-2", "green-3-3"],
	["green-3-4", "green-3-5"],
	["green-3-4", "green-4-3"],
	["green-3-4", "green-4-4"],
	["green-3-4", "green-4-5"],
	["green-3-8", "green-4-7"],
	["green-4-0", "green-4-1"],
	["green-4-1", "green-4-2"],
	["green-4-2", "green-4-3"],
	["green-4-3", "green-4-4"],
	["green-4-4", "green-4-5"],
	["green-4-5", "green-4-6"],
	["green-4-6", "green-4-7"],
	["green-4-7", "green-4-8"],
	["red-0-0", "red-1-3"],
	["red-0-3", "red-1-4"],
	["red-0-4", "red-1-4"],
	["red-0-5", "red-1-4"],
	["red-0-8", "red-1-5"],
	["red-1-0", "red-1-1"],
	["red-1-1", "red-1-2"],
	["red-1-1", "red-2-1"],
	["red-1-2", "red-1-3"],
	["red-1-2", "red-2-2"],
	["red-1-3", "red-1-4"],
	["red-1-3", "red-2-3"],
	["red-1-4", "red-1-5"],
	["red-1-4", "red-2-4"],
	["red-1-5", "red-1-6"],
	["red-1-5", "red-2-5"],
	["red-1-6", "red-1-7"],
	["red-1-6", "red-2-6"],
	["red-1-7", "red-1-8"],
	["red-1-7", "red-2-7"],
	["red-1-8", "red-4-8"],
	["red-2-0", "red-2-1"],
	["red-2-1", "red-4-1"],
	["red-2-2", "red-3-3"],
	["red-2-3", "red-4-3"],
	["red-2-4", "red-3-6"],
	["red-2-5", "red-4-5"],
	["red-2-6", "red-4-6"],
	["red-2-7", "red-2-8"],
	["red-2-7", "red-4-7"],
	["red-3-0", "red-3-1"],
	["red-3-1", "red-3-2"],
	["red-3-2", "red-3-3"],
	["red-3-6", "red-4-4"],
	["red-4-0", "red-4-1"],
	["red-4-1", "red-4-2"],
	["red-4-2", "red-4-3"],
	["red-4-3", "red-4-4"],
	["red-4-4", "red-4-5"],
	["red-4-5", "red-4-6"],
	["red-4-6", "red-4-7"],
	["red-4-7", "red-4-8"]
];
const SOURCE_RAIL_ADJACENCY = /* @__PURE__ */ new Map();
for (const [from, to] of SOURCE_RAIL_EDGES) {
	SOURCE_RAIL_ADJACENCY.set(from, [...SOURCE_RAIL_ADJACENCY.get(from) ?? [], to]);
	SOURCE_RAIL_ADJACENCY.set(to, [...SOURCE_RAIL_ADJACENCY.get(to) ?? [], from]);
}
const logicalNode = (sector, rank, file) => ({
	sector,
	rank,
	file
});
const logicalNodeKey = (node) => `${node.sector}-${node.rank}-${node.file}`;
/**
* Non-visual river continuation table confirmed from the labelled board.
* Human labels are L1..L9; code files are 0..8.
*
* R1-B9, R2-B8, R3-B7, R4-B6,
* R5-B5-G5,
* R6-G4, R7-G3, R8-G2, R9-G1,
* B1-G9, B2-G8, B3-G7, B4-G6.
*/
const FILE_CONTINUATIONS = {
	red: [
		[{
			sector: "blue",
			file: 8
		}],
		[{
			sector: "blue",
			file: 7
		}],
		[{
			sector: "blue",
			file: 6
		}],
		[{
			sector: "blue",
			file: 5
		}],
		[{
			sector: "blue",
			file: 4
		}, {
			sector: "green",
			file: 4
		}],
		[{
			sector: "green",
			file: 3
		}],
		[{
			sector: "green",
			file: 2
		}],
		[{
			sector: "green",
			file: 1
		}],
		[{
			sector: "green",
			file: 0
		}]
	],
	blue: [
		[{
			sector: "green",
			file: 8
		}],
		[{
			sector: "green",
			file: 7
		}],
		[{
			sector: "green",
			file: 6
		}],
		[{
			sector: "green",
			file: 5
		}],
		[{
			sector: "red",
			file: 4
		}, {
			sector: "green",
			file: 4
		}],
		[{
			sector: "red",
			file: 3
		}],
		[{
			sector: "red",
			file: 2
		}],
		[{
			sector: "red",
			file: 1
		}],
		[{
			sector: "red",
			file: 0
		}]
	],
	green: [
		[{
			sector: "red",
			file: 8
		}],
		[{
			sector: "red",
			file: 7
		}],
		[{
			sector: "red",
			file: 6
		}],
		[{
			sector: "red",
			file: 5
		}],
		[{
			sector: "red",
			file: 4
		}, {
			sector: "blue",
			file: 4
		}],
		[{
			sector: "blue",
			file: 3
		}],
		[{
			sector: "blue",
			file: 2
		}],
		[{
			sector: "blue",
			file: 1
		}],
		[{
			sector: "blue",
			file: 0
		}]
	]
};
/**
* The only genuinely three-way movement junction.
*
* Each kingdom's (rank 0, file 4) is its L5 river endpoint. Reaching that
* endpoint presents two straight continuations: the L5 endpoint of each other
* kingdom. A piece may choose one branch; a single move never turns from one
* foreign branch into the other after choosing it.
*/
const CENTRAL_VERTEX_EXITS = {
	red: ["blue", "green"],
	blue: ["red", "green"],
	green: ["red", "blue"]
};
const isCentralVertexEndpoint = (node) => node.rank === 0 && node.file === 4;
/** Direct one-step river exits from a rank-0 endpoint. */
function riverExits(node) {
	if (node.rank !== 0) return [];
	if (isCentralVertexEndpoint(node)) return CENTRAL_VERTEX_EXITS[node.sector].map((sector) => logicalNode(sector, 0, 4));
	return (FILE_CONTINUATIONS[node.sector][node.file] ?? []).map((continuation) => logicalNode(continuation.sector, 0, continuation.file));
}
/** Standard Xiangqi horizontal rays inside one logical 5x9 sector. */
function rankRays(node) {
	const { sector, rank, file } = node;
	return [Array.from({ length: file }, (_, offset) => logicalNode(sector, rank, file - offset - 1)), Array.from({ length: 9 - file - 1 }, (_, offset) => logicalNode(sector, rank, file + offset + 1))].filter((ray) => ray.length > 0);
}
/**
* Xiangqi vertical rays plus one Sanguo boundary operation.
*
* Inside a sector this is ordinary file movement. When the inward ray reaches
* rank 0, it may continue through exactly one river exit. The chosen foreign
* file then continues from rank 0 toward rank 4 as an ordinary Xiangqi file.
* L5 simply produces two candidate rays because its river endpoint is the
* explicit three-way junction defined above.
*/
function fileRays(node) {
	const { sector, rank, file } = node;
	const outward = Array.from({ length: 4 - rank }, (_, offset) => logicalNode(sector, rank + offset + 1, file));
	const toRiver = Array.from({ length: rank }, (_, offset) => logicalNode(sector, rank - offset - 1, file));
	const exits = riverExits(logicalNode(sector, 0, file));
	return [outward, ...exits.length ? exits.map((exit) => [...toRiver, ...Array.from({ length: 5 }, (_, foreignRank) => logicalNode(exit.sector, foreignRank, exit.file))]) : [toRiver]].filter((ray) => ray.length > 0);
}
//#endregion
//#region src/games/heritage-arcade/ported/game/sanguoHorseMoves.ts
const sameNode$7 = (left, right) => left.sector === right.sector && left.rank === right.rank && left.file === right.file;
const occupant$8 = (pieces, node) => pieces.find((piece) => !piece.captured && sameNode$7(piece.node, node));
const unique$2 = (nodes) => [...new Map(nodes.map((node) => [`${node.sector}-${node.rank}-${node.file}`, node])).values()];
const landable$2 = (piece, pieces, node) => {
	const hit = occupant$8(pieces, node);
	return !hit || hit.controller !== piece.controller;
};
const insideFile$2 = (file) => file >= 0 && file <= 8;
const insideRank = (rank) => rank >= 0 && rank <= 4;
const HORSE_DELTAS = [
	[-2, -1],
	[-2, 1],
	[-1, -2],
	[-1, 2],
	[1, -2],
	[1, 2],
	[2, -1],
	[2, 1]
];
/** Standard same-sector Xiangqi Horse geometry on the logical 5x9 grid. */
function appendLocalHorseTargets(piece, pieces, output) {
	const { sector, rank, file } = piece.node;
	for (const [rankDelta, fileDelta] of HORSE_DELTAS) {
		const destinationRank = rank + rankDelta;
		const destinationFile = file + fileDelta;
		if (!insideRank(destinationRank) || !insideFile$2(destinationFile)) continue;
		if (occupant$8(pieces, Math.abs(rankDelta) === 2 ? {
			sector,
			rank: rank + Math.sign(rankDelta),
			file
		} : {
			sector,
			rank,
			file: file + Math.sign(fileDelta)
		})) continue;
		const destination = logicalNode(sector, destinationRank, destinationFile);
		if (landable$2(piece, pieces, destination)) output.push(destination);
	}
}
/**
* Xiangqi Horse movement with only the river boundary adapted for Sanguo.
* Local moves are the ordinary eight (±2,±1)/(±1,±2) possibilities. If an L
* reaches across rank 0, the final geometry uses the explicit river exit of the
* logical board; L5 may therefore choose either branch of the central junction.
*/
function sanguoHorseTargets(piece, pieces) {
	if (piece.captured) return [];
	const output = [];
	appendLocalHorseTargets(piece, pieces, output);
	for (const ray of fileRays(piece.node)) {
		if (ray.length < 2) continue;
		const leg = ray[0];
		const second = ray[1];
		if (occupant$8(pieces, leg)) continue;
		if (second.sector === piece.node.sector) continue;
		for (const side of [-1, 1]) {
			const destinationFile = second.file + side;
			if (!insideFile$2(destinationFile)) continue;
			const destination = logicalNode(second.sector, second.rank, destinationFile);
			if (landable$2(piece, pieces, destination)) output.push(destination);
		}
	}
	for (const ray of rankRays(piece.node)) {
		if (ray.length < 2) continue;
		const leg = ray[0];
		const second = ray[1];
		if (occupant$8(pieces, leg)) continue;
		for (const perpendicular of fileRays(second)) {
			const destination = perpendicular[0];
			if (!destination || destination.sector === piece.node.sector) continue;
			if (landable$2(piece, pieces, destination)) output.push(destination);
		}
	}
	return unique$2(output);
}
//#endregion
//#region src/games/heritage-arcade/ported/game/sanguoElephantMoves.ts
const sameNode$6 = (left, right) => left.sector === right.sector && left.rank === right.rank && left.file === right.file;
const occupant$7 = (pieces, node) => pieces.find((piece) => !piece.captured && sameNode$6(piece.node, node));
const insideHalfBoard = (rank, file) => rank >= 0 && rank <= 4 && file >= 0 && file <= 8;
const ELEPHANT_DELTAS = [
	[-2, -2],
	[-2, 2],
	[2, -2],
	[2, 2]
];
/**
* Exact Xiangqi Elephant movement on a Sanguo kingdom half-board.
*
* The Elephant moves exactly two points diagonally in one move. It cannot jump:
* the diagonal midpoint (the elephant eye) must be empty. As in Xiangqi, an
* Elephant may not cross the river, so every destination remains in the
* Elephant's current Sanguo sector. A friendly destination is forbidden; an
* enemy destination may be captured.
*/
function sanguoElephantTargets(piece, pieces) {
	if (piece.captured) return [];
	const output = [];
	const { sector, rank, file } = piece.node;
	for (const [rankDelta, fileDelta] of ELEPHANT_DELTAS) {
		const destinationRank = rank + rankDelta;
		const destinationFile = file + fileDelta;
		if (!insideHalfBoard(destinationRank, destinationFile)) continue;
		if (occupant$7(pieces, {
			sector,
			rank: rank + rankDelta / 2,
			file: file + fileDelta / 2
		})) continue;
		const destination = {
			sector,
			rank: destinationRank,
			file: destinationFile
		};
		const hit = occupant$7(pieces, destination);
		if (!hit || hit.controller !== piece.controller) output.push(destination);
	}
	return output;
}
//#endregion
//#region src/games/heritage-arcade/ported/game/sanguoAdvisorMoves.ts
const key$1 = (node) => `${node.sector}-${node.rank}-${node.file}`;
const sameNode$5 = (left, right) => left.sector === right.sector && left.rank === right.rank && left.file === right.file;
const occupant$6 = (pieces, node) => pieces.find((piece) => !piece.captured && sameNode$5(piece.node, node));
const PALACE_CORNERS = [
	{
		rank: 2,
		file: 3
	},
	{
		rank: 2,
		file: 5
	},
	{
		rank: 4,
		file: 3
	},
	{
		rank: 4,
		file: 5
	}
];
const PALACE_CENTER = {
	rank: 3,
	file: 4
};
/**
* Exact Xiangqi Advisor rule for one Sanguo kingdom palace.
*
* The Advisor moves exactly one diagonal palace step and may never leave its
* original kingdom's 3x3 palace. The palace has the normal Xiangqi X: the four
* corners connect only to the centre, and the centre connects to all four
* corners. Mid-edge palace points are not Advisor destinations because no
* diagonal palace rail reaches them.
*
* Appropriation changes controller, not the piece's original sector, so an
* appropriated Advisor remains confined to the palace printed in its own
* sector. It may capture an enemy-controlled coin on a legal destination but
* may not land on a friendly-controlled coin.
*/
function sanguoAdvisorTargets(piece, pieces) {
	if (piece.captured) return [];
	const { sector, rank, file } = piece.node;
	const isCenter = rank === PALACE_CENTER.rank && file === PALACE_CENTER.file;
	const isCorner = PALACE_CORNERS.some((corner) => corner.rank === rank && corner.file === file);
	let candidates = [];
	if (isCenter) candidates = PALACE_CORNERS.map((corner) => ({
		sector,
		rank: corner.rank,
		file: corner.file
	}));
	else if (isCorner) candidates = [{
		sector,
		rank: PALACE_CENTER.rank,
		file: PALACE_CENTER.file
	}];
	else return [];
	return [...new Map(candidates.map((node) => [key$1(node), node])).values()].filter((node) => {
		const hit = occupant$6(pieces, node);
		return !hit || hit.controller !== piece.controller;
	});
}
//#endregion
//#region src/games/heritage-arcade/ported/game/sanguoGeneralMoves.ts
const sameNode$4 = (left, right) => left.sector === right.sector && left.rank === right.rank && left.file === right.file;
const occupant$5 = (pieces, node) => pieces.find((piece) => !piece.captured && sameNode$4(piece.node, node));
const insidePalace = (piece, node) => node.sector === piece.sector && node.rank >= 2 && node.rank <= 4 && node.file >= 3 && node.file <= 5;
const ORTHOGONAL_STEPS = [
	[-1, 0],
	[1, 0],
	[0, -1],
	[0, 1]
];
/**
* Exact Xiangqi General rule for a Sanguo kingdom palace.
*
* The General moves exactly one point orthogonally and may never leave its
* original 3x3 palace. It never moves diagonally and never uses any of the
* cross-kingdom continuation lines.
*
* Friendly pieces block the destination. Enemy pieces may be captured there.
* Check, flying-General exposure, and moving into attack are enforced by the
* higher-level legal-move filter in sanguoRules.ts, so this function returns
* only the General's geometric pseudo-legal destinations.
*/
function sanguoGeneralTargets(piece, pieces) {
	if (piece.captured) return [];
	if (!insidePalace(piece, piece.node)) return [];
	return ORTHOGONAL_STEPS.map(([rankDelta, fileDelta]) => ({
		sector: piece.sector,
		rank: piece.node.rank + rankDelta,
		file: piece.node.file + fileDelta
	})).filter((node) => insidePalace(piece, node)).filter((node) => {
		const hit = occupant$5(pieces, node);
		return !hit || hit.controller !== piece.controller;
	});
}
//#endregion
//#region src/games/heritage-arcade/ported/game/sanguoSoldierMoves.ts
const sameNode$3 = (left, right) => left.sector === right.sector && left.rank === right.rank && left.file === right.file;
const occupant$4 = (pieces, node) => pieces.find((piece) => !piece.captured && sameNode$3(piece.node, node));
const insideFile$1 = (file) => file >= 0 && file <= 8;
const landable$1 = (piece, pieces, node) => {
	const hit = occupant$4(pieces, node);
	return !hit || hit.controller !== piece.controller;
};
/**
* Standard Xiangqi Soldier rule on a logical Sanguo sector.
*
* Home sector:
*   - exactly one point forward (rank - 1)
*   - at rank 0, forward means cross through the explicit river exit
*
* Foreign sector (river already crossed):
*   - one point forward deeper into that sector (rank + 1)
*   - or one point sideways (file ± 1)
*   - never backward
*
* The only Sanguo-specific case is rank-0 crossing. On L5, riverExits()
* explicitly returns both branches of the central three-way junction.
*/
function sanguoSoldierTargets(piece, pieces) {
	if (piece.captured) return [];
	const { sector: currentSector, rank, file } = piece.node;
	const crossedRiver = currentSector !== piece.sector;
	const candidates = [];
	if (!crossedRiver) if (rank > 0) candidates.push(logicalNode(currentSector, rank - 1, file));
	else candidates.push(...riverExits(piece.node));
	else {
		if (rank < 4) candidates.push(logicalNode(currentSector, rank + 1, file));
		if (insideFile$1(file - 1)) candidates.push(logicalNode(currentSector, rank, file - 1));
		if (insideFile$1(file + 1)) candidates.push(logicalNode(currentSector, rank, file + 1));
	}
	return candidates.filter((node) => landable$1(piece, pieces, node));
}
//#endregion
//#region src/games/heritage-arcade/ported/game/sanguoBannermanMoves.ts
const sameNode$2 = (left, right) => left.sector === right.sector && left.rank === right.rank && left.file === right.file;
const occupant$3 = (pieces, node) => pieces.find((piece) => !piece.captured && sameNode$2(piece.node, node));
const unique$1 = (nodes) => [...new Map(nodes.map((node) => [`${node.sector}-${node.rank}-${node.file}`, node])).values()];
const landable = (piece, pieces, node) => {
	const hit = occupant$3(pieces, node);
	return !hit || hit.controller !== piece.controller;
};
const insideFile = (file) => file >= 0 && file <= 8;
/**
* Optional Sanguo Bannerman rule on logical coordinates.
* Two clear orthogonal transit points, then one outward diagonal finish.
* The only non-Xiangqi geometry is a river-boundary continuation supplied by
* sanguoLogicalTopology; no pixel/rail tracing participates in the rule.
*/
function sanguoBannermanTargets(piece, pieces) {
	if (piece.captured) return [];
	const output = [];
	for (const ray of fileRays(piece.node)) {
		if (ray.length < 3) continue;
		const first = ray[0];
		const second = ray[1];
		const longEndpoint = ray[2];
		if (occupant$3(pieces, first) || occupant$3(pieces, second)) continue;
		for (const side of [-1, 1]) {
			const destinationFile = longEndpoint.file + side;
			if (!insideFile(destinationFile)) continue;
			const destination = logicalNode(longEndpoint.sector, longEndpoint.rank, destinationFile);
			if (landable(piece, pieces, destination)) output.push(destination);
		}
	}
	for (const ray of rankRays(piece.node)) {
		if (ray.length < 3) continue;
		const first = ray[0];
		const second = ray[1];
		const longEndpoint = ray[2];
		if (occupant$3(pieces, first) || occupant$3(pieces, second)) continue;
		for (const perpendicular of fileRays(longEndpoint)) {
			const destination = perpendicular[0];
			if (destination && landable(piece, pieces, destination)) output.push(destination);
		}
	}
	return unique$1(output);
}
//#endregion
//#region src/games/heritage-arcade/ported/game/sanguoGraphMoves.ts
const key = (node) => `${node.sector}-${node.rank}-${node.file}`;
const same = (left, right) => key(left) === key(right);
const occupant$2 = (pieces, node) => pieces.find((piece) => !piece.captured && same(piece.node, node));
const unique = (nodes) => [...new Map(nodes.map((node) => [key(node), node])).values()];
function appendChariotRay(piece, pieces, ray, output) {
	for (const node of ray) {
		const hit = occupant$2(pieces, node);
		if (!hit) {
			output.push(node);
			continue;
		}
		if (hit.controller !== piece.controller) output.push(node);
		break;
	}
}
/** Xiangqi Chariot rays on logical coordinates, extended only at a Sanguo river boundary. */
function chariotTargets(piece, pieces) {
	const output = [];
	for (const ray of [...rankRays(piece.node), ...fileRays(piece.node)]) appendChariotRay(piece, pieces, ray, output);
	return unique(output);
}
function appendCannonRay(piece, pieces, ray, output) {
	let screened = false;
	for (const node of ray) {
		const hit = occupant$2(pieces, node);
		if (!screened) {
			if (!hit) {
				output.push(node);
				continue;
			}
			screened = true;
			continue;
		}
		if (!hit) continue;
		if (hit.controller !== piece.controller) output.push(node);
		break;
	}
}
/** Xiangqi Cannon rule on the same logical straight rays as the Chariot. */
function cannonTargets(piece, pieces) {
	const output = [];
	for (const ray of [...rankRays(piece.node), ...fileRays(piece.node)]) appendCannonRay(piece, pieces, ray, output);
	return unique(output);
}
/** Authoritative pseudo-legal resolver. */
function logicalPseudoTargets(piece, pieces) {
	if (piece.captured) return [];
	if (piece.role === "icebreaker") return chariotTargets(piece, pieces);
	if (piece.role === "cannon") return cannonTargets(piece, pieces);
	if (piece.role === "king") return sanguoGeneralTargets(piece, pieces);
	if (piece.role === "guard") return sanguoAdvisorTargets(piece, pieces);
	if (piece.role === "seer") return sanguoElephantTargets(piece, pieces);
	if (piece.role === "rider") return sanguoHorseTargets(piece, pieces);
	if (piece.role === "runner") return sanguoBannermanTargets(piece, pieces);
	return sanguoSoldierTargets(piece, pieces);
}
//#endregion
//#region src/games/heritage-arcade/ported/game/sanguoSpecialRules.ts
const sameNode$1 = (left, right) => left.sector === right.sector && left.rank === right.rank && left.file === right.file;
const occupant$1 = (pieces, node) => pieces.find((piece) => !piece.captured && sameNode$1(piece.node, node));
/**
* Xiangqi flying-General prohibition on logical straight files.
*
* Within a sector this is the ordinary Xiangqi file test. If the sightline
* reaches rank 0, the Sanguo river layer may continue it into one foreign file.
* At L5 there are exactly two separately-tested branches from the explicit
* central three-way junction. Any intervening coin blocks that branch.
*/
function generalsFacingOnLogicalFiles(pieces) {
	const generals = pieces.filter((piece) => !piece.captured && piece.role === "king");
	for (const general of generals) for (const ray of fileRays(general.node)) for (const node of ray) {
		const hit = occupant$1(pieces, node);
		if (!hit) continue;
		if (hit.role === "king" && hit.id !== general.id) return true;
		break;
	}
	return false;
}
//#endregion
//#region src/games/heritage-arcade/ported/game/sanguoRules.ts
const sanguoFactions = [
	"red",
	"green",
	"blue"
];
const roleLabels = {
	king: "General",
	guard: "Advisor",
	seer: "Elephant",
	rider: "Horse",
	runner: "Bannerman",
	icebreaker: "Chariot",
	cannon: "Cannon",
	scout: "Soldier"
};
const nodeId = (node) => logicalNodeKey(node);
const sameNode = (left, right) => nodeId(left) === nodeId(right);
const sanguoNodeIds = () => sanguoFactions.flatMap((sector) => Array.from({ length: 45 }, (_, index) => logicalNodeKey({
	sector,
	rank: Math.floor(index / 9),
	file: index % 9
})));
const railNodeIds = new Set(sanguoNodeIds());
/** Renderer/audit-only validation. Movement legality does not use SOURCE_RAIL_EDGES. */
const graphHasOnlyKnownNodes = () => SOURCE_RAIL_EDGES.every(([from, to]) => railNodeIds.has(from) && railNodeIds.has(to));
const optionalBannermenCount = (enabled) => enabled ? 54 : 48;
const otherFactions = (faction) => sanguoFactions.filter((candidate) => candidate !== faction);
const occupant = (pieces, node) => pieces.find((piece) => !piece.captured && sameNode(piece.node, node));
/** Public pseudo-target resolver: logical Xiangqi geometry + explicit Sanguo boundary rules. */
const pseudoSanguoTargets = (piece, pieces) => logicalPseudoTargets(piece, pieces);
/** Xiangqi flying-General rule on logical files, including explicit L5 branching. */
function generalsFacing(pieces) {
	return generalsFacingOnLogicalFiles(pieces);
}
function generalIsAttacked(controller, pieces) {
	const general = pieces.find((piece) => !piece.captured && piece.sector === controller && piece.role === "king");
	return Boolean(general && pieces.some((piece) => !piece.captured && piece.controller !== controller && pseudoSanguoTargets(piece, pieces).some((target) => sameNode(target, general.node))));
}
const checkingPiecesAgainst = (defeated, victor, pieces) => {
	const general = pieces.find((piece) => !piece.captured && piece.sector === defeated && piece.role === "king");
	if (!general) return [];
	return pieces.filter((piece) => !piece.captured && piece.controller === victor && pseudoSanguoTargets(piece, pieces).some((target) => sameNode(target, general.node)));
};
const relocate = (pieces, piece, destination) => {
	const victim = occupant(pieces, destination);
	return pieces.map((candidate) => candidate.id === piece.id ? {
		...candidate,
		node: destination
	} : victim && candidate.id === victim.id ? {
		...candidate,
		captured: true
	} : candidate);
};
/**
* A legal move may not capture a General directly. Instead it must leave the
* opposing General with no legal reply; Sanguo then resolves that army in the
* documented separate appropriation turn.
*/
const legalSanguoTargets = (piece, pieces) => pseudoSanguoTargets(piece, pieces).filter((target) => {
	if (occupant(pieces, target)?.role === "king") return false;
	const next = relocate(pieces, piece, target);
	return !generalsFacing(next) && !generalIsAttacked(piece.controller, next);
});
const hasSanguoLegalMove = (controller, pieces) => pieces.some((piece) => !piece.captured && piece.controller === controller && legalSanguoTargets(piece, pieces).length > 0);
function initialSanguoPieces(includeBannermen = false) {
	const pieces = [];
	sanguoFactions.forEach((sector) => {
		const add = (role, rank, file, index) => pieces.push({
			id: `${sector}-${role}-${index}`,
			sector,
			controller: sector,
			role,
			node: {
				sector,
				rank,
				file
			}
		});
		[
			"icebreaker",
			"rider",
			"seer",
			"guard",
			"king",
			"guard",
			"seer",
			"rider",
			"icebreaker"
		].forEach((role, file) => add(role, 4, file, file));
		add("cannon", 2, 1, 0);
		add("cannon", 2, 7, 1);
		[
			0,
			2,
			4,
			6,
			8
		].forEach((file, index) => add("scout", 1, file, index));
		if (includeBannermen) {
			add("runner", 2, 3, 0);
			add("runner", 2, 5, 1);
		}
	});
	return pieces;
}
const initialSanguoState = (includeBannermen = false) => ({
	pieces: initialSanguoPieces(includeBannermen),
	turn: "red",
	defeated: [],
	winner: null,
	pending: null,
	note: "Shu / Red opens. Turns then proceed counterclockwise: Red → Green → Blue.",
	moveNumber: 1,
	lastMove: null
});
/** Shu/Red first, then counterclockwise Red → Green → Blue, skipping eliminated kingdoms. */
function nextSanguoTurn(current, defeated) {
	for (let offset = 1; offset <= sanguoFactions.length; offset += 1) {
		const candidate = sanguoFactions[(sanguoFactions.indexOf(current) + offset) % sanguoFactions.length];
		if (!defeated.includes(candidate)) return candidate;
	}
	return current;
}
const winnerFromDefeats = (defeated) => {
	const survivors = sanguoFactions.filter((faction) => !defeated.includes(faction));
	return survivors.length === 1 ? survivors[0] : null;
};
const appropriateArmy = (pieces, defeated, victor) => pieces.map((piece) => piece.controller === defeated && !piece.captured && piece.role !== "king" ? {
	...piece,
	controller: victor
} : piece);
const removeGeneralAndAppropriate = (pieces, resolution) => pieces.map((piece) => piece.controller !== resolution.defeated ? piece : piece.role === "king" ? {
	...piece,
	captured: true
} : piece.captured ? piece : {
	...piece,
	controller: resolution.victor
});
function applySanguoMove(state, pieceId, destination) {
	if (state.winner || state.draw || state.pending) return null;
	const piece = state.pieces.find((candidate) => candidate.id === pieceId);
	if (!piece || piece.captured || piece.controller !== state.turn || !legalSanguoTargets(piece, state.pieces).some((target) => sameNode(target, destination))) return null;
	const victim = occupant(state.pieces, destination);
	const pieces = relocate(state.pieces, piece, destination);
	const nextTurn = nextSanguoTurn(state.turn, state.defeated);
	const lastMove = {
		pieceId,
		from: piece.node,
		to: destination,
		controller: state.turn,
		role: piece.role,
		captured: victim?.role
	};
	const action = `${roleLabels[piece.role]} ${victim ? `captures ${roleLabels[victim.role]}` : "advances"}`;
	const nextInCheck = generalIsAttacked(nextTurn, pieces);
	if (!hasSanguoLegalMove(nextTurn, pieces)) {
		const reason = nextInCheck ? "checkmate" : "stalemate";
		const checkers = reason === "checkmate" ? checkingPiecesAgainst(nextTurn, state.turn, pieces) : [];
		const matingPieceId = checkers.some((checker) => checker.id === piece.id) ? piece.id : checkers[0]?.id;
		return {
			...state,
			pieces,
			pending: {
				defeated: nextTurn,
				victor: state.turn,
				reason,
				matingPieceId
			},
			note: `${action}. ${nextTurn} has no legal reply: resolve ${reason} appropriation.`,
			moveNumber: state.moveNumber + 1,
			lastMove
		};
	}
	return trackSanguoPosition({
		...state,
		pieces,
		turn: nextTurn,
		note: nextInCheck ? `${action}. ${nextTurn} is in check and must answer it.` : `${action}. ${nextTurn} to move.`,
		moveNumber: state.moveNumber + 1,
		lastMove,
		positions: state.positions ?? [sanguoPositionKey(state)],
		quietMoves: victim || piece.role === "scout" ? 0 : (state.quietMoves ?? 0) + 1
	});
}
/** Arctic completion rules: three identical positions, or 120 quiet plies, draw. */
function sanguoPositionKey(state) {
	const roleCode = {
		king: "k",
		guard: "g",
		seer: "e",
		rider: "h",
		runner: "b",
		icebreaker: "r",
		cannon: "c",
		scout: "s"
	};
	return state.turn + ":" + state.pieces.filter((p) => !p.captured).map((p) => `${p.sector[0]}${p.controller[0]}${roleCode[p.role]}${p.node.sector[0]}${p.node.rank}${p.node.file}`).sort().join("");
}
function trackSanguoPosition(state) {
	const key = sanguoPositionKey(state);
	const positions = [...state.positions ?? [], key].slice(-121);
	const draw = positions.filter((p) => p === key).length >= 3 ? "repetition" : (state.quietMoves ?? 0) >= 120 ? "no-progress" : void 0;
	return {
		...state,
		positions,
		...draw ? {
			draw,
			note: draw === "repetition" ? "Draw: the same position occurred three times." : "Draw: 120 moves without a capture or Soldier move."
		} : {}
	};
}
const placeMatingPieceOnGeneral = (pieces, resolution) => {
	if (resolution.reason !== "checkmate" || !resolution.matingPieceId) return pieces;
	const general = pieces.find((piece) => !piece.captured && piece.sector === resolution.defeated && piece.role === "king");
	const matingPiece = pieces.find((piece) => !piece.captured && piece.id === resolution.matingPieceId && piece.controller === resolution.victor);
	if (!general || !matingPiece) return pieces;
	return pieces.map((piece) => piece.id === matingPiece.id ? {
		...piece,
		node: general.node
	} : piece);
};
function resolveSanguoAppropriation(state) {
	if (!state.pending) return null;
	const defeated = [...state.defeated, state.pending.defeated];
	const pieces = removeGeneralAndAppropriate(placeMatingPieceOnGeneral(state.pieces, state.pending), state.pending);
	const winner = winnerFromDefeats(defeated);
	if (winner) return {
		...state,
		pieces,
		defeated,
		winner,
		pending: null,
		note: `${winner} is the last surviving kingdom.`,
		lastMove: state.lastMove
	};
	const turn = nextSanguoTurn(state.turn, defeated);
	const next = {
		...state,
		pieces,
		defeated,
		turn,
		pending: null,
		note: `${state.pending.victor} appropriates the ${state.pending.defeated} army. ${turn} to move.`,
		lastMove: state.lastMove,
		positions: [],
		quietMoves: 0
	};
	if (!hasSanguoLegalMove(turn, pieces)) {
		const check = generalIsAttacked(turn, pieces);
		next.pending = {
			defeated: turn,
			victor: state.pending.victor,
			reason: check ? "checkmate" : "stalemate",
			matingPieceId: checkingPiecesAgainst(turn, state.pending.victor, pieces)[0]?.id
		};
		next.turn = state.pending.victor;
		next.note = `${turn} has no legal reply after appropriation. Resolve its army.`;
	}
	return next;
}
/** Resignation is an explicit Arctic completion: the resigning army leaves play. */
function resignSanguoFaction(state, faction) {
	if (state.winner || state.draw || state.defeated.includes(faction)) return null;
	if (state.pending) {
		const resolved = resolveSanguoAppropriation(state);
		return resolved.winner || resolved.defeated.includes(faction) ? resolved : resignSanguoFaction(resolved, faction);
	}
	const defeated = [...state.defeated, faction];
	const pieces = state.pieces.map((p) => p.controller === faction ? {
		...p,
		captured: true
	} : p);
	const turn = state.turn === faction ? nextSanguoTurn(faction, defeated) : state.turn;
	const winner = winnerFromDefeats(defeated);
	const next = {
		...state,
		pieces,
		defeated,
		turn,
		winner,
		positions: [],
		quietMoves: 0,
		note: winner ? `${winner} is the last surviving kingdom.` : `${faction} resigned. ${turn} to move.`
	};
	if (!winner && !hasSanguoLegalMove(turn, pieces)) {
		const victor = nextSanguoTurn(turn, defeated);
		next.pending = {
			defeated: turn,
			victor,
			reason: generalIsAttacked(turn, pieces) ? "checkmate" : "stalemate",
			matingPieceId: checkingPiecesAgainst(turn, victor, pieces)[0]?.id
		};
		next.turn = victor;
	}
	return next;
}
const sanguoStateFrom = (pieces, turn = "red", defeated = []) => ({
	pieces,
	turn,
	defeated,
	winner: null,
	pending: null,
	note: "Test state loaded.",
	moveNumber: 1,
	lastMove: null
});
//#endregion
//#region src/games/heritage-arcade/ported/game/sanguoBot.ts
const BOT_LEVELS = {
	easy: {
		label: "Easy",
		description: "Plays legal moves with a little capture preference.",
		depth: 1,
		width: 6,
		budget: 150
	},
	medium: {
		label: "Medium",
		description: "Weighs captures, development and threatened pieces.",
		depth: 1,
		width: 60,
		budget: 600
	},
	hard: {
		label: "Hard",
		description: "Searches both rivals’ replies and protects its army.",
		depth: 3,
		width: 3,
		budget: 1800
	}
};
const VALUE = {
	king: 2e4,
	icebreaker: 900,
	cannon: 450,
	rider: 400,
	runner: 450,
	guard: 180,
	seer: 180,
	scout: 100
};
function sanguoActions(state) {
	if (state.winner || state.draw) return [];
	if (state.pending) return [{ type: "resolve" }];
	return state.pieces.filter((p) => !p.captured && p.controller === state.turn).flatMap((p) => legalSanguoTargets(p, state.pieces).map((to) => ({
		type: "move",
		pieceId: p.id,
		to
	})));
}
function applySanguoAction(state, action) {
	return action.type === "resolve" ? resolveSanguoAppropriation(state) : applySanguoMove(state, action.pieceId, action.to);
}
/** One utility per kingdom: each opponent optimizes its own position (MaxN). */
function evaluateSanguo(state) {
	const scores = {
		red: 0,
		green: 0,
		blue: 0
	};
	if (state.draw) return scores;
	if (state.winner) return Object.fromEntries(sanguoFactions.map((f) => [f, f === state.winner ? 1e6 : -1e6]));
	const threats = {
		red: /* @__PURE__ */ new Set(),
		green: /* @__PURE__ */ new Set(),
		blue: /* @__PURE__ */ new Set()
	};
	for (const p of state.pieces) if (!p.captured) for (const target of pseudoSanguoTargets(p, state.pieces)) threats[p.controller].add(nodeId(target));
	for (const p of state.pieces) if (!p.captured) {
		let worth = VALUE[p.role];
		const progress = p.node.sector === p.sector ? 4 - p.node.rank : 5 + p.node.rank;
		if (p.role === "scout") worth += progress * 12;
		if ([
			"rider",
			"cannon",
			"icebreaker"
		].includes(p.role)) worth += progress * 4;
		if (sanguoFactions.some((f) => f !== p.controller && threats[f].has(nodeId(p.node))) && p.role !== "king") worth -= VALUE[p.role] * (threats[p.controller].has(nodeId(p.node)) ? .22 : .7);
		scores[p.controller] += worth;
	}
	for (const f of sanguoFactions) if (state.defeated.includes(f)) scores[f] = -1e6;
	else if (generalIsAttacked(f, state.pieces)) scores[f] -= 120;
	const own = { ...scores };
	for (const f of sanguoFactions) if (!state.defeated.includes(f)) scores[f] -= sanguoFactions.filter((g) => g !== f && !state.defeated.includes(g)).reduce((sum, g) => sum + own[g] * .4, 0);
	return scores;
}
function chooseSanguoBotAction(state, difficulty = "medium", options = {}) {
	const level = BOT_LEVELS[difficulty] || BOT_LEVELS.medium;
	const started = performance.now();
	const deadline = started + (options.budgetMs ?? level.budget);
	const random = options.random ?? Math.random;
	const actions = sanguoActions(state);
	let nodes = 0, completedDepth = 0;
	const result = (action) => ({
		action,
		stats: {
			nodes,
			completedDepth,
			elapsedMs: Math.round(performance.now() - started)
		}
	});
	if (!actions.length) return result(null);
	if (state.pending) return result(actions[0]);
	const captureValue = (action, position) => action.type === "move" ? VALUE[position.pieces.find((p) => !p.captured && nodeId(p.node) === nodeId(action.to))?.role] || 0 : 5e4;
	if (difficulty === "easy") {
		const captures = actions.filter((a) => captureValue(a, state) > 0);
		const pool = captures.length && random() < .4 ? captures : actions;
		nodes = 1;
		completedDepth = 1;
		return result(pool[Math.min(pool.length - 1, Math.floor(random() * pool.length))]);
	}
	const ordered = [...actions].sort((a, b) => captureValue(b, state) - captureValue(a, state));
	const positions = [];
	for (const action of ordered) {
		const next = applySanguoAction(state, action);
		if (!next) continue;
		const resolved = next.pending ? resolveSanguoAppropriation(next) : next;
		nodes++;
		positions.push({
			action,
			state: resolved,
			score: evaluateSanguo(resolved)[state.turn]
		});
	}
	positions.sort((a, b) => b.score - a.score);
	if (!positions.length) return result(actions[0]);
	let best = positions[0].action;
	completedDepth = 1;
	if (difficulty === "medium") return result(best);
	const TIMEOUT = Symbol("search deadline");
	const search = (position, depth) => {
		if (performance.now() > deadline) throw TIMEOUT;
		nodes++;
		if (!depth || position.winner || position.draw) return evaluateSanguo(position);
		const danger = new Set(position.pieces.filter((p) => !p.captured && p.controller !== position.turn).flatMap((p) => pseudoSanguoTargets(p, position.pieces).map(nodeId)));
		const priority = (action) => {
			if (action.type === "resolve") return 1e5;
			const piece = position.pieces.find((p) => p.id === action.pieceId);
			return captureValue(action, position) * 2 - (danger.has(nodeId(action.to)) ? VALUE[piece.role] : 0) + (action.to.sector === piece.sector ? 4 - action.to.rank : 5 + action.to.rank);
		};
		const candidates = sanguoActions(position).sort((a, b) => priority(b) - priority(a)).slice(0, level.width).map((action) => {
			if (performance.now() > deadline) throw TIMEOUT;
			const next = applySanguoAction(position, action);
			const child = next.pending ? resolveSanguoAppropriation(next) : next;
			return {
				child,
				score: evaluateSanguo(child)[position.turn]
			};
		}).sort((a, b) => b.score - a.score).slice(0, level.width);
		let utility = null;
		for (const { child } of candidates) {
			const score = search(child, depth - 1);
			if (!utility || score[position.turn] > utility[position.turn]) utility = score;
		}
		return utility ?? evaluateSanguo(position);
	};
	for (let depth = 2; depth <= level.depth; depth++) try {
		let iterationBest = best, bestScore = -Infinity;
		for (const candidate of positions.slice(0, level.width)) {
			const score = search(candidate.state, depth - 1)[state.turn];
			if (score > bestScore) {
				bestScore = score;
				iterationBest = candidate.action;
			}
		}
		best = iterationBest;
		completedDepth = depth;
	} catch (error) {
		if (error !== TIMEOUT) throw error;
		break;
	}
	return result(best);
}
//#endregion
exports.BOT_LEVELS = BOT_LEVELS;
exports.applySanguoAction = applySanguoAction;
exports.applySanguoMove = applySanguoMove;
exports.appropriateArmy = appropriateArmy;
exports.chooseSanguoBotAction = chooseSanguoBotAction;
exports.evaluateSanguo = evaluateSanguo;
exports.generalIsAttacked = generalIsAttacked;
exports.generalsFacing = generalsFacing;
exports.graphHasOnlyKnownNodes = graphHasOnlyKnownNodes;
exports.hasSanguoLegalMove = hasSanguoLegalMove;
exports.initialSanguoPieces = initialSanguoPieces;
exports.initialSanguoState = initialSanguoState;
exports.legalSanguoTargets = legalSanguoTargets;
exports.nextSanguoTurn = nextSanguoTurn;
exports.nodeId = nodeId;
exports.optionalBannermenCount = optionalBannermenCount;
exports.otherFactions = otherFactions;
exports.pseudoSanguoTargets = pseudoSanguoTargets;
exports.railNodeIds = railNodeIds;
exports.removeGeneralAndAppropriate = removeGeneralAndAppropriate;
exports.resignSanguoFaction = resignSanguoFaction;
exports.resolveSanguoAppropriation = resolveSanguoAppropriation;
exports.roleLabels = roleLabels;
exports.sameNode = sameNode;
exports.sanguoActions = sanguoActions;
exports.sanguoFactions = sanguoFactions;
exports.sanguoNodeIds = sanguoNodeIds;
exports.sanguoPositionKey = sanguoPositionKey;
exports.sanguoStateFrom = sanguoStateFrom;
exports.winnerFromDefeats = winnerFromDefeats;
