// Generated by frontend/scripts/build-sanguo-engine.mjs. Do not edit by hand.
Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
//#region src/games/heritage-arcade/ported/game/sanguoRailGraph.ts
const SOURCE_RAIL_EDGES = [
	["blue-0-0", "blue-0-1"],
	["blue-0-0", "blue-1-2"],
	["blue-0-4", "blue-0-5"],
	["blue-0-4", "blue-1-4"],
	["blue-0-5", "blue-1-4"],
	["blue-0-6", "blue-1-4"],
	["blue-1-0", "blue-1-1"],
	["blue-1-0", "blue-4-0"],
	["blue-0-4", "green-0-4"],
	["blue-1-1", "blue-1-2"],
	["blue-1-1", "blue-2-1"],
	["blue-1-2", "blue-1-3"],
	["blue-1-2", "blue-4-2"],
	["blue-1-3", "blue-1-4"],
	["blue-1-3", "blue-3-3"],
	["blue-1-4", "blue-1-5"],
	["blue-1-4", "blue-2-4"],
	["blue-1-6", "blue-4-6"],
	["blue-1-7", "blue-1-8"],
	["blue-1-7", "blue-2-7"],
	["blue-1-8", "blue-4-8"],
	["blue-0-4", "red-0-4"],
	["blue-2-0", "blue-4-1"],
	["blue-2-1", "blue-4-1"],
	["blue-2-3", "blue-3-4"],
	["blue-2-4", "blue-3-4"],
	["blue-2-5", "blue-2-7"],
	["blue-2-5", "blue-3-8"],
	["blue-3-0", "blue-3-1"],
	["blue-3-0", "blue-4-2"],
	["blue-3-1", "blue-3-2"],
	["blue-3-2", "blue-3-3"],
	["blue-3-4", "blue-3-5"],
	["blue-3-4", "blue-4-3"],
	["blue-3-4", "blue-4-4"],
	["blue-3-4", "blue-4-5"],
	["blue-3-5", "blue-4-2"],
	["blue-3-8", "blue-4-7"],
	["blue-4-0", "blue-4-1"],
	["blue-4-1", "blue-4-2"],
	["blue-4-2", "blue-4-3"],
	["blue-4-3", "blue-4-4"],
	["blue-4-4", "blue-4-5"],
	["blue-4-5", "blue-4-6"],
	["blue-4-6", "blue-4-7"],
	["blue-4-7", "blue-4-8"],
	["green-0-0", "green-0-1"],
	["green-0-0", "green-1-2"],
	["green-0-1", "green-1-2"],
	["green-0-4", "green-0-5"],
	["green-0-4", "green-1-4"],
	["green-0-5", "green-1-4"],
	["green-0-6", "green-1-4"],
	["green-1-0", "green-1-1"],
	["green-1-0", "green-4-0"],
	["green-1-1", "green-1-2"],
	["green-1-1", "green-2-1"],
	["green-1-2", "green-1-3"],
	["green-1-2", "green-4-2"],
	["green-1-3", "green-1-4"],
	["green-1-3", "green-3-3"],
	["green-1-4", "green-1-5"],
	["green-1-4", "green-2-4"],
	["green-1-6", "green-4-6"],
	["green-1-7", "green-1-8"],
	["green-1-7", "green-2-7"],
	["green-1-8", "green-4-8"],
	["green-0-4", "red-0-4"],
	["green-2-0", "green-4-1"],
	["green-2-1", "green-4-1"],
	["green-2-3", "green-3-4"],
	["green-2-4", "green-3-4"],
	["green-2-5", "green-2-7"],
	["green-3-0", "green-3-1"],
	["green-3-0", "green-4-2"],
	["green-3-1", "green-3-2"],
	["green-3-2", "green-3-3"],
	["green-3-4", "green-3-5"],
	["green-3-4", "green-4-3"],
	["green-3-4", "green-4-4"],
	["green-3-4", "green-4-5"],
	["green-3-8", "green-4-7"],
	["green-4-0", "green-4-1"],
	["green-4-1", "green-4-2"],
	["green-4-2", "green-4-3"],
	["green-4-3", "green-4-4"],
	["green-4-4", "green-4-5"],
	["green-4-5", "green-4-6"],
	["green-4-6", "green-4-7"],
	["green-4-7", "green-4-8"],
	["red-0-0", "red-1-3"],
	["red-0-3", "red-1-4"],
	["red-0-4", "red-1-4"],
	["red-0-5", "red-1-4"],
	["red-0-8", "red-1-5"],
	["red-1-0", "red-1-1"],
	["red-1-1", "red-1-2"],
	["red-1-1", "red-2-1"],
	["red-1-2", "red-1-3"],
	["red-1-2", "red-2-2"],
	["red-1-3", "red-1-4"],
	["red-1-3", "red-2-3"],
	["red-1-4", "red-1-5"],
	["red-1-4", "red-2-4"],
	["red-1-5", "red-1-6"],
	["red-1-5", "red-2-5"],
	["red-1-6", "red-1-7"],
	["red-1-6", "red-2-6"],
	["red-1-7", "red-1-8"],
	["red-1-7", "red-2-7"],
	["red-1-8", "red-4-8"],
	["red-2-0", "red-2-1"],
	["red-2-1", "red-4-1"],
	["red-2-2", "red-3-3"],
	["red-2-3", "red-4-3"],
	["red-2-4", "red-3-6"],
	["red-2-5", "red-4-5"],
	["red-2-6", "red-4-6"],
	["red-2-7", "red-2-8"],
	["red-2-7", "red-4-7"],
	["red-3-0", "red-3-1"],
	["red-3-1", "red-3-2"],
	["red-3-2", "red-3-3"],
	["red-3-6", "red-4-4"],
	["red-4-0", "red-4-1"],
	["red-4-1", "red-4-2"],
	["red-4-2", "red-4-3"],
	["red-4-3", "red-4-4"],
	["red-4-4", "red-4-5"],
	["red-4-5", "red-4-6"],
	["red-4-6", "red-4-7"],
	["red-4-7", "red-4-8"]
];
const SOURCE_RAIL_ADJACENCY = /* @__PURE__ */ new Map();
for (const [from, to] of SOURCE_RAIL_EDGES) {
	SOURCE_RAIL_ADJACENCY.set(from, [...SOURCE_RAIL_ADJACENCY.get(from) ?? [], to]);
	SOURCE_RAIL_ADJACENCY.set(to, [...SOURCE_RAIL_ADJACENCY.get(to) ?? [], from]);
}
const logicalNode = (sector, rank, file) => ({
	sector,
	rank,
	file
});
const logicalNodeKey = (node) => `${node.sector}-${node.rank}-${node.file}`;
/**
* Non-visual river continuation table confirmed from the labelled board.
* Human labels are L1..L9; code files are 0..8.
*
* R1-B9, R2-B8, R3-B7, R4-B6,
* R5-B5-G5,
* R6-G4, R7-G3, R8-G2, R9-G1,
* B1-G9, B2-G8, B3-G7, B4-G6.
*/
const FILE_CONTINUATIONS = {
	red: [
		[{
			sector: "blue",
			file: 8
		}],
		[{
			sector: "blue",
			file: 7
		}],
		[{
			sector: "blue",
			file: 6
		}],
		[{
			sector: "blue",
			file: 5
		}],
		[{
			sector: "blue",
			file: 4
		}, {
			sector: "green",
			file: 4
		}],
		[{
			sector: "green",
			file: 3
		}],
		[{
			sector: "green",
			file: 2
		}],
		[{
			sector: "green",
			file: 1
		}],
		[{
			sector: "green",
			file: 0
		}]
	],
	blue: [
		[{
			sector: "green",
			file: 8
		}],
		[{
			sector: "green",
			file: 7
		}],
		[{
			sector: "green",
			file: 6
		}],
		[{
			sector: "green",
			file: 5
		}],
		[{
			sector: "red",
			file: 4
		}, {
			sector: "green",
			file: 4
		}],
		[{
			sector: "red",
			file: 3
		}],
		[{
			sector: "red",
			file: 2
		}],
		[{
			sector: "red",
			file: 1
		}],
		[{
			sector: "red",
			file: 0
		}]
	],
	green: [
		[{
			sector: "red",
			file: 8
		}],
		[{
			sector: "red",
			file: 7
		}],
		[{
			sector: "red",
			file: 6
		}],
		[{
			sector: "red",
			file: 5
		}],
		[{
			sector: "red",
			file: 4
		}, {
			sector: "blue",
			file: 4
		}],
		[{
			sector: "blue",
			file: 3
		}],
		[{
			sector: "blue",
			file: 2
		}],
		[{
			sector: "blue",
			file: 1
		}],
		[{
			sector: "blue",
			file: 0
		}]
	]
};
/**
* The only genuinely three-way movement junction.
*
* Each kingdom's (rank 0, file 4) is its L5 river endpoint. Reaching that
* endpoint presents two straight continuations: the L5 endpoint of each other
* kingdom. A piece may choose one branch; a single move never turns from one
* foreign branch into the other after choosing it.
*/
const CENTRAL_VERTEX_EXITS = {
	red: ["blue", "green"],
	blue: ["red", "green"],
	green: ["red", "blue"]
};
const isCentralVertexEndpoint = (node) => node.rank === 0 && node.file === 4;
/** Direct one-step river exits from a rank-0 endpoint. */
function riverExits(node) {
	if (node.rank !== 0) return [];
	if (isCentralVertexEndpoint(node)) return CENTRAL_VERTEX_EXITS[node.sector].map((sector) => logicalNode(sector, 0, 4));
	return (FILE_CONTINUATIONS[node.sector][node.file] ?? []).map((continuation) => logicalNode(continuation.sector, 0, continuation.file));
}
/** Standard Xiangqi horizontal rays inside one logical 5x9 sector. */
function rankRays(node) {
	const { sector, rank, file } = node;
	return [Array.from({ length: file }, (_, offset) => logicalNode(sector, rank, file - offset - 1)), Array.from({ length: 9 - file - 1 }, (_, offset) => logicalNode(sector, rank, file + offset + 1))].filter((ray) => ray.length > 0);
}
/**
* Xiangqi vertical rays plus one Sanguo boundary operation.
*
* Inside a sector this is ordinary file movement. When the inward ray reaches
* rank 0, it may continue through exactly one river exit. The chosen foreign
* file then continues from rank 0 toward rank 4 as an ordinary Xiangqi file.
* L5 simply produces two candidate rays because its river endpoint is the
* explicit three-way junction defined above.
*/
function fileRays(node) {
	const { sector, rank, file } = node;
	const outward = Array.from({ length: 4 - rank }, (_, offset) => logicalNode(sector, rank + offset + 1, file));
	const toRiver = Array.from({ length: rank }, (_, offset) => logicalNode(sector, rank - offset - 1, file));
	const exits = riverExits(logicalNode(sector, 0, file));
	return [outward, ...exits.length ? exits.map((exit) => [...toRiver, ...Array.from({ length: 5 }, (_, foreignRank) => logicalNode(exit.sector, foreignRank, exit.file))]) : [toRiver]].filter((ray) => ray.length > 0);
}
//#endregion
//#region src/games/heritage-arcade/ported/game/sanguoHorseMoves.ts
const sameNode$7 = (left, right) => left.sector === right.sector && left.rank === right.rank && left.file === right.file;
const occupant$9 = (pieces, node) => pieces.find((piece) => !piece.captured && sameNode$7(piece.node, node));
const unique$2 = (nodes) => [...new Map(nodes.map((node) => [`${node.sector}-${node.rank}-${node.file}`, node])).values()];
const landable$2 = (piece, pieces, node) => {
	const hit = occupant$9(pieces, node);
	return !hit || hit.controller !== piece.controller;
};
const insideFile$2 = (file) => file >= 0 && file <= 8;
const insideRank = (rank) => rank >= 0 && rank <= 4;
const HORSE_DELTAS = [
	[-2, -1],
	[-2, 1],
	[-1, -2],
	[-1, 2],
	[1, -2],
	[1, 2],
	[2, -1],
	[2, 1]
];
/** Standard same-sector Xiangqi Horse geometry on the logical 5x9 grid. */
function appendLocalHorseTargets(piece, pieces, output) {
	const { sector, rank, file } = piece.node;
	for (const [rankDelta, fileDelta] of HORSE_DELTAS) {
		const destinationRank = rank + rankDelta;
		const destinationFile = file + fileDelta;
		if (!insideRank(destinationRank) || !insideFile$2(destinationFile)) continue;
		if (occupant$9(pieces, Math.abs(rankDelta) === 2 ? {
			sector,
			rank: rank + Math.sign(rankDelta),
			file
		} : {
			sector,
			rank,
			file: file + Math.sign(fileDelta)
		})) continue;
		const destination = logicalNode(sector, destinationRank, destinationFile);
		if (landable$2(piece, pieces, destination)) output.push(destination);
	}
}
/**
* Xiangqi Horse movement with only the river boundary adapted for Sanguo.
* Local moves are the ordinary eight (±2,±1)/(±1,±2) possibilities. If an L
* reaches across rank 0, the final geometry uses the explicit river exit of the
* logical board; L5 may therefore choose either branch of the central junction.
*/
function sanguoHorseTargets(piece, pieces) {
	if (piece.captured) return [];
	const output = [];
	appendLocalHorseTargets(piece, pieces, output);
	for (const ray of fileRays(piece.node)) {
		if (ray.length < 2) continue;
		const leg = ray[0];
		const second = ray[1];
		if (occupant$9(pieces, leg)) continue;
		if (second.sector === piece.node.sector) continue;
		for (const side of [-1, 1]) {
			const destinationFile = second.file + side;
			if (!insideFile$2(destinationFile)) continue;
			const destination = logicalNode(second.sector, second.rank, destinationFile);
			if (landable$2(piece, pieces, destination)) output.push(destination);
		}
	}
	for (const ray of rankRays(piece.node)) {
		if (ray.length < 2) continue;
		const leg = ray[0];
		const second = ray[1];
		if (occupant$9(pieces, leg)) continue;
		for (const perpendicular of fileRays(second)) {
			const destination = perpendicular[0];
			if (!destination || destination.sector === piece.node.sector) continue;
			if (landable$2(piece, pieces, destination)) output.push(destination);
		}
	}
	return unique$2(output);
}
//#endregion
//#region src/games/heritage-arcade/ported/game/sanguoElephantMoves.ts
const sameNode$6 = (left, right) => left.sector === right.sector && left.rank === right.rank && left.file === right.file;
const occupant$8 = (pieces, node) => pieces.find((piece) => !piece.captured && sameNode$6(piece.node, node));
const insideHalfBoard = (rank, file) => rank >= 0 && rank <= 4 && file >= 0 && file <= 8;
const ELEPHANT_DELTAS = [
	[-2, -2],
	[-2, 2],
	[2, -2],
	[2, 2]
];
/**
* Exact Xiangqi Elephant movement on a Sanguo kingdom half-board.
*
* The Elephant moves exactly two points diagonally in one move. It cannot jump:
* the diagonal midpoint (the elephant eye) must be empty. As in Xiangqi, an
* Elephant may not cross the river, so every destination remains in the
* Elephant's current Sanguo sector. A friendly destination is forbidden; an
* enemy destination may be captured.
*/
function sanguoElephantTargets(piece, pieces) {
	if (piece.captured) return [];
	const output = [];
	const { sector, rank, file } = piece.node;
	for (const [rankDelta, fileDelta] of ELEPHANT_DELTAS) {
		const destinationRank = rank + rankDelta;
		const destinationFile = file + fileDelta;
		if (!insideHalfBoard(destinationRank, destinationFile)) continue;
		if (occupant$8(pieces, {
			sector,
			rank: rank + rankDelta / 2,
			file: file + fileDelta / 2
		})) continue;
		const destination = {
			sector,
			rank: destinationRank,
			file: destinationFile
		};
		const hit = occupant$8(pieces, destination);
		if (!hit || hit.controller !== piece.controller) output.push(destination);
	}
	return output;
}
//#endregion
//#region src/games/heritage-arcade/ported/game/sanguoAdvisorMoves.ts
const key$1 = (node) => `${node.sector}-${node.rank}-${node.file}`;
const sameNode$5 = (left, right) => left.sector === right.sector && left.rank === right.rank && left.file === right.file;
const occupant$7 = (pieces, node) => pieces.find((piece) => !piece.captured && sameNode$5(piece.node, node));
const PALACE_CORNERS = [
	{
		rank: 2,
		file: 3
	},
	{
		rank: 2,
		file: 5
	},
	{
		rank: 4,
		file: 3
	},
	{
		rank: 4,
		file: 5
	}
];
const PALACE_CENTER = {
	rank: 3,
	file: 4
};
/**
* Exact Xiangqi Advisor rule for one Sanguo kingdom palace.
*
* The Advisor moves exactly one diagonal palace step and may never leave its
* original kingdom's 3x3 palace. The palace has the normal Xiangqi X: the four
* corners connect only to the centre, and the centre connects to all four
* corners. Mid-edge palace points are not Advisor destinations because no
* diagonal palace rail reaches them.
*
* Appropriation changes controller, not the piece's original sector, so an
* appropriated Advisor remains confined to the palace printed in its own
* sector. It may capture an enemy-controlled coin on a legal destination but
* may not land on a friendly-controlled coin.
*/
function sanguoAdvisorTargets(piece, pieces) {
	if (piece.captured || piece.node.sector !== piece.sector) return [];
	const { sector, rank, file } = piece.node;
	const isCenter = rank === PALACE_CENTER.rank && file === PALACE_CENTER.file;
	const isCorner = PALACE_CORNERS.some((corner) => corner.rank === rank && corner.file === file);
	let candidates = [];
	if (isCenter) candidates = PALACE_CORNERS.map((corner) => ({
		sector,
		rank: corner.rank,
		file: corner.file
	}));
	else if (isCorner) candidates = [{
		sector,
		rank: PALACE_CENTER.rank,
		file: PALACE_CENTER.file
	}];
	else return [];
	return [...new Map(candidates.map((node) => [key$1(node), node])).values()].filter((node) => {
		const hit = occupant$7(pieces, node);
		return !hit || hit.controller !== piece.controller;
	});
}
//#endregion
//#region src/games/heritage-arcade/ported/game/sanguoGeneralMoves.ts
const sameNode$4 = (left, right) => left.sector === right.sector && left.rank === right.rank && left.file === right.file;
const occupant$6 = (pieces, node) => pieces.find((piece) => !piece.captured && sameNode$4(piece.node, node));
const insidePalace = (piece, node) => node.sector === piece.sector && node.rank >= 2 && node.rank <= 4 && node.file >= 3 && node.file <= 5;
const ORTHOGONAL_STEPS = [
	[-1, 0],
	[1, 0],
	[0, -1],
	[0, 1]
];
/**
* Exact Xiangqi General rule for a Sanguo kingdom palace.
*
* The General moves exactly one point orthogonally and may never leave its
* original 3x3 palace. It never moves diagonally and never uses any of the
* cross-kingdom continuation lines.
*
* Friendly pieces block the destination. Enemy pieces may be captured there.
* Check, flying-General exposure, and moving into attack are enforced by the
* higher-level legal-move filter in sanguoRules.ts, so this function returns
* only the General's geometric pseudo-legal destinations.
*/
function sanguoGeneralTargets(piece, pieces) {
	if (piece.captured) return [];
	if (!insidePalace(piece, piece.node)) return [];
	return ORTHOGONAL_STEPS.map(([rankDelta, fileDelta]) => ({
		sector: piece.sector,
		rank: piece.node.rank + rankDelta,
		file: piece.node.file + fileDelta
	})).filter((node) => insidePalace(piece, node)).filter((node) => {
		const hit = occupant$6(pieces, node);
		return !hit || hit.controller !== piece.controller;
	});
}
//#endregion
//#region src/games/heritage-arcade/ported/game/sanguoSoldierMoves.ts
const sameNode$3 = (left, right) => left.sector === right.sector && left.rank === right.rank && left.file === right.file;
const occupant$5 = (pieces, node) => pieces.find((piece) => !piece.captured && sameNode$3(piece.node, node));
const insideFile$1 = (file) => file >= 0 && file <= 8;
const landable$1 = (piece, pieces, node) => {
	const hit = occupant$5(pieces, node);
	return !hit || hit.controller !== piece.controller;
};
/**
* Standard Xiangqi Soldier rule on a logical Sanguo sector.
*
* Home sector:
*   - exactly one point forward (rank - 1)
*   - at rank 0, forward means cross through the explicit river exit
*
* Foreign sector (river already crossed):
*   - one point forward deeper into that sector (rank + 1)
*   - or one point sideways (file ± 1)
*   - never backward
*
* The only Sanguo-specific case is rank-0 crossing. On L5, riverExits()
* explicitly returns both branches of the central three-way junction.
*/
function sanguoSoldierTargets(piece, pieces) {
	if (piece.captured) return [];
	const { sector: currentSector, rank, file } = piece.node;
	const crossedRiver = currentSector !== piece.sector;
	const candidates = [];
	if (!crossedRiver) if (rank > 0) candidates.push(logicalNode(currentSector, rank - 1, file));
	else candidates.push(...riverExits(piece.node));
	else {
		if (rank < 4) candidates.push(logicalNode(currentSector, rank + 1, file));
		if (insideFile$1(file - 1)) candidates.push(logicalNode(currentSector, rank, file - 1));
		if (insideFile$1(file + 1)) candidates.push(logicalNode(currentSector, rank, file + 1));
	}
	return candidates.filter((node) => landable$1(piece, pieces, node));
}
//#endregion
//#region src/games/heritage-arcade/ported/game/sanguoBannermanMoves.ts
const sameNode$2 = (left, right) => left.sector === right.sector && left.rank === right.rank && left.file === right.file;
const occupant$4 = (pieces, node) => pieces.find((piece) => !piece.captured && sameNode$2(piece.node, node));
const unique$1 = (nodes) => [...new Map(nodes.map((node) => [`${node.sector}-${node.rank}-${node.file}`, node])).values()];
const landable = (piece, pieces, node) => {
	const hit = occupant$4(pieces, node);
	return !hit || hit.controller !== piece.controller;
};
const insideFile = (file) => file >= 0 && file <= 8;
/**
* Optional Sanguo Bannerman rule on logical coordinates.
* Two clear orthogonal transit points, then one outward diagonal finish.
* The only non-Xiangqi geometry is a river-boundary continuation supplied by
* sanguoLogicalTopology; no pixel/rail tracing participates in the rule.
*/
function sanguoBannermanTargets(piece, pieces) {
	if (piece.captured) return [];
	const output = [];
	for (const ray of fileRays(piece.node)) {
		if (ray.length < 3) continue;
		const first = ray[0];
		const second = ray[1];
		const longEndpoint = ray[2];
		if (occupant$4(pieces, first) || occupant$4(pieces, second)) continue;
		for (const side of [-1, 1]) {
			const destinationFile = longEndpoint.file + side;
			if (!insideFile(destinationFile)) continue;
			const destination = logicalNode(longEndpoint.sector, longEndpoint.rank, destinationFile);
			if (landable(piece, pieces, destination)) output.push(destination);
		}
	}
	for (const ray of rankRays(piece.node)) {
		if (ray.length < 3) continue;
		const first = ray[0];
		const second = ray[1];
		const longEndpoint = ray[2];
		if (occupant$4(pieces, first) || occupant$4(pieces, second)) continue;
		for (const perpendicular of fileRays(longEndpoint)) {
			const destination = perpendicular[0];
			if (destination && landable(piece, pieces, destination)) output.push(destination);
		}
	}
	return unique$1(output);
}
//#endregion
//#region src/games/heritage-arcade/ported/game/sanguoGraphMoves.ts
const key = (node) => `${node.sector}-${node.rank}-${node.file}`;
const same = (left, right) => key(left) === key(right);
const occupant$3 = (pieces, node) => pieces.find((piece) => !piece.captured && same(piece.node, node));
const unique = (nodes) => [...new Map(nodes.map((node) => [key(node), node])).values()];
function appendChariotRay(piece, pieces, ray, output) {
	for (const node of ray) {
		const hit = occupant$3(pieces, node);
		if (!hit) {
			output.push(node);
			continue;
		}
		if (hit.controller !== piece.controller) output.push(node);
		break;
	}
}
/** Xiangqi Chariot rays on logical coordinates, extended only at a Sanguo river boundary. */
function chariotTargets(piece, pieces) {
	const output = [];
	for (const ray of [...rankRays(piece.node), ...fileRays(piece.node)]) appendChariotRay(piece, pieces, ray, output);
	return unique(output);
}
function appendCannonRay(piece, pieces, ray, output) {
	let screened = false;
	for (const node of ray) {
		const hit = occupant$3(pieces, node);
		if (!screened) {
			if (!hit) {
				output.push(node);
				continue;
			}
			screened = true;
			continue;
		}
		if (!hit) continue;
		if (hit.controller !== piece.controller) output.push(node);
		break;
	}
}
/** Xiangqi Cannon rule on the same logical straight rays as the Chariot. */
function cannonTargets(piece, pieces) {
	const output = [];
	for (const ray of [...rankRays(piece.node), ...fileRays(piece.node)]) appendCannonRay(piece, pieces, ray, output);
	return unique(output);
}
/** Authoritative pseudo-legal resolver. */
function logicalPseudoTargets(piece, pieces) {
	if (piece.captured) return [];
	if (piece.role === "icebreaker") return chariotTargets(piece, pieces);
	if (piece.role === "cannon") return cannonTargets(piece, pieces);
	if (piece.role === "king") return sanguoGeneralTargets(piece, pieces);
	if (piece.role === "guard") return sanguoAdvisorTargets(piece, pieces);
	if (piece.role === "seer") return sanguoElephantTargets(piece, pieces);
	if (piece.role === "rider") return sanguoHorseTargets(piece, pieces);
	if (piece.role === "runner") return sanguoBannermanTargets(piece, pieces);
	return sanguoSoldierTargets(piece, pieces);
}
//#endregion
//#region src/games/heritage-arcade/ported/game/sanguoSpecialRules.ts
const sameNode$1 = (left, right) => left.sector === right.sector && left.rank === right.rank && left.file === right.file;
const occupant$2 = (pieces, node) => pieces.find((piece) => !piece.captured && sameNode$1(piece.node, node));
/**
* Xiangqi flying-General prohibition on logical straight files.
*
* Within a sector this is the ordinary Xiangqi file test. If the sightline
* reaches rank 0, the Sanguo river layer may continue it into one foreign file.
* At L5 there are exactly two separately-tested branches from the explicit
* central three-way junction. Any intervening coin blocks that branch.
*/
function generalsFacingOnLogicalFiles(pieces) {
	const generals = pieces.filter((piece) => !piece.captured && piece.role === "king");
	for (const general of generals) for (const ray of fileRays(general.node)) for (const node of ray) {
		const hit = occupant$2(pieces, node);
		if (!hit) continue;
		if (hit.role === "king" && hit.id !== general.id) return true;
		break;
	}
	return false;
}
//#endregion
//#region src/games/heritage-arcade/ported/game/sanguoRules.ts
const sanguoFactions = [
	"red",
	"green",
	"blue"
];
const roleLabels = {
	king: "General",
	guard: "Advisor",
	seer: "Elephant",
	rider: "Horse",
	runner: "Bannerman",
	icebreaker: "Chariot",
	cannon: "Cannon",
	scout: "Soldier"
};
const nodeId = (node) => logicalNodeKey(node);
const sameNode = (left, right) => nodeId(left) === nodeId(right);
const sanguoNodeIds = () => sanguoFactions.flatMap((sector) => Array.from({ length: 45 }, (_, index) => logicalNodeKey({
	sector,
	rank: Math.floor(index / 9),
	file: index % 9
})));
const railNodeIds = new Set(sanguoNodeIds());
/** Renderer/audit-only validation. Movement legality does not use SOURCE_RAIL_EDGES. */
const graphHasOnlyKnownNodes = () => SOURCE_RAIL_EDGES.every(([from, to]) => railNodeIds.has(from) && railNodeIds.has(to));
const optionalBannermenCount = (enabled) => enabled ? 54 : 48;
const otherFactions = (faction) => sanguoFactions.filter((candidate) => candidate !== faction);
const occupant$1 = (pieces, node) => pieces.find((piece) => !piece.captured && sameNode(piece.node, node));
/** Public pseudo-target resolver: logical Xiangqi geometry + explicit Sanguo boundary rules. */
const pseudoSanguoTargets = (piece, pieces) => logicalPseudoTargets(piece, pieces);
/** Xiangqi flying-General rule on logical files, including explicit L5 branching. */
function generalsFacing(pieces) {
	return generalsFacingOnLogicalFiles(pieces);
}
function generalIsAttacked(controller, pieces) {
	const general = pieces.find((piece) => !piece.captured && piece.sector === controller && piece.role === "king");
	return Boolean(general && pieces.some((piece) => !piece.captured && piece.controller !== controller && pseudoSanguoTargets(piece, pieces).some((target) => sameNode(target, general.node))));
}
const checkingPiecesAgainst = (defeated, victor, pieces) => {
	const general = pieces.find((piece) => !piece.captured && piece.sector === defeated && piece.role === "king");
	if (!general) return [];
	return pieces.filter((piece) => !piece.captured && piece.controller === victor && pseudoSanguoTargets(piece, pieces).some((target) => sameNode(target, general.node)));
};
const relocate = (pieces, piece, destination) => {
	const victim = occupant$1(pieces, destination);
	return pieces.map((candidate) => candidate.id === piece.id ? {
		...candidate,
		node: destination
	} : victim && candidate.id === victim.id ? {
		...candidate,
		captured: true
	} : candidate);
};
/**
* A legal move may not capture a General directly. Instead it must leave the
* opposing General with no legal reply; Sanguo then resolves that army in the
* documented separate appropriation turn.
*/
const legalSanguoTargets = (piece, pieces) => pseudoSanguoTargets(piece, pieces).filter((target) => {
	if (occupant$1(pieces, target)?.role === "king") return false;
	const next = relocate(pieces, piece, target);
	return !generalsFacing(next) && !generalIsAttacked(piece.controller, next);
});
const hasSanguoLegalMove = (controller, pieces) => pieces.some((piece) => !piece.captured && piece.controller === controller && legalSanguoTargets(piece, pieces).length > 0);
function initialSanguoPieces(includeBannermen = false) {
	const pieces = [];
	sanguoFactions.forEach((sector) => {
		const add = (role, rank, file, index) => pieces.push({
			id: `${sector}-${role}-${index}`,
			sector,
			controller: sector,
			role,
			node: {
				sector,
				rank,
				file
			}
		});
		[
			"icebreaker",
			"rider",
			"seer",
			"guard",
			"king",
			"guard",
			"seer",
			"rider",
			"icebreaker"
		].forEach((role, file) => add(role, 4, file, file));
		add("cannon", 2, 1, 0);
		add("cannon", 2, 7, 1);
		[
			0,
			2,
			4,
			6,
			8
		].forEach((file, index) => add("scout", 1, file, index));
		if (includeBannermen) {
			add("runner", 2, 3, 0);
			add("runner", 2, 5, 1);
		}
	});
	return pieces;
}
const initialSanguoState = (includeBannermen = false) => ({
	pieces: initialSanguoPieces(includeBannermen),
	turn: "red",
	defeated: [],
	winner: null,
	pending: null,
	note: "Shu / Red opens. Turns then proceed counterclockwise: Red → Green → Blue.",
	moveNumber: 1,
	lastMove: null
});
/** Shu/Red first, then counterclockwise Red → Green → Blue, skipping eliminated kingdoms. */
function nextSanguoTurn(current, defeated) {
	for (let offset = 1; offset <= sanguoFactions.length; offset += 1) {
		const candidate = sanguoFactions[(sanguoFactions.indexOf(current) + offset) % sanguoFactions.length];
		if (!defeated.includes(candidate)) return candidate;
	}
	return current;
}
const winnerFromDefeats = (defeated) => {
	const survivors = sanguoFactions.filter((faction) => !defeated.includes(faction));
	return survivors.length === 1 ? survivors[0] : null;
};
const appropriateArmy = (pieces, defeated, victor) => pieces.map((piece) => piece.controller === defeated && !piece.captured && piece.role !== "king" ? {
	...piece,
	controller: victor
} : piece);
const removeGeneralAndAppropriate = (pieces, resolution) => pieces.map((piece) => piece.controller !== resolution.defeated ? piece : piece.role === "king" ? {
	...piece,
	captured: true
} : piece.captured ? piece : {
	...piece,
	controller: resolution.victor
});
function applySanguoMove(state, pieceId, destination) {
	if (state.winner || state.draw || state.pending) return null;
	const piece = state.pieces.find((candidate) => candidate.id === pieceId);
	if (!piece || piece.captured || piece.controller !== state.turn || !legalSanguoTargets(piece, state.pieces).some((target) => sameNode(target, destination))) return null;
	const victim = occupant$1(state.pieces, destination);
	const pieces = relocate(state.pieces, piece, destination);
	const nextTurn = nextSanguoTurn(state.turn, state.defeated);
	const lastMove = {
		pieceId,
		from: piece.node,
		to: destination,
		controller: state.turn,
		role: piece.role,
		captured: victim?.role
	};
	const action = `${roleLabels[piece.role]} ${victim ? `captures ${roleLabels[victim.role]}` : "advances"}`;
	const nextInCheck = generalIsAttacked(nextTurn, pieces);
	if (!hasSanguoLegalMove(nextTurn, pieces)) {
		const reason = nextInCheck ? "checkmate" : "stalemate";
		const checkers = reason === "checkmate" ? checkingPiecesAgainst(nextTurn, state.turn, pieces) : [];
		const matingPieceId = checkers.some((checker) => checker.id === piece.id) ? piece.id : checkers[0]?.id;
		return {
			...state,
			pieces,
			pending: {
				defeated: nextTurn,
				victor: state.turn,
				reason,
				matingPieceId
			},
			note: `${action}. ${nextTurn} has no legal reply: resolve ${reason} appropriation.`,
			moveNumber: state.moveNumber + 1,
			lastMove
		};
	}
	return trackSanguoPosition({
		...state,
		pieces,
		turn: nextTurn,
		note: nextInCheck ? `${action}. ${nextTurn} is in check and must answer it.` : `${action}. ${nextTurn} to move.`,
		moveNumber: state.moveNumber + 1,
		lastMove,
		positions: state.positions ?? [sanguoPositionKey(state)],
		quietMoves: victim || piece.role === "scout" ? 0 : (state.quietMoves ?? 0) + 1
	});
}
/** Arctic completion rules: three identical positions, or 120 quiet plies, draw. */
function sanguoPositionKey(state) {
	const roleCode = {
		king: "k",
		guard: "g",
		seer: "e",
		rider: "h",
		runner: "b",
		icebreaker: "r",
		cannon: "c",
		scout: "s"
	};
	return state.turn + ":" + state.pieces.filter((p) => !p.captured).map((p) => `${p.sector[0]}${p.controller[0]}${roleCode[p.role]}${p.node.sector[0]}${p.node.rank}${p.node.file}`).sort().join("");
}
function trackSanguoPosition(state) {
	const key = sanguoPositionKey(state);
	const positions = [...state.positions ?? [], key].slice(-121);
	const draw = positions.filter((p) => p === key).length >= 3 ? "repetition" : (state.quietMoves ?? 0) >= 120 ? "no-progress" : void 0;
	return {
		...state,
		positions,
		...draw ? {
			draw,
			note: draw === "repetition" ? "Draw: the same position occurred three times." : "Draw: 120 moves without a capture or Soldier move."
		} : {}
	};
}
const placeMatingPieceOnGeneral = (pieces, resolution) => {
	if (resolution.reason !== "checkmate" || !resolution.matingPieceId) return pieces;
	const general = pieces.find((piece) => !piece.captured && piece.sector === resolution.defeated && piece.role === "king");
	const matingPiece = pieces.find((piece) => !piece.captured && piece.id === resolution.matingPieceId && piece.controller === resolution.victor);
	if (!general || !matingPiece) return pieces;
	return pieces.map((piece) => piece.id === matingPiece.id ? {
		...piece,
		node: general.node
	} : piece);
};
function resolveSanguoAppropriation(state) {
	if (!state.pending) return null;
	const defeated = [...state.defeated, state.pending.defeated];
	const pieces = removeGeneralAndAppropriate(placeMatingPieceOnGeneral(state.pieces, state.pending), state.pending);
	const winner = winnerFromDefeats(defeated);
	if (winner) return {
		...state,
		pieces,
		defeated,
		winner,
		pending: null,
		note: `${winner} is the last surviving kingdom.`,
		lastMove: state.lastMove
	};
	const turn = nextSanguoTurn(state.turn, defeated);
	const next = {
		...state,
		pieces,
		defeated,
		turn,
		pending: null,
		note: `${state.pending.victor} appropriates the ${state.pending.defeated} army. ${turn} to move.`,
		lastMove: state.lastMove,
		positions: [],
		quietMoves: 0
	};
	if (!hasSanguoLegalMove(turn, pieces)) {
		const check = generalIsAttacked(turn, pieces);
		next.pending = {
			defeated: turn,
			victor: state.pending.victor,
			reason: check ? "checkmate" : "stalemate",
			matingPieceId: checkingPiecesAgainst(turn, state.pending.victor, pieces)[0]?.id
		};
		next.turn = state.pending.victor;
		next.note = `${turn} has no legal reply after appropriation. Resolve its army.`;
	}
	return next;
}
/** Resignation is an explicit Arctic completion: the resigning army leaves play. */
function resignSanguoFaction(state, faction) {
	if (state.winner || state.draw || state.defeated.includes(faction)) return null;
	if (state.pending) {
		const resolved = resolveSanguoAppropriation(state);
		return resolved.winner || resolved.defeated.includes(faction) ? resolved : resignSanguoFaction(resolved, faction);
	}
	const defeated = [...state.defeated, faction];
	const pieces = state.pieces.map((p) => p.controller === faction ? {
		...p,
		captured: true
	} : p);
	const turn = state.turn === faction ? nextSanguoTurn(faction, defeated) : state.turn;
	const winner = winnerFromDefeats(defeated);
	const next = {
		...state,
		pieces,
		defeated,
		turn,
		winner,
		positions: [],
		quietMoves: 0,
		note: winner ? `${winner} is the last surviving kingdom.` : `${faction} resigned. ${turn} to move.`
	};
	if (!winner && !hasSanguoLegalMove(turn, pieces)) {
		const victor = nextSanguoTurn(turn, defeated);
		next.pending = {
			defeated: turn,
			victor,
			reason: generalIsAttacked(turn, pieces) ? "checkmate" : "stalemate",
			matingPieceId: checkingPiecesAgainst(turn, victor, pieces)[0]?.id
		};
		next.turn = victor;
	}
	return next;
}
const sanguoStateFrom = (pieces, turn = "red", defeated = []) => ({
	pieces,
	turn,
	defeated,
	winner: null,
	pending: null,
	note: "Test state loaded.",
	moveNumber: 1,
	lastMove: null
});
//#endregion
//#region src/games/heritage-arcade/ported/game/sanguoBot.ts
const BOT_LEVELS = {
	easy: {
		label: "Easy",
		description: "Plays legal moves with a little capture preference.",
		search: "random",
		depth: 1,
		width: 6,
		qDepth: 0,
		qWidth: 0,
		budget: 150,
		tableSize: 0
	},
	medium: {
		label: "Medium",
		description: "Tactical three-player search with Xiangqi development, king safety and forcing-line analysis.",
		search: "paranoid",
		depth: 4,
		width: 20,
		qDepth: 2,
		qWidth: 14,
		budget: 1600,
		tableSize: 5e4
	},
	hard: {
		label: "Hard",
		description: "Deep iterative three-player search with transpositions, quiescence and aggressive reply analysis.",
		search: "paranoid",
		depth: 7,
		width: 34,
		qDepth: 4,
		qWidth: 24,
		budget: 6500,
		tableSize: 2e5
	}
};
const SANGUO_EVAL_WEIGHTS = {
	strongestRival: .55,
	secondRival: .18,
	mobility: 1.25,
	attackedPiece: .28,
	doubleAttackedPiece: .12,
	check: 900,
	sideToMoveInCheck: 320,
	checkPressure: 150,
	soldierProgress: 15,
	crossedSoldier: 95,
	majorPieceProgress: 5,
	centralFile: 20,
	riverControl: 8,
	enemySector: 18,
	eliminatedOpponent: 5200
};
const VALUE = {
	king: 3e4,
	icebreaker: 1e3,
	cannon: 460,
	rider: 440,
	runner: 430,
	guard: 210,
	seer: 210,
	scout: 125
};
const MOBILITY_FACTOR = {
	king: .18,
	guard: .28,
	seer: .3,
	rider: 1,
	runner: .75,
	icebreaker: .9,
	cannon: .95,
	scout: .5
};
const MATE_SCORE = 1e7;
const INF = 1e8;
const HOME_RANK = 4;
const CENTRAL_FILE = 4;
const nowMs = () => typeof performance !== "undefined" && performance.now ? performance.now() : Date.now();
const actionKey = (action) => !action ? "" : action.type === "resolve" ? "resolve" : `${action.pieceId}|${nodeId(action.to)}`;
const occupant = (state, node) => state.pieces.find((piece) => !piece.captured && nodeId(piece.node) === nodeId(node));
const pieceValue = (piece) => VALUE[piece.role] || 0;
const boardPieces = (state, controller) => state.pieces.filter((piece) => !piece.captured && (controller == null || piece.controller === controller));
function pieceProgress(piece) {
	return piece.node.sector === piece.sector ? HOME_RANK - piece.node.rank : 5 + piece.node.rank;
}
function terminalValue(state, faction) {
	if (state.draw) return 0;
	if (state.winner) return state.winner === faction ? MATE_SCORE : -1e7;
	if (state.defeated.includes(faction)) return -1e7;
	return null;
}
function buildThreatMaps(state) {
	const threats = {
		red: /* @__PURE__ */ new Map(),
		green: /* @__PURE__ */ new Map(),
		blue: /* @__PURE__ */ new Map()
	};
	for (const piece of boardPieces(state)) {
		const map = threats[piece.controller];
		for (const target of pseudoSanguoTargets(piece, state.pieces)) {
			const key = nodeId(target);
			map.set(key, (map.get(key) || 0) + 1);
		}
	}
	return threats;
}
function factionInCheckFromThreats(state, faction, threats) {
	const general = state.pieces.find((piece) => !piece.captured && piece.sector === faction && piece.role === "king");
	if (!general) return false;
	const square = nodeId(general.node);
	return sanguoFactions.some((enemy) => enemy !== faction && !state.defeated.includes(enemy) && (threats[enemy].get(square) || 0) > 0);
}
function rawFactionScore(state, faction, threats, checks, weights) {
	if (state.defeated.includes(faction)) return -1e7;
	let score = 0;
	for (const piece of boardPieces(state, faction)) {
		const value = pieceValue(piece);
		const targets = pseudoSanguoTargets(piece, state.pieces);
		const progress = pieceProgress(piece);
		score += value;
		score += targets.length * weights.mobility * MOBILITY_FACTOR[piece.role];
		if (piece.role === "scout") {
			score += progress * weights.soldierProgress;
			if (piece.node.sector !== piece.sector) score += weights.crossedSoldier;
		} else if ([
			"rider",
			"cannon",
			"icebreaker",
			"runner"
		].includes(piece.role)) score += progress * weights.majorPieceProgress;
		if ([
			"icebreaker",
			"cannon",
			"rider"
		].includes(piece.role) && piece.node.file === CENTRAL_FILE) score += weights.centralFile;
		if (piece.node.rank === 0) score += weights.riverControl;
		if (piece.node.sector !== piece.sector) score += weights.enemySector;
		const attackers = sanguoFactions.filter((enemy) => enemy !== faction && !state.defeated.includes(enemy)).reduce((sum, enemy) => sum + (threats[enemy].get(nodeId(piece.node)) || 0), 0);
		if (piece.role !== "king" && attackers > 0) {
			score -= value * weights.attackedPiece;
			if (attackers > 1) score -= value * weights.doubleAttackedPiece * (attackers - 1);
		}
	}
	if (checks[faction]) {
		score -= weights.check;
		if (state.turn === faction) score -= weights.sideToMoveInCheck;
	}
	for (const rival of sanguoFactions) if (rival !== faction && !state.defeated.includes(rival) && checks[rival]) score += weights.checkPressure;
	score += state.defeated.filter((rival) => rival !== faction).length * weights.eliminatedOpponent;
	return score;
}
/**
* Xiangqi-informed, controller-aware evaluation.
*
* Captured armies that were appropriated are naturally counted for their new
* controller because material, mobility and threats are all keyed by
* piece.controller rather than original sector.
*/
function evaluateSanguo(state, weights = SANGUO_EVAL_WEIGHTS) {
	const terminal = {
		red: terminalValue(state, "red"),
		green: terminalValue(state, "green"),
		blue: terminalValue(state, "blue")
	};
	if (state.draw || state.winner) return {
		red: terminal.red ?? 0,
		green: terminal.green ?? 0,
		blue: terminal.blue ?? 0
	};
	const threats = buildThreatMaps(state);
	const checks = Object.fromEntries(sanguoFactions.map((faction) => [faction, factionInCheckFromThreats(state, faction, threats)]));
	const raw = Object.fromEntries(sanguoFactions.map((faction) => [faction, terminal[faction] ?? rawFactionScore(state, faction, threats, checks, weights)]));
	const scores = { ...raw };
	for (const faction of sanguoFactions) {
		if (state.defeated.includes(faction)) {
			scores[faction] = -1e7;
			continue;
		}
		const rivals = sanguoFactions.filter((candidate) => candidate !== faction && !state.defeated.includes(candidate)).map((candidate) => raw[candidate]).sort((a, b) => b - a);
		if (rivals[0] != null) scores[faction] -= rivals[0] * weights.strongestRival;
		if (rivals[1] != null) scores[faction] -= rivals[1] * weights.secondRival;
	}
	return scores;
}
function sanguoActions(state) {
	if (state.winner || state.draw) return [];
	if (state.pending) return [{ type: "resolve" }];
	return state.pieces.filter((piece) => !piece.captured && piece.controller === state.turn).flatMap((piece) => legalSanguoTargets(piece, state.pieces).map((to) => ({
		type: "move",
		pieceId: piece.id,
		to
	})));
}
function applySanguoAction(state, action) {
	return action.type === "resolve" ? resolveSanguoAppropriation(state) : applySanguoMove(state, action.pieceId, action.to);
}
/** Collapse only the deterministic appropriation action while searching. */
function settleForcedResolution(state) {
	let current = state;
	let guard = 0;
	while (current.pending && !current.winner && !current.draw && guard < 3) {
		const next = resolveSanguoAppropriation(current);
		if (!next) break;
		current = next;
		guard += 1;
	}
	return current;
}
function searchChild(state, action) {
	const next = applySanguoAction(state, action);
	return next ? settleForcedResolution(next) : null;
}
function stateKey(state) {
	const pieces = state.pieces.map((piece) => [
		piece.id,
		piece.controller,
		piece.captured ? 1 : 0,
		nodeId(piece.node)
	]).sort((a, b) => String(a[0]).localeCompare(String(b[0])));
	const positions = state.positions || [];
	const repetitionContext = new Set(positions).size === positions.length ? [] : positions;
	return JSON.stringify([
		state.turn,
		[...state.defeated].sort(),
		state.winner || "",
		state.pending ? [
			state.pending.defeated,
			state.pending.victor,
			state.pending.reason,
			state.pending.matingPieceId || ""
		] : null,
		state.draw || "",
		state.quietMoves || 0,
		repetitionContext,
		pieces
	]);
}
function captureValue(action, state) {
	if (action.type === "resolve") return 1e5;
	const victim = occupant(state, action.to);
	return victim ? pieceValue(victim) : 0;
}
function crossesRiver(state, action) {
	if (action.type !== "move") return false;
	const piece = state.pieces.find((candidate) => candidate.id === action.pieceId);
	return Boolean(piece && piece.role === "scout" && piece.node.sector === piece.sector && action.to.sector !== piece.sector);
}
function fastMovePriority(state, action, context, ply, ttMoveKey = "") {
	const key = actionKey(action);
	let score = 0;
	if (key === ttMoveKey) score += 5e6;
	if (action.type === "resolve") return score + 2e7;
	const moving = state.pieces.find((piece) => piece.id === action.pieceId);
	const victim = occupant(state, action.to);
	if (victim) score += 1e6 + pieceValue(victim) * 90 - pieceValue(moving) * 7;
	if (crossesRiver(state, action)) score += 18e4;
	if (action.to.file === CENTRAL_FILE) score += 3500;
	if (action.to.rank === 0) score += 2200;
	if (context.killers.get(ply)?.includes(key)) score += 6e5;
	score += context.history.get(key) || 0;
	return score;
}
function preparedChildren(state, context, ply, limit, ttMoveKey = "") {
	const actions = sanguoActions(state);
	const prepared = [];
	for (const action of actions) {
		context.checkDeadline();
		const beforeDefeated = state.defeated.length;
		const victim = action.type === "move" ? occupant(state, action.to) : null;
		const crossed = crossesRiver(state, action);
		const child = searchChild(state, action);
		if (!child) continue;
		const checkCount = sanguoFactions.filter((faction) => faction !== state.turn && !child.defeated.includes(faction) && generalIsAttacked(faction, child.pieces)).length;
		const eliminated = child.defeated.length - beforeDefeated;
		const winning = child.winner === context.rootFaction;
		const forcing = Boolean(victim) || crossed || checkCount > 0 || eliminated > 0 || Boolean(child.winner) || generalIsAttacked(state.turn, state.pieces);
		let priority = fastMovePriority(state, action, context, ply, ttMoveKey);
		if (winning) priority += 3e7;
		if (eliminated) priority += 6e6 * eliminated;
		if (checkCount) priority += 26e4 * checkCount;
		prepared.push({
			action,
			child,
			priority,
			forcing,
			quiet: !victim && !crossed && !checkCount && !eliminated
		});
	}
	prepared.sort((a, b) => b.priority - a.priority || actionKey(a.action).localeCompare(actionKey(b.action)));
	if (!Number.isFinite(limit) || prepared.length <= limit) return prepared;
	const forcing = prepared.filter((entry) => entry.forcing);
	const quiet = prepared.filter((entry) => !entry.forcing);
	return [...forcing, ...quiet.slice(0, Math.max(0, limit - forcing.length))];
}
function recordCutoff(context, action, ply, depth, quiet) {
	if (!quiet) return;
	const key = actionKey(action);
	const killers = context.killers.get(ply) || [];
	if (!killers.includes(key)) {
		killers.unshift(key);
		if (killers.length > 2) killers.pop();
		context.killers.set(ply, killers);
	}
	context.history.set(key, Math.min(2e6, (context.history.get(key) || 0) + depth * depth * 500));
}
function transpositionLookup(context, key, depth, alpha, beta) {
	const entry = context.table.get(key);
	if (!entry || entry.depth < depth) return null;
	context.ttHits += 1;
	if (entry.flag === "exact") return {
		value: entry.value,
		moveKey: entry.moveKey,
		cutoff: true
	};
	if (entry.flag === "lower" && entry.value >= beta) return {
		value: entry.value,
		moveKey: entry.moveKey,
		cutoff: true
	};
	if (entry.flag === "upper" && entry.value <= alpha) return {
		value: entry.value,
		moveKey: entry.moveKey,
		cutoff: true
	};
	return {
		value: entry.value,
		moveKey: entry.moveKey,
		cutoff: false
	};
}
function transpositionStore(context, key, entry) {
	if (!context.level.tableSize) return;
	if (context.table.size >= context.level.tableSize) {
		const remove = Math.max(1, Math.floor(context.level.tableSize * .08));
		const iterator = context.table.keys();
		for (let index = 0; index < remove; index += 1) {
			const next = iterator.next();
			if (next.done) break;
			context.table.delete(next.value);
		}
	}
	context.table.set(key, entry);
}
function rootScore(state, context) {
	return evaluateSanguo(state, context.weights)[context.rootFaction];
}
function quiescence(state, alpha, beta, qDepth, context, ply) {
	context.checkDeadline();
	context.nodes += 1;
	context.qNodes += 1;
	const terminal = terminalValue(state, context.rootFaction);
	if (terminal != null && (state.winner || state.draw || state.defeated.includes(context.rootFaction))) return terminal;
	const maximizing = state.turn === context.rootFaction;
	const checked = generalIsAttacked(state.turn, state.pieces);
	const standPat = rootScore(state, context);
	if (qDepth <= 0 && !checked) return standPat;
	if (!checked) if (maximizing) {
		if (standPat >= beta) return standPat;
		alpha = Math.max(alpha, standPat);
	} else {
		if (standPat <= alpha) return standPat;
		beta = Math.min(beta, standPat);
	}
	let children = preparedChildren(state, context, ply, context.level.qWidth);
	if (!checked) children = children.filter((entry) => entry.forcing).slice(0, context.level.qWidth);
	if (!children.length) return standPat;
	let best = checked ? maximizing ? -1e8 : INF : standPat;
	for (const entry of children) {
		const score = quiescence(entry.child, alpha, beta, Math.max(0, qDepth - 1), context, ply + 1);
		if (maximizing) {
			if (score > best) best = score;
			alpha = Math.max(alpha, best);
		} else {
			if (score < best) best = score;
			beta = Math.min(beta, best);
		}
		if (alpha >= beta) {
			context.cutoffs += 1;
			break;
		}
	}
	return best;
}
/**
* Root-centric paranoid search.
*
* Red/Green/Blue still take turns exactly according to the authoritative rule
* engine. The search assumption is simply that every non-root faction chooses
* the reply that minimizes the root faction's score, which makes alpha-beta
* pruning available for this three-player game.
*/
function paranoidSearch(state, depth, alpha, beta, context, ply) {
	context.checkDeadline();
	context.nodes += 1;
	const terminal = terminalValue(state, context.rootFaction);
	if (terminal != null && (state.winner || state.draw || state.defeated.includes(context.rootFaction))) return terminal;
	if (depth <= 0) return quiescence(state, alpha, beta, context.level.qDepth, context, ply);
	const key = `${context.rootFaction}|${stateKey(state)}`;
	const originalAlpha = alpha;
	const originalBeta = beta;
	const tt = transpositionLookup(context, key, depth, alpha, beta);
	if (tt?.cutoff) return tt.value;
	const maximizing = state.turn === context.rootFaction;
	const children = preparedChildren(state, context, ply, context.level.width, tt?.moveKey || "");
	if (!children.length) return rootScore(state, context);
	let best = maximizing ? -1e8 : INF;
	let bestMoveKey = "";
	for (const entry of children) {
		const score = paranoidSearch(entry.child, depth - 1, alpha, beta, context, ply + 1);
		if (maximizing && score > best || !maximizing && score < best) {
			best = score;
			bestMoveKey = actionKey(entry.action);
		}
		if (maximizing) alpha = Math.max(alpha, best);
		else beta = Math.min(beta, best);
		if (alpha >= beta) {
			context.cutoffs += 1;
			recordCutoff(context, entry.action, ply, depth, entry.quiet);
			break;
		}
	}
	let flag = "exact";
	if (best <= originalAlpha) flag = "upper";
	else if (best >= originalBeta) flag = "lower";
	transpositionStore(context, key, {
		depth,
		value: best,
		flag,
		moveKey: bestMoveKey
	});
	return best;
}
function easyBotAction(state, options) {
	const started = nowMs();
	const actions = sanguoActions(state);
	if (!actions.length) return {
		action: null,
		stats: {
			nodes: 0,
			qNodes: 0,
			cutoffs: 0,
			ttHits: 0,
			completedDepth: 0,
			elapsedMs: Math.round(nowMs() - started),
			search: "capture-biased-random"
		}
	};
	if (state.pending) return {
		action: actions[0],
		stats: {
			nodes: 1,
			qNodes: 0,
			cutoffs: 0,
			ttHits: 0,
			completedDepth: 1,
			elapsedMs: Math.round(nowMs() - started),
			search: "forced-resolution"
		}
	};
	const random = options.random ?? Math.random;
	const captures = actions.filter((action) => captureValue(action, state) > 0);
	const pool = captures.length && random() < .4 ? captures : actions;
	return {
		action: pool[Math.min(pool.length - 1, Math.floor(random() * pool.length))] || pool[0],
		stats: {
			nodes: 1,
			qNodes: 0,
			cutoffs: 0,
			ttHits: 0,
			completedDepth: 1,
			elapsedMs: Math.round(nowMs() - started),
			search: "capture-biased-random"
		}
	};
}
function searchBotAction(state, difficulty, options) {
	const configured = BOT_LEVELS[difficulty];
	const level = {
		depth: options.maxDepth ?? configured.depth,
		width: options.width ?? configured.width,
		qDepth: options.qDepth ?? configured.qDepth,
		qWidth: options.qWidth ?? configured.qWidth,
		budget: options.budgetMs ?? configured.budget,
		tableSize: configured.tableSize
	};
	if (state.defeated.length === 1 && difficulty === "hard") {
		level.depth += 2;
		level.width = Math.max(level.width, 42);
		level.qWidth = Math.max(level.qWidth, 28);
	}
	const started = nowMs();
	const timeoutSignal = Symbol("sanguo-search-timeout");
	const deadline = started + level.budget;
	const context = {
		rootFaction: state.turn,
		level,
		weights: options.evalWeights ?? SANGUO_EVAL_WEIGHTS,
		deadline,
		timeoutSignal,
		table: /* @__PURE__ */ new Map(),
		killers: /* @__PURE__ */ new Map(),
		history: /* @__PURE__ */ new Map(),
		nodes: 0,
		qNodes: 0,
		cutoffs: 0,
		ttHits: 0,
		checkDeadline() {
			if (nowMs() >= deadline) throw timeoutSignal;
		}
	};
	const actions = sanguoActions(state);
	const result = (action, score, completedDepth) => ({
		action,
		score,
		stats: {
			nodes: context.nodes,
			qNodes: context.qNodes,
			cutoffs: context.cutoffs,
			ttHits: context.ttHits,
			completedDepth,
			elapsedMs: Math.round(nowMs() - started),
			tableSize: context.table.size,
			search: "iterative-paranoid-alpha-beta"
		}
	});
	if (!actions.length) return result(null, null, 0);
	if (state.pending) return result(actions[0], null, 1);
	let bestAction = [...actions].sort((a, b) => fastMovePriority(state, b, context, 0) - fastMovePriority(state, a, context, 0) || actionKey(a).localeCompare(actionKey(b)))[0] || actions[0];
	let bestScore = -1e8;
	let completedDepth = 0;
	let principalKey = actionKey(bestAction);
	try {
		const initial = preparedChildren(state, context, 0, Number.POSITIVE_INFINITY);
		if (initial.length) {
			bestAction = initial[0].action;
			bestScore = rootScore(initial[0].child, context);
			completedDepth = 1;
			principalKey = actionKey(bestAction);
		}
		for (let depth = 2; depth <= level.depth; depth += 1) {
			context.checkDeadline();
			const rootChildren = preparedChildren(state, context, 0, level.width, principalKey);
			let iterationAction = bestAction;
			let iterationScore = -1e8;
			let alpha = -1e8;
			for (const entry of rootChildren) {
				context.checkDeadline();
				const score = paranoidSearch(entry.child, depth - 1, alpha, INF, context, 1);
				if (score > iterationScore || score === iterationScore && actionKey(entry.action).localeCompare(actionKey(iterationAction)) < 0) {
					iterationScore = score;
					iterationAction = entry.action;
				}
				alpha = Math.max(alpha, iterationScore);
			}
			bestAction = iterationAction;
			bestScore = iterationScore;
			principalKey = actionKey(bestAction);
			completedDepth = depth;
		}
	} catch (error) {
		if (error !== timeoutSignal) throw error;
	}
	return result(bestAction, bestScore, completedDepth);
}
function chooseSanguoBotAction(state, difficulty = "medium", options = {}) {
	if (difficulty === "easy") return easyBotAction(state, options);
	return searchBotAction(state, difficulty, options);
}
//#endregion
exports.BOT_LEVELS = BOT_LEVELS;
exports.SANGUO_EVAL_WEIGHTS = SANGUO_EVAL_WEIGHTS;
exports.applySanguoAction = applySanguoAction;
exports.applySanguoMove = applySanguoMove;
exports.appropriateArmy = appropriateArmy;
exports.chooseSanguoBotAction = chooseSanguoBotAction;
exports.evaluateSanguo = evaluateSanguo;
exports.generalIsAttacked = generalIsAttacked;
exports.generalsFacing = generalsFacing;
exports.graphHasOnlyKnownNodes = graphHasOnlyKnownNodes;
exports.hasSanguoLegalMove = hasSanguoLegalMove;
exports.initialSanguoPieces = initialSanguoPieces;
exports.initialSanguoState = initialSanguoState;
exports.legalSanguoTargets = legalSanguoTargets;
exports.nextSanguoTurn = nextSanguoTurn;
exports.nodeId = nodeId;
exports.optionalBannermenCount = optionalBannermenCount;
exports.otherFactions = otherFactions;
exports.pseudoSanguoTargets = pseudoSanguoTargets;
exports.railNodeIds = railNodeIds;
exports.removeGeneralAndAppropriate = removeGeneralAndAppropriate;
exports.resignSanguoFaction = resignSanguoFaction;
exports.resolveSanguoAppropriation = resolveSanguoAppropriation;
exports.roleLabels = roleLabels;
exports.sameNode = sameNode;
exports.sanguoActions = sanguoActions;
exports.sanguoFactions = sanguoFactions;
exports.sanguoNodeIds = sanguoNodeIds;
exports.sanguoPositionKey = sanguoPositionKey;
exports.sanguoStateFrom = sanguoStateFrom;
exports.winnerFromDefeats = winnerFromDefeats;
