// Generated by frontend/scripts/build-xiangqi-engine.mjs. Do not edit by hand.
Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
//#region src/games/heritage-arcade/ported/game/xiangqiRules.ts
const ROLE_LABELS = {
	general: "General",
	advisor: "Advisor",
	elephant: "Elephant",
	horse: "Horse",
	chariot: "Chariot",
	cannon: "Cannon",
	soldier: "Soldier"
};
const SIDE_LABELS = {
	red: "Red / Shu",
	black: "Blue / Wei"
};
const otherSide = (side) => side === "red" ? "black" : "red";
const sameSquare = (a, b) => a.row === b.row && a.col === b.col;
const inBoard = ({ row, col }) => row >= 0 && row < 10 && col >= 0 && col < 9;
const isInPalace = (side, { row, col }) => col >= 3 && col <= 5 && (side === "red" ? row >= 7 && row <= 9 : row >= 0 && row <= 2);
const isHomeSide = (side, row) => side === "red" ? row >= 5 : row <= 4;
const pieceAt = (pieces, square) => pieces.find((piece) => sameSquare(piece, square));
const canLand = (piece, square, pieces) => inBoard(square) && pieceAt(pieces, square)?.side !== piece.side;
const candidate = (piece, square, pieces, targets) => {
	if (canLand(piece, square, pieces)) targets.push(square);
};
const rayTargets = (piece, pieces) => {
	const targets = [];
	for (const [dr, dc] of [
		[-1, 0],
		[1, 0],
		[0, -1],
		[0, 1]
	]) for (let step = 1; step < 10; step += 1) {
		const square = {
			row: piece.row + dr * step,
			col: piece.col + dc * step
		};
		if (!inBoard(square)) break;
		const blocker = pieceAt(pieces, square);
		if (!blocker) targets.push(square);
		else {
			if (blocker.side !== piece.side) targets.push(square);
			break;
		}
	}
	return targets;
};
const cannonTargets = (piece, pieces) => {
	const targets = [];
	for (const [dr, dc] of [
		[-1, 0],
		[1, 0],
		[0, -1],
		[0, 1]
	]) {
		let screened = false;
		for (let step = 1; step < 10; step += 1) {
			const square = {
				row: piece.row + dr * step,
				col: piece.col + dc * step
			};
			if (!inBoard(square)) break;
			const blocker = pieceAt(pieces, square);
			if (!screened) {
				if (!blocker) targets.push(square);
				else screened = true;
				continue;
			}
			if (!blocker) continue;
			if (blocker.side !== piece.side) targets.push(square);
			break;
		}
	}
	return targets;
};
function pseudoLegalTargets(piece, pieces) {
	const targets = [];
	if (piece.role === "chariot") return rayTargets(piece, pieces);
	if (piece.role === "cannon") return cannonTargets(piece, pieces);
	if (piece.role === "general") {
		[
			[-1, 0],
			[1, 0],
			[0, -1],
			[0, 1]
		].forEach(([dr, dc]) => {
			const square = {
				row: piece.row + dr,
				col: piece.col + dc
			};
			if (isInPalace(piece.side, square)) candidate(piece, square, pieces, targets);
		});
		return targets;
	}
	if (piece.role === "advisor") {
		[
			[-1, -1],
			[-1, 1],
			[1, -1],
			[1, 1]
		].forEach(([dr, dc]) => {
			const square = {
				row: piece.row + dr,
				col: piece.col + dc
			};
			if (isInPalace(piece.side, square)) candidate(piece, square, pieces, targets);
		});
		return targets;
	}
	if (piece.role === "elephant") {
		[
			[-2, -2],
			[-2, 2],
			[2, -2],
			[2, 2]
		].forEach(([dr, dc]) => {
			const square = {
				row: piece.row + dr,
				col: piece.col + dc
			};
			const eye = {
				row: piece.row + dr / 2,
				col: piece.col + dc / 2
			};
			if (inBoard(square) && isHomeSide(piece.side, square.row) && !pieceAt(pieces, eye)) candidate(piece, square, pieces, targets);
		});
		return targets;
	}
	if (piece.role === "horse") {
		[
			{
				dr: -2,
				dc: -1,
				legRow: -1,
				legCol: 0
			},
			{
				dr: -2,
				dc: 1,
				legRow: -1,
				legCol: 0
			},
			{
				dr: 2,
				dc: -1,
				legRow: 1,
				legCol: 0
			},
			{
				dr: 2,
				dc: 1,
				legRow: 1,
				legCol: 0
			},
			{
				dr: -1,
				dc: -2,
				legRow: 0,
				legCol: -1
			},
			{
				dr: 1,
				dc: -2,
				legRow: 0,
				legCol: -1
			},
			{
				dr: -1,
				dc: 2,
				legRow: 0,
				legCol: 1
			},
			{
				dr: 1,
				dc: 2,
				legRow: 0,
				legCol: 1
			}
		].forEach(({ dr, dc, legRow, legCol }) => {
			if (!pieceAt(pieces, {
				row: piece.row + legRow,
				col: piece.col + legCol
			})) candidate(piece, {
				row: piece.row + dr,
				col: piece.col + dc
			}, pieces, targets);
		});
		return targets;
	}
	const forward = piece.side === "red" ? -1 : 1;
	candidate(piece, {
		row: piece.row + forward,
		col: piece.col
	}, pieces, targets);
	if (piece.side === "red" ? piece.row <= 4 : piece.row >= 5) {
		candidate(piece, {
			row: piece.row,
			col: piece.col - 1
		}, pieces, targets);
		candidate(piece, {
			row: piece.row,
			col: piece.col + 1
		}, pieces, targets);
	}
	return targets;
}
const generalsFacing = (pieces) => {
	const red = pieces.find((piece) => piece.side === "red" && piece.role === "general");
	const black = pieces.find((piece) => piece.side === "black" && piece.role === "general");
	if (!red || !black || red.col !== black.col) return false;
	const start = Math.min(red.row, black.row) + 1;
	const end = Math.max(red.row, black.row);
	return !pieces.some((piece) => piece.col === red.col && piece.row >= start && piece.row < end);
};
const isInCheck = (side, pieces) => {
	const general = pieces.find((piece) => piece.side === side && piece.role === "general");
	if (!general) return true;
	return generalsFacing(pieces) || pieces.some((piece) => piece.side !== side && pseudoLegalTargets(piece, pieces).some((target) => sameSquare(target, general)));
};
const relocate = (pieces, piece, destination) => {
	const captured = pieceAt(pieces, destination);
	return pieces.filter((candidatePiece) => candidatePiece.id !== captured?.id).map((candidatePiece) => candidatePiece.id === piece.id ? {
		...candidatePiece,
		...destination
	} : candidatePiece);
};
function legalTargets(piece, pieces) {
	return pseudoLegalTargets(piece, pieces).filter((target) => {
		if (pieceAt(pieces, target)?.role === "general") return false;
		const nextPieces = relocate(pieces, piece, target);
		return !isInCheck(piece.side, nextPieces) && !generalsFacing(nextPieces);
	});
}
const hasLegalMove = (side, pieces) => pieces.some((piece) => piece.side === side && legalTargets(piece, pieces).length > 0);
const homeRank = (side) => side === "red" ? 9 : 0;
const cannonRank = (side) => side === "red" ? 7 : 2;
const soldierRank = (side) => side === "red" ? 6 : 3;
function initialXiangqiState() {
	const pieces = [];
	["red", "black"].forEach((side) => {
		const add = (role, row, col, index) => pieces.push({
			id: `${side}-${role}-${index}`,
			side,
			role,
			row,
			col
		});
		[
			"chariot",
			"horse",
			"elephant",
			"advisor",
			"general",
			"advisor",
			"elephant",
			"horse",
			"chariot"
		].forEach((role, col) => add(role, homeRank(side), col, col));
		add("cannon", cannonRank(side), 1, 0);
		add("cannon", cannonRank(side), 7, 1);
		[
			0,
			2,
			4,
			6,
			8
		].forEach((col, index) => add("soldier", soldierRank(side), col, index));
	});
	return {
		pieces,
		turn: "red",
		winner: null,
		result: null,
		note: "Red / Shu opens. Select a coin to reveal legal intersections.",
		moveNumber: 1,
		lastMove: null
	};
}
function applyXiangqiMove(state, pieceId, destination) {
	if (state.winner) return null;
	const piece = state.pieces.find((candidatePiece) => candidatePiece.id === pieceId);
	if (!piece || piece.side !== state.turn || !legalTargets(piece, state.pieces).some((target) => sameSquare(target, destination))) return null;
	const captured = pieceAt(state.pieces, destination);
	const pieces = relocate(state.pieces, piece, destination);
	const nextTurn = otherSide(piece.side);
	const checked = isInCheck(nextTurn, pieces);
	const noReply = !hasLegalMove(nextTurn, pieces);
	const action = `${SIDE_LABELS[piece.side]} ${ROLE_LABELS[piece.role]} ${captured ? `captures ${SIDE_LABELS[captured.side]} ${ROLE_LABELS[captured.role]}` : "advances"}`;
	const lastMove = {
		from: {
			row: piece.row,
			col: piece.col
		},
		to: destination,
		side: piece.side,
		role: piece.role,
		captured: captured?.role
	};
	if (noReply) {
		const result = checked ? "checkmate" : "stalemate";
		return {
			pieces,
			turn: nextTurn,
			winner: piece.side,
			result,
			note: `${action}. ${result === "checkmate" ? "Checkmate" : "Stalemate"} — ${SIDE_LABELS[piece.side]} wins.`,
			moveNumber: state.moveNumber + 1,
			lastMove
		};
	}
	return {
		pieces,
		turn: nextTurn,
		winner: null,
		result: null,
		note: `${action}.${checked ? ` Check — ${SIDE_LABELS[nextTurn]} must answer.` : ` ${SIDE_LABELS[nextTurn]} to move.`}`,
		moveNumber: state.moveNumber + 1,
		lastMove
	};
}
//#endregion
//#region src/games/xiangqi/engine.ts
const RULESET_VERSION = "standard-xiangqi-v1";
const SIDES = ["red", "black"];
const BOT_LEVELS = {
	easy: {
		label: "Easy",
		description: "Varied legal moves with a light preference for captures."
	},
	medium: {
		label: "Medium",
		description: "Two-kingdom tactical search with checks, recaptures and river-crossing threats."
	},
	hard: {
		label: "Hard",
		description: "Deeper alpha-beta strategy with tactical continuations. No deliberate mistakes."
	}
};
const createInitialState = initialXiangqiState;
function getLegalActions(state) {
	if (state.winner) return [];
	return state.pieces.filter((p) => p.side === state.turn).flatMap((p) => legalTargets(p, state.pieces).map((to) => ({
		pieceId: p.id,
		to
	})));
}
function applyAction(state, action) {
	const next = applyXiangqiMove(state, action.pieceId, action.to);
	return next ? { state: next } : { error: "That move is not legal." };
}
const VALUES = {
	general: 0,
	chariot: 900,
	cannon: 450,
	horse: 400,
	elephant: 200,
	advisor: 200,
	soldier: 100
};
const other = (side) => side === "red" ? "black" : "red";
function evaluate(state) {
	let score = 0;
	for (const p of state.pieces) {
		const advance = p.side === "red" ? 9 - p.row : p.row;
		const value = VALUES[p.role] + (p.role === "soldier" ? advance * 8 + (advance >= 5 ? 65 : 0) : p.role === "general" ? 0 : advance * 2) + (p.role === "horse" || p.role === "chariot" ? (4 - Math.abs(4 - p.col)) * 3 : 0);
		score += p.side === state.turn ? value : -value;
	}
	return score + (isInCheck(state.turn, state.pieces) ? -45 : 0) + (isInCheck(other(state.turn), state.pieces) ? 45 : 0);
}
function advance(state, action) {
	const pieces = state.pieces.filter((p) => !(p.row === action.to.row && p.col === action.to.col)).map((p) => p.id === action.pieceId ? {
		...p,
		...action.to
	} : p);
	return {
		...state,
		pieces,
		turn: other(state.turn),
		moveNumber: state.moveNumber + 1
	};
}
function ordered(state, actions) {
	const priority = (a) => {
		const capture = pieceAt(state.pieces, a.to);
		return capture ? VALUES[capture.role] * 10 - VALUES[state.pieces.find((p) => p.id === a.pieceId).role] : 0;
	};
	return [...actions].sort((a, b) => priority(b) - priority(a));
}
function chooseXiangqiAction(state, difficulty = "medium", options = {}) {
	const actions = getLegalActions(state);
	if (!actions.length) return null;
	if (difficulty === "easy") {
		const weights = actions.map((a) => pieceAt(state.pieces, a.to) ? 1.6 : 1);
		let pick = (options.random || Math.random)() * weights.reduce((a, b) => a + b, 0);
		return actions.find((_, i) => (pick -= weights[i]) < 0) || actions.at(-1);
	}
	const hard = difficulty === "hard", deadline = Date.now() + (options.budgetMs ?? (hard ? 1800 : 500));
	let nodes = 0;
	const stop = {}, maxNodes = options.maxNodes ?? (hard ? 18e3 : 4e3);
	function search(position, depth, alpha, beta, ply, tactical) {
		if (++nodes > maxNodes || Date.now() >= deadline) throw stop;
		let legal = getLegalActions(position);
		if (!legal.length) return -1e5 + ply;
		if (depth <= 0) {
			const value = evaluate(position);
			if (tactical <= 0) return value;
			if (!isInCheck(position.turn, position.pieces)) {
				if (value >= beta) return value;
				alpha = Math.max(alpha, value);
				legal = legal.filter((a) => pieceAt(position.pieces, a.to));
				if (!legal.length) return value;
			}
		}
		for (const action of ordered(position, legal)) {
			const value = -search(advance(position, action), depth - 1, -beta, -alpha, ply + 1, depth <= 0 ? tactical - 1 : tactical);
			if (value >= beta) return value;
			alpha = Math.max(alpha, value);
		}
		return alpha;
	}
	let root = ordered(state, actions), best = root[0];
	for (let depth = 1; depth <= (options.depth ?? (hard ? 4 : 2)); depth++) {
		let candidate = best, score = -Infinity;
		try {
			for (const action of root) {
				const value = -search(advance(state, action), depth - 1, -Infinity, -score, 1, hard ? 2 : 1);
				if (value > score) {
					score = value;
					candidate = action;
				}
			}
			best = candidate;
			root = [best, ...root.filter((a) => a !== best)];
			if (score > 99900) break;
		} catch (error) {
			if (error !== stop) throw error;
			break;
		}
	}
	return best;
}
//#endregion
exports.BOT_LEVELS = BOT_LEVELS;
exports.RULESET_VERSION = RULESET_VERSION;
exports.SIDES = SIDES;
exports.applyAction = applyAction;
exports.chooseXiangqiAction = chooseXiangqiAction;
exports.createInitialState = createInitialState;
exports.getLegalActions = getLegalActions;
