import {fileURLToPath} from 'node:url';
import path from 'node:path';
import fs from 'node:fs/promises';
import {createRequire} from 'node:module';
const here=path.dirname(fileURLToPath(import.meta.url));
const mobile=path.resolve(here,'..'),root=path.resolve(mobile,'../..');
const require=createRequire(path.join(root,'frontend/package.json'));
const {build}=await import(require.resolve('rolldown'));
const sharp=require('sharp');
const destination=path.join(mobile,'android/app/src/main/assets');
await fs.rm(destination,{recursive:true,force:true});await fs.mkdir(destination,{recursive:true});
const browser=await build({input:path.join(mobile,'src/App.jsx'),platform:'browser',resolve:{alias:{react:path.join(root,'frontend/node_modules/react'),'react-dom':path.join(root,'frontend/node_modules/react-dom'),'lucide-react':path.join(root,'frontend/node_modules/lucide-react')}},transform:{define:{'process.env.NODE_ENV':'"production"'}},output:{dir:destination,format:'iife',entryFileNames:'app.js',minify:true}});
await fs.copyFile(path.join(mobile,'src/styles.css'),path.join(destination,'app.css'));
await fs.copyFile(path.join(mobile,'THIRD_PARTY_NOTICES.txt'),path.join(destination,'THIRD_PARTY_NOTICES.txt'));
await build({input:path.join(mobile,'src/bot.worker.js'),platform:'browser',output:{file:path.join(destination,'bot.js'),format:'iife',minify:true}});
const canonical=await build({input:path.join(mobile,'src/games.ts'),platform:'node',output:{file:path.join(root,'server/arcticPlayEngine.cjs'),format:'cjs',minify:false,banner:'// Generated by mobile/arctic-play/scripts/build-web.mjs. Do not edit; imports canonical Heritage Arcade rules.'}});
await build({input:path.join(mobile,'src/games.ts'),platform:'node',output:{file:path.join(mobile,'build/games.cjs'),format:'cjs',minify:false}});
const files=await fs.readdir(destination);const css=files.filter(f=>f.endsWith('.css'));
await fs.writeFile(path.join(destination,'index.html'),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,viewport-fit=cover"><meta name="color-scheme" content="light dark"><meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src wss://articweb3.onrender.com; worker-src 'self'; font-src 'self'; base-uri 'none'; object-src 'none'"><title>Arctic Play</title>${css.map(f=>`<link rel="stylesheet" href="${f}">`).join('')}</head><body><div id="root"></div><script src="app.js"></script></body></html>`);
const art=path.join(destination,'art'),source=path.join(root,'frontend/public/assets');
async function copy(relative,target){const to=path.join(art,target);await fs.mkdir(path.dirname(to),{recursive:true});await sharp(path.join(source,relative)).resize({width:target.includes('board')?1334:256,withoutEnlargement:true}).webp({quality:90,alphaQuality:100}).toFile(to);}
async function board(relative,target,size=1280){const to=path.join(art,target);await fs.mkdir(path.dirname(to),{recursive:true});await sharp(path.join(source,relative)).resize({width:size,withoutEnlargement:true}).webp({quality:87}).toFile(to);}
for(const [folder,target,colors] of [['games/shogi-frozen-shogunate','shogi',['red','blue']],['games/sannin-shogi','sannin',['red','green','blue']]]){
  for(const file of await fs.readdir(path.join(source,folder)))if(file.endsWith('.webp')&&(colors.some(c=>file.startsWith(c+'-'))||file==='board.webp'))await copy(`${folder}/${file}`,`${target}/${file}`);
}
const tokens=await fs.readdir(path.join(source,'heritage-arcade/tokens'));
for(const file of tokens)if(/^token-sanguo-(red|green|blue)-[a-z]+\.webp$/.test(file))await copy(`heritage-arcade/tokens/${file}`,`tokens/${file}`);
for(const file of await fs.readdir(path.join(source,'heritage-arcade/tokens/sanyou')))if(file.endsWith('.webp'))await copy(`heritage-arcade/tokens/sanyou/${file}`,`sanyou/${file}`);
for(const file of await fs.readdir(path.join(source,'heritage-arcade/sanguo-yan-yi/pieces')))if(file.endsWith('.webp'))await copy(`heritage-arcade/sanguo-yan-yi/pieces/${file}`,`yanyi/pieces/${file}`);
await copy('heritage-arcade/sanguo-yan-yi/yan-yi-arctic-board.webp','yanyi/yan-yi-arctic-board.webp');
await board('heritage-arcade/board/sanguo-arctic-board.png','boards/sanguo.webp');
await board('heritage-arcade/board/sanyou-arctic-board.png','boards/sanyou.webp');
await board('heritage-arcade/board/xiangqi-arctic-board.png','boards/xiangqi.webp');
const size=await fs.stat(path.join(destination,'app.js'));
console.log(`Built Android web app: ${files.join(', ')}; JavaScript ${(size.size/1024).toFixed(0)} KiB. Only six games and their assets are bundled.`);
