/** Icebound Strategy Atlas: audited modern team Chaturaji / four-handed Chaturanga table. */
import { useMemo, useState } from "react";
import { ALL_CLANS, CLANS, ClanId } from "@/game/millsRules";
type Kind = "K" | "R" | "N" | "B" | "P";
type Piece = { id: string; owner: ClanId; kind: Kind; row: number; col: number };
type State = { pieces: Piece[]; turn: number; selected: string | null; eliminated: ClanId[]; winner: "red-yellow" | "green-black" | null; note: string; actions: number };
const roster = ALL_CLANS as ClanId[]; const order = ["polly", "pengu", "abster", "retsba"] as ClanId[]; const team = (clan: ClanId) => clan === "polly" || clan === "abster" ? "red-yellow" : "green-black";
const key = (row: number, col: number) => `${row}:${col}`;
const initial = (): State => {
  const pieces: Piece[] = []; const add = (owner: ClanId, kind: Kind, row: number, col: number) => pieces.push({ id: `${owner}-${kind}-${row}-${col}`, owner, kind, row, col });
  [["retsba", "K", 4, 0], ["retsba", "B", 5, 0], ["retsba", "N", 6, 0], ["retsba", "R", 7, 0], ["polly", "K", 0, 4], ["polly", "B", 0, 5], ["polly", "N", 0, 6], ["polly", "R", 0, 7], ["pengu", "K", 4, 7], ["pengu", "B", 5, 7], ["pengu", "N", 6, 7], ["pengu", "R", 7, 7], ["abster", "K", 7, 3], ["abster", "B", 7, 2], ["abster", "N", 7, 1], ["abster", "R", 7, 0]].forEach(([owner, kind, row, col]) => add(owner as ClanId, kind as Kind, row as number, col as number));
  for (let row = 4; row <= 7; row += 1) add("retsba", "P", row, 1); for (let col = 4; col <= 7; col += 1) add("polly", "P", 1, col); for (let row = 4; row <= 7; row += 1) add("pengu", "P", row, 6); for (let col = 0; col <= 3; col += 1) add("abster", "P", 6, col);
  return { pieces, turn: 0, selected: null, eliminated: [], winner: null, note: "Polly Clan (red) opens. Polly and Abster form one team; Pengu and Retsba form the other.", actions: 0 };
};
const inBoard = (r: number, c: number) => r >= 0 && r < 8 && c >= 0 && c < 8;
const occupied = (state: State, r: number, c: number) => state.pieces.find((piece) => piece.row === r && piece.col === c);
const pawnStep: Record<ClanId, [number, number]> = { polly: [1, 0], retsba: [0, 1], pengu: [0, -1], abster: [-1, 0] };
function targets(state: State, piece: Piece) { const out: string[] = []; const add = (r: number, c: number) => { const hit = occupied(state, r, c); if (inBoard(r, c) && (!hit || hit.owner !== piece.owner)) out.push(key(r, c)); }; if (piece.kind === "K") [[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]].forEach(([dr,dc])=>add(piece.row+dr,piece.col+dc)); if (piece.kind === "N") [[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]].forEach(([dr,dc])=>add(piece.row+dr,piece.col+dc)); if (piece.kind === "B") [[-2,-2],[-2,2],[2,-2],[2,2]].forEach(([dr,dc])=>add(piece.row+dr,piece.col+dc)); if (piece.kind === "P") { const [dr,dc] = pawnStep[piece.owner]; add(piece.row + dr, piece.col + dc); } if (piece.kind === "R") [[-1,0],[1,0],[0,-1],[0,1]].forEach(([dr,dc])=>{ for(let d=1; d<8; d+=1){ const r=piece.row+dr*d,c=piece.col+dc*d; if(!inBoard(r,c)) break; const hit=occupied(state,r,c); if(!hit) out.push(key(r,c)); else { if(hit.owner!==piece.owner) out.push(key(r,c)); break; } } }); return out; }
const isPromotion = (piece: Piece) => piece.kind === "P" && ((piece.owner === "polly" && piece.row === 7) || (piece.owner === "retsba" && piece.col === 7) || (piece.owner === "pengu" && piece.col === 0) || (piece.owner === "abster" && piece.row === 0));
export default function ChaturajiBoard({ onBack }: { onBack: () => void }) { const [game, setGame] = useState<State>(initial); const [history, setHistory] = useState<State[]>([]); const current = order[game.turn]; const selected = game.pieces.find((piece) => piece.id === game.selected); const legal = useMemo(() => selected ? targets(game, selected) : [], [game, selected]); const commit = (next: State) => { setHistory((past) => [...past.slice(-60), game]); setGame(next); };
  const move = (r: number, c: number) => { if (game.winner || game.eliminated.includes(current)) return; const target = occupied(game,r,c); if(target?.owner===current){ commit({ ...game, selected: game.selected===target.id?null:target.id, note:`${CLANS[current].name} selected ${target.kind}.`}); return; } if(!selected || !legal.includes(key(r,c))) return; const capture=target; let pieces=game.pieces.filter((piece)=>piece.id!==capture?.id).map((piece)=>piece.id===selected.id?{...piece,row:r,col:c}:piece); const moved=pieces.find((piece)=>piece.id===selected.id)!; let boatCapture=""; if(moved.kind==="B"){ const squares=[[r,c],[r-1,c],[r,c-1],[r-1,c-1]]; if(squares.every(([sr,sc])=>inBoard(sr,sc)&&occupied({ ...game,pieces },sr,sc)?.kind==="B")){ const removed=squares.filter(([sr,sc])=>!(sr===r&&sc===c)).map(([sr,sc])=>occupied({ ...game,pieces },sr,sc)!.id); pieces=pieces.filter((piece)=>!removed.includes(piece.id)); boatCapture=" Boat triumph removes three other Boats."; } } if(isPromotion(moved)) pieces=pieces.map((piece)=>piece.id===moved.id?{...piece,kind:"R"}:piece); const eliminated=capture?.kind==="K"?[...game.eliminated,capture.owner]:game.eliminated; const remainingTeams=["red-yellow","green-black"].filter((side)=>order.some((clan)=>team(clan)===side&&!eliminated.includes(clan))); const winner=remainingTeams.length===1?remainingTeams[0] as State["winner"]:null; let next=(game.turn+1)%4; while(eliminated.includes(order[next])) next=(next+1)%4; commit({ pieces,turn:next,selected:null,eliminated,winner,note:winner?`${winner === "red-yellow" ? "Polly and Abster" : "Pengu and Retsba"} take both opposing Kings and win.`:`${capture?`${CLANS[current].name} captures ${capture.kind}. `:""}${isPromotion(moved)?"Pawn promotes to Rook. ":""}${boatCapture}${CLANS[order[next]].name} to move.`,actions:game.actions+1 }); };
  return <main className="compact-screen"><header className="table-header"><button type="button" className="text-button" onClick={onBack}>← Back to Icebound Atlas</button><div className="table-title"><div className="table-brand"><span className="table-compass">✦</span><span>AUDITED FOUR-PLAYER TABLE</span></div><span className="eyebrow">CHATURAJI · MODERN TEAM VARIANT</span><h1>Four thrones, one floe.</h1><p>8×8 uncheckered board · red/yellow versus green/black.</p></div><div className="table-actions"><button type="button" onClick={()=>{setHistory([]);setGame(initial());}}>Reset expedition</button><button type="button" disabled={!history.length} onClick={()=>{const past=history.at(-1);if(past){setHistory((all)=>all.slice(0,-1));setGame(past);}}}>Undo route</button></div></header><section className="compact-table"><aside className="match-rail"><div className="compass-status"><span className="pulse-dot" style={{background:CLANS[current].color}}/><span>{game.winner?"CONCLUDED":"ACTIVE TURN"}</span></div><h2>{game.winner?`${game.winner === "red-yellow"?"Polly + Abster":"Pengu + Retsba"} win`:`${CLANS[current].name}'s turn`}</h2><p>{game.note}</p><div className="match-player-stack">{order.map((clan)=><article key={clan} className={`match-player ${current===clan?"is-turn":""}`} style={{"--clan":CLANS[clan].color} as React.CSSProperties}><img src={CLANS[clan].portrait} alt=""/><div><strong>{CLANS[clan].name}</strong><span>{game.eliminated.includes(clan)?"King taken":"King in play"}</span></div></article>)}</div></aside><section className="compact-board-panel"><div className="board-caption"><span>UN-CHEQUERED FROZEN FLOE</span><strong>ACTION {game.actions}</strong></div><div className="chaturaji-board">{Array.from({length:64},(_,index)=>{const r=Math.floor(index/8),c=index%8,piece=occupied(game,r,c);return <button type="button" key={key(r,c)} className={`chaturaji-cell ${legal.includes(key(r,c))?"legal":""} ${selected?.id===piece?.id?"selected":""}`} onClick={()=>move(r,c)}>{piece&&<span className={`chaturaji-piece ${piece.kind}`} style={{"--piece":CLANS[piece.owner].color,backgroundImage:`url(${CLANS[piece.owner].portrait})`} as React.CSSProperties}><b>{piece.kind}</b></span>}</button>})}</div><div className="event-tape"><span>FIELD NOTE</span><p>{game.note}</p></div></section><aside className="rules-panel"><span className="eyebrow">ROUTE BRIEFING</span><h2>Modern team form</h2><ol><li>Four players move clockwise: red, green, yellow, black.</li><li>Each army has King, Rook/Elephant, Knight, Boat, and four Pawns.</li><li>King, Rook, and Knight use orthodox movement; the Boat leaps two diagonal squares.</li><li>Form a 2×2 square of Boats to trigger a Boat triumph; the first team to take both opposing Kings wins.</li></ol><div className="debug-box"><strong>Audit choice</strong><span>This table uses the documented modern team objective and its optional simplified pawn promotion convention.</span></div></aside></section></main>; }
