/** Icebound Strategy Atlas: compact, transparent rules contracts for each additional playable dossier. */
export type BoardShape = "grid" | "cross" | "ring" | "hex" | "hex61" | "hex91" | "liubo" | "triad" | "fourfront" | "italy" | "india" | "map";
export type Interaction = "march" | "claim" | "draft" | "stack";
export type CompactMode = {
  id: number;
  shape: BoardShape;
  interaction: Interaction;
  rows: number;
  cols: number;
  actionLimit: number;
  boardLabel: string;
  objective: string;
  mechanics: string[];
  historicalNote: string;
};

export const COMPACT_MODES: Record<number, CompactMode> = {
  1: { id: 1, shape: "triad", interaction: "march", rows: 11, cols: 11, actionLimit: 120, boardLabel: "Three Kingdoms lattice", objective: "Protect your General and break through the rival fronts.", mechanics: ["Three home sectors meet through a three-sided polygonal lattice rather than a generic hex grid.", "Move along adjacent linked intersections; capture by landing.", "The dedicated piece engine will replace this temporary generic march resolver."], historicalNote: "Partial reconstruction: board form follows Three Kingdoms diagrams; move rules require the selected edition’s source sheet." },
  2: { id: 2, shape: "fourfront", interaction: "march", rows: 17, cols: 17, actionLimit: 160, boardLabel: "Four Kingdoms xiangqi field", objective: "Protect your General and outmaneuver the four opposing fronts.", mechanics: ["Four xiangqi-style home fronts surround one wide central field.", "Each front enters through a dedicated arm rather than a 7×7 compact cross.", "The dedicated xiangqi piece engine will replace this temporary generic march resolver."], historicalNote: "Partial reconstruction: four-front board geometry follows Siguo Xiangqi diagrams; rules engine pending selected edition." },
  3: { id: 3, shape: "grid", interaction: "march", rows: 36, cols: 36, actionLimit: 140, boardLabel: "Taikyoku Shogi 36×36 field", objective: "Survey the documented giant-board scale before selecting a playable reduced edition.", mechanics: ["The table uses the historic 36×36 board scale and two opposed home armies instead of a false small hex board.", "The full historical piece catalogue is too large for the prior compact rules engine and is not simulated here.", "A dedicated selectable-viewport engine is required before claiming full Taikyoku Shogi play."], historicalNote: "Documented scale and two-player board; this is an accurate-scale layout viewer, not a completed Taikyoku Shogi rules engine." },
  4: { id: 4, shape: "italy", interaction: "claim", rows: 9, cols: 9, actionLimit: 84, boardLabel: "Machiavelli Italian campaign map", objective: "Accumulate the most court influence across the regional campaign map.", mechanics: ["The layout uses a boot-shaped network of regional city nodes rather than a generic province grid.", "Claim or reinforce one region each season.", "The full published diplomatic order system requires a dedicated private-order engine."], historicalNote: "Modern published game: map form is reference-led; the compact public order system is still a separate adaptation." },
  5: { id: 5, shape: "grid", interaction: "march", rows: 8, cols: 8, actionLimit: 100, boardLabel: "Four Kings uncheckered floe", objective: "Capture rival royalty and lead in trophy value.", mechanics: ["Four clans start at the four corners.", "Move along marked adjacent squares; capture by landing.", "A four-corner Skiff formation grants a two-point triumph."], historicalNote: "Dice-free individual Pudgy adaptation of Chaturaji." },
  6: { id: 6, shape: "triad", interaction: "march", rows: 11, cols: 11, actionLimit: 150, boardLabel: "Jorigi Three-Fortress lattice", objective: "Be the last fortress with active penguins.", mechanics: ["Three fortified home sectors meet at a central nexus.", "Move one adjacent lattice node and capture when a rival is flanked on a visible line.", "A successful capture grants an extra trophy point."], historicalNote: "Pudgy Penguins Original: the route uses its fully declared three-fortress board contract." },
  7: { id: 7, shape: "triad", interaction: "claim", rows: 11, cols: 11, actionLimit: 150, boardLabel: "Ryukyu Sanzan Three-Hills field", objective: "Control the most hill intersections and sealed pockets.", mechanics: ["Place a stone on an open triangular-field intersection.", "A new adjacent pair strengthens that clan’s territory total.", "Completing a three-sided pocket earns a Perimeter Cut point."], historicalNote: "Pudgy Penguins Original: this is not represented as a recovered historical Go ruleset." },
  8: { id: 8, shape: "ring", interaction: "draft", rows: 1, cols: 18, actionLimit: 72, boardLabel: "Baltic market wheel", objective: "Secure docks, gates, and the richest fish haul.", mechanics: ["Choose an open spoke or dock to gather, raid, or fortify.", "A controlled dock gains a fish point at the end of a full round.", "A second adjacent control becomes a fortified gate."], historicalNote: "Pudgy Penguins Original." },
  9: { id: 9, shape: "india", interaction: "claim", rows: 9, cols: 9, actionLimit: 72, boardLabel: "Bharata regional campaign map", objective: "Build influence across the published Indian-subcontinent map.", mechanics: ["The layout uses a peninsula-shaped regional node map rather than a generic 3×4 grid.", "Claim an open region or reinforce your existing route.", "The publisher’s complete action-and-card system remains a dedicated implementation target."], historicalNote: "Modern published game: the map silhouette follows product imagery; the current public claim engine is not its full rule system." },
  10: { id: 10, shape: "hex61", interaction: "march", rows: 9, cols: 9, actionLimit: 180, boardLabel: "Heptanthos Seven-path flower", objective: "Survive the flower war and pressure rival home sectors.", mechanics: ["Seven radial paths are represented by a compact flower-shaped hex field.", "A token entering the center ring earns pressure score.", "Capturing an isolated rival token earns a Triple-Lock trophy."], historicalNote: "Pudgy Penguins Original: full board identity is declared in the rulebook." },
  11: { id: 11, shape: "triad", interaction: "march", rows: 11, cols: 11, actionLimit: 140, boardLabel: "Ludus Regalis Three-Crown nexus", objective: "Take rival Crowns or dominate the nexus.", mechanics: ["Each triangular front is a Crown home.", "Move a guard along a linked lattice point and capture by landing.", "Nexus entries award a Crown pressure point."], historicalNote: "Pudgy Penguins Original: full board identity is declared in the rulebook." },
  13: { id: 13, shape: "hex61", interaction: "claim", rows: 9, cols: 9, actionLimit: 120, boardLabel: "Ttaht Nubian ridge web", objective: "Build ridges and prevent your clan from being pushed away.", mechanics: ["Place a pebble on an open hex-web node.", "Three same-clan adjacent pebbles earn a ridge point.", "Ridge points make captured rivals worth two trophies."], historicalNote: "Pudgy Penguins Original: the board and score logic are declared rather than attributed to an unverified tradition." },
  14: { id: 14, shape: "liubo", interaction: "march", rows: 5, cols: 5, actionLimit: 108, boardLabel: "Twelve-road Owl board", objective: "Move six birds along the reconstructed roads and awaken the central Owl.", mechanics: ["The visible table uses the surviving road-board geometry rather than a generic ring.", "Each side fields six birds; the central pond is the Owl state.", "Movement and victory use the selected reconstruction because original Liubo rules are lost."], historicalNote: "Reconstruction: board geometry, two players, six pieces each, and an Owl are documented; movement and victory are not." },
  15: { id: 15, shape: "cross", interaction: "march", rows: 7, cols: 7, actionLimit: 96, boardLabel: "Three-Theater trenches", objective: "Secure the radio mast and out-rank enemy ranks.", mechanics: ["Each token has a hidden rank shown only to its owner in a handoff game; this compact mode uses visible colors.", "Moving to the central mast earns control score.", "Captures award two points to simulate successful rank clashes."], historicalNote: "Three-clan Pudgy extension of documented two-sided L’Attaque." },
  16: { id: 16, shape: "triad", interaction: "draft", rows: 11, cols: 11, actionLimit: 54, boardLabel: "San Guo Zhi Battalion Bridges", objective: "Win the most bridges and collect rival battalions.", mechanics: ["Three theater fronts meet through a triangular bridge lattice.", "Claim an open bridge with one battalion token.", "Holding a bridge for a full round earns a fish score."], historicalNote: "Pudgy Penguins Original: this is a fully disclosed board contract, not an unsupported historical claim." },
  17: { id: 17, shape: "hex91", interaction: "march", rows: 11, cols: 11, actionLimit: 120, boardLabel: "Agon Queen’s Guard field", objective: "Escort your Queen onto the center cell before the opposing guard does.", mechanics: ["The table uses the 91-cell hexagonal field and four exterior starting markers from the selected Agon board reference.", "The current two-side rules remain marked for dedicated movement-engine completion.", "The center is an objective square, not a generic score zone."], historicalNote: "Documented board geometry; dedicated historical Agon move rules are still under rebuild." },
  18: { id: 18, shape: "grid", interaction: "march", rows: 11, cols: 11, actionLimit: 120, boardLabel: "Copenhagen 11×11 Tafl field", objective: "The King escapes to a corner; attackers encircle and capture the King.", mechanics: ["The table now uses Copenhagen’s 11×11 geometry with a central throne and four corner escape squares.", "The current path engine is a visual scaffold pending Copenhagen’s dedicated asymmetric capture engine.", "This route is two-player, not a three-clan extension."], historicalNote: "Selected edition: Copenhagen Hnefatafl. Board geometry is reference-led; asymmetric rules engine pending." },
  19: { id: 19, shape: "cross", interaction: "march", rows: 7, cols: 7, actionLimit: 96, boardLabel: "Fortress Breakwater", objective: "Fill the fortress or clear the rebels.", mechanics: ["Raiders advance through cross-lattice paths toward the central fort.", "Officer captures are represented by a two-point landing capture.", "Controlling three fort cells awards an immediate siege bonus."], historicalNote: "Three-clan Pudgy extension of two-sided Asalto." },
  20: { id: 20, shape: "grid", interaction: "stack", rows: 5, cols: 5, actionLimit: 90, boardLabel: "Ludus Turrium Towers of Ice", objective: "Command the tallest stacks and own the central tower field.", mechanics: ["Place or stack a disk on one of 25 tower foundations.", "Taking an enemy top disk changes stack command.", "A stack of four creates a fracture bonus for its owner."], historicalNote: "Pudgy Penguins Original: full five-by-five stack-field contract." },
  21: { id: 21, shape: "grid", interaction: "claim", rows: 16, cols: 8, actionLimit: 120, boardLabel: "Rithmomachia 8×16 number field", objective: "Build the documented numerical formations on the double chessboard.", mechanics: ["The table now uses the historical 8×16 board ratio instead of a generic 8×8 grid.", "The next dedicated engine will load the Lever–Fulke piece values, shapes, and capture relations.", "This is a two-player numerical game; Black / Team Odds opens in the selected orientation."], historicalNote: "Documented board dimensions and orientation; numerical-piece engine pending." },
  22: { id: 22, shape: "triad", interaction: "march", rows: 11, cols: 11, actionLimit: 120, boardLabel: "Sanguo Chess River Fortress lattice", objective: "Cross the ice river and take rival Generals.", mechanics: ["Three fortress lanes meet through a river-marked triangular lattice.", "The central river nodes award promotion score.", "Capture a rival commander token for three points."], historicalNote: "Pudgy Penguins Original: full triangular board contract." },
  23: { id: 23, shape: "grid", interaction: "march", rows: 8, cols: 8, actionLimit: 100, boardLabel: "Four-Handed Floe Chess", objective: "Capture royalty and claim opposing thrones.", mechanics: ["Four corner armies move on an uncheckered floe.", "Landing capture removes the rival token and grants its value.", "A boat-triumph pattern earns a bonus score."], historicalNote: "Dice-free individual arcade configuration of the documented four-player family." },
  24: { id: 24, shape: "hex61", interaction: "march", rows: 9, cols: 9, actionLimit: 130, boardLabel: "Sannin Shogi Three-Home hex", objective: "Protect your King and dominate promotion ice.", mechanics: ["The three-home field now uses a true hexagonal 61-cell envelope rather than a rectangular fake hex grid.", "Move across six hex directions toward the central promotion ice.", "The dedicated Sannin Shogi piece and drop engine remains a separate rules rebuild."], historicalNote: "Documented three-player board family: geometry corrected from visual reference; full piece engine pending." },
};

export const getCompactMode = (id: number) => COMPACT_MODES[id];
