export const SANGUO_VIEWBOX = "0 0 1280 1124";

export type SanguoFaction = "red" | "blue" | "green";
export type SourcePoint = { x: number; y: number };

const CENTER: SourcePoint = { x: 640, y: 625 };

// Fixed samples transcribed from the supplied source setup. Each northern sector has its own trace;
// they must not be generated by rotating the red field because the source uses different line terminations.
const RED_FIELD: SourcePoint[][] = [
  [{ x: 548, y: 718 }, { x: 571, y: 703 }, { x: 594, y: 691 }, { x: 617, y: 683 }, { x: 640, y: 680 }, { x: 663, y: 683 }, { x: 686, y: 691 }, { x: 709, y: 703 }, { x: 732, y: 718 }],
  [{ x: 260, y: 886 }, { x: 350, y: 850 }, { x: 450, y: 809 }, { x: 544, y: 770 }, { x: 640, y: 731 }, { x: 735, y: 770 }, { x: 829, y: 809 }, { x: 930, y: 850 }, { x: 1018, y: 886 }],
  [{ x: 319, y: 925 }, { x: 379, y: 917 }, { x: 470, y: 900 }, { x: 555, y: 880 }, { x: 640, y: 865 }, { x: 725, y: 880 }, { x: 810, y: 900 }, { x: 899, y: 918 }, { x: 960, y: 925 }],
  [{ x: 338, y: 994 }, { x: 389, y: 985 }, { x: 440, y: 978 }, { x: 491, y: 973 }, { x: 542, y: 970 }, { x: 593, y: 973 }, { x: 644, y: 978 }, { x: 695, y: 985 }, { x: 746, y: 994 }],
  [{ x: 354, y: 1047 }, { x: 425, y: 1047 }, { x: 496, y: 1047 }, { x: 568, y: 1047 }, { x: 640, y: 1047 }, { x: 712, y: 1047 }, { x: 784, y: 1047 }, { x: 855, y: 1047 }, { x: 926, y: 1047 }],
];

const BLUE_FIELD: SourcePoint[][] = [
  [{ x: 545, y: 265 }, { x: 540, y: 315 }, { x: 535, y: 365 }, { x: 530, y: 415 }, { x: 525, y: 465 }, { x: 520, y: 500 }, { x: 505, y: 525 }, { x: 470, y: 545 }, { x: 400, y: 565 }],
  [{ x: 544, y: 70 }, { x: 530, y: 165 }, { x: 519, y: 276 }, { x: 510, y: 370 }, { x: 493, y: 476 }, { x: 420, y: 540 }, { x: 329, y: 602 }, { x: 250, y: 660 }, { x: 167, y: 724 }],
  [{ x: 450, y: 170 }, { x: 460, y: 159 }, { x: 410, y: 290 }, { x: 390, y: 350 }, { x: 370, y: 410 }, { x: 350, y: 470 }, { x: 330, y: 530 }, { x: 201, y: 609 }, { x: 270, y: 630 }],
  [{ x: 400, y: 120 }, { x: 375, y: 180 }, { x: 350, y: 245 }, { x: 325, y: 305 }, { x: 300, y: 365 }, { x: 275, y: 425 }, { x: 250, y: 485 }, { x: 225, y: 545 }, { x: 190, y: 600 }],
  [{ x: 350, y: 70 }, { x: 315, y: 130 }, { x: 280, y: 190 }, { x: 245, y: 255 }, { x: 210, y: 315 }, { x: 175, y: 375 }, { x: 145, y: 435 }, { x: 110, y: 495 }, { x: 70, y: 560 }],
];

const GREEN_FIELD: SourcePoint[][] = BLUE_FIELD.map((rank) => rank.map(({ x, y }) => ({ x: 1280 - x, y })));

export const SOURCE_NODES: Record<SanguoFaction, SourcePoint[][]> = {
  red: RED_FIELD,
  blue: BLUE_FIELD,
  green: GREEN_FIELD,
};

export const fieldPoint = (sector: SanguoFaction, rank: number, file: number) => SOURCE_NODES[sector][rank][file];
export const fieldPolyline = (points: SourcePoint[]) => points.map((point) => `${point.x},${point.y}`).join(" ");

export const SOURCE_SECTORS: Record<SanguoFaction, string> = {
  blue: "M350 70 L540 70 L590 530 L640 625 L210 780 L70 560 Z",
  green: "M740 70 L930 70 L1210 560 L1070 780 L640 625 L690 530 Z",
  red: "M640 625 L1070 780 L930 1050 L350 1050 L210 780 Z",
};

export const SOURCE_RIVERS = [
  "M540 70 L740 70 L690 530 L640 625 L590 530 Z",
  "M70 560 L210 780 L640 625 L590 530 Z",
  "M690 530 L640 625 L1070 780 L1210 560 Z",
];

export const SOURCE_JUNCTION = "M590 530 L690 530 L640 625 Z";

// The table is an irregular line graph. These rails are traced as individual source paths rather than inferred
// from a regular quadrilateral grid; each sequence follows a visible route in the supplied no-banner setup.
export const SOURCE_TRACE_PATHS: Record<SanguoFaction, string[]> = {
  blue: [
    "M350 70 L382 140 L370 220 L340 300 L305 370 L245 455 L175 535 L70 560",
    "M410 70 L425 145 L410 220 L390 300 L365 370 L320 440 L265 510 L210 590 L175 790",
    "M475 70 L480 150 L470 230 L455 310 L440 390 L420 470 L400 545 L390 620 L350 700",
    "M540 70 L545 155 L550 240 L555 325 L565 410 L575 485 L590 530",
    "M360 140 L430 155 L505 180 L545 190",
    "M305 225 L380 245 L465 265 L550 290",
    "M245 310 L330 330 L425 360 L555 390",
    "M180 395 L280 405 L370 435 L470 470 L575 485",
    "M115 485 L220 500 L320 525 L420 545 L525 535 L590 530",
    "M305 370 L405 420 L470 495 L420 545",
    "M305 370 L365 470 L470 495 L525 535",
  ],
  green: [
    "M930 70 L898 140 L910 220 L940 300 L975 370 L1035 455 L1105 535 L1210 560",
    "M870 70 L855 145 L870 220 L890 300 L915 370 L960 440 L1015 510 L1070 590 L1090 790",
    "M805 70 L800 150 L810 230 L825 310 L840 390 L860 470 L880 545 L890 620 L930 700",
    "M740 70 L735 155 L730 240 L725 325 L715 410 L705 485 L690 530",
    "M920 140 L850 155 L775 180 L735 190",
    "M975 225 L900 245 L815 265 L730 290",
    "M1035 310 L950 330 L855 360 L725 390",
    "M1100 395 L1000 405 L910 435 L810 470 L705 485",
    "M1165 485 L1060 500 L960 525 L860 545 L755 535 L690 530",
    "M975 370 L875 420 L810 495 L860 545",
    "M975 370 L915 470 L810 495 L755 535",
  ],
  red: [
    "M640 625 L640 680 L640 770 L640 865 L640 955 L640 1050",
    "M590 655 L565 725 L545 805 L525 895 L500 975 L495 1050",
    "M540 680 L500 740 L470 820 L440 900 L425 980 L425 1050",
    "M490 710 L435 760 L395 835 L370 915 L355 985 L354 1050",
    "M690 655 L715 725 L735 805 L755 895 L780 975 L784 1050",
    "M740 680 L780 740 L810 820 L840 900 L855 980 L855 1050",
    "M790 710 L845 760 L885 835 L910 915 L925 985 L926 1050",
    "M300 845 L390 820 L485 795 L585 780 L690 780 L795 795 L890 820 L980 845",
    "M320 925 L410 905 L505 890 L600 880 L690 880 L780 890 L870 905 L960 925",
    "M338 995 L430 980 L530 970 L640 966 L750 970 L850 980 L942 995",
    "M525 895 L640 975 L755 895",
    "M755 895 L640 975 L525 895",
  ],
};

export const palaceConnections = (sector: SanguoFaction): Array<[SourcePoint, SourcePoint]> => {
  const pattern = sector === "red" ? [[2, 3, 4, 5], [2, 5, 4, 3]] : [[1, 3, 3, 5], [1, 5, 3, 3]];
  return pattern.map(([fromRank, fromFile, toRank, toFile]) => [fieldPoint(sector, fromRank, fromFile), fieldPoint(sector, toRank, toFile)]);
};
