import { type YanYiPiece, type YanYiPoint, type YanYiRole, type YanYiFaction } from "./sanguoYanYiRules";
export const YAN_YI_ASSET_ROOT = "/assets/heritage-arcade/sanguo-yan-yi";
export const YAN_YI_BOARD = `${YAN_YI_ASSET_ROOT}/yan-yi-arctic-board.webp`;
// Calibrated against the supplied 1536px artwork. Never use these pixel positions for rule geometry.
export const YAN_YI_X = [96, 171, 246, 321, 415, 503, 592, 681, 768, 855, 944, 1034, 1122, 1208, 1283, 1362, 1441];
export const YAN_YI_Y = [75, 165, 249, 327, 417, 506, 594, 684, 769, 856, 946, 1034, 1122, 1200, 1284, 1364, 1446];
export const yanYiPixelPoint = (point: YanYiPoint) => ({ x: YAN_YI_X[point.x], y: YAN_YI_Y[point.y] });
export const yanYiSprite = (origin: YanYiFaction, role: Exclude<YanYiRole, "emperor">) => `${YAN_YI_ASSET_ROOT}/pieces/${origin}-${role}.webp`;
export const YAN_YI_HAN_ARTWORK = [
  { id: "han-emperor", filename: "han-emperor.webp", displayName: "Han Golden Emperor", role: "emperor", count: 1, pieceIds: ["han-emperor"] },
  { id: "han-chariot-imperial", filename: "han-chariot-imperial.webp", displayName: "Han Imperial Chariot", role: "chariot", count: 2, pieceIds: ["han-chariot-6", "han-chariot-10"] },
  { id: "han-chariot-vanguard", filename: "han-chariot-vanguard.webp", displayName: "Han Vanguard Chariot", role: "chariot", count: 1, pieceIds: ["han-chariot-8"] },
  { id: "han-cannon", filename: "han-cannon.webp", displayName: "Han Golden Cannon", role: "cannon", count: 1, pieceIds: ["han-cannon"] },
] as const;
// Use permanent identity, never current coordinates or controller: inherited Han stays yellow.
export const yanYiHanArtwork = (piece: YanYiPiece) => piece.origin === "han"
  ? YAN_YI_HAN_ARTWORK.find(art => art.pieceIds.some(id => id === piece.id)) || YAN_YI_HAN_ARTWORK.find(art => art.role === piece.role)
  : undefined;
export const yanYiPieceSprite = (piece: YanYiPiece) => {
  if (piece.origin !== "han") return yanYiSprite(piece.origin, piece.role as Exclude<YanYiRole, "emperor">);
  const art = yanYiHanArtwork(piece);
  return art ? `${YAN_YI_ASSET_ROOT}/pieces/${art.filename}` : null;
};
export const YAN_YI_ROLE_HELP: Record<YanYiRole, string> = {
  king: "One point horizontally or vertically inside its 3×3 palace. Wei and Shu kings may face each other in this Free Play edition.",
  advisor: "One diagonal step along its five palace points. An inherited Advisor may transfer to an empty Advisor point in your palace, using the entire move.",
  elephant: "Two points diagonally, with no blocked eye. Seven home points; inherited Elephants may use connected territories you control. The route must stay on the board.",
  horse: "An L-shaped jump: two along one axis and one along the other. Pieces do not block the leg. The full route must stay on the cross. Horses alone form alliances or capture the inactive Han Emperor.",
  chariot: "Any clear distance horizontally or vertically. Capture the first enemy on the line; never jump over a piece.",
  cannon: "Move on clear orthogonal lines. To capture, jump exactly one intervening piece of any faction. During the first full round, stay on or behind your soldier defensive line.",
  soldier: "One point forward or sideways at home. Beyond your own national boundary, move in any orthogonal direction; retreat only as far as that boundary. Inherited Soldiers use their new controller's direction.",
  emperor: "Initially immobile at Luoyang. Only a Horse may capture him. Alliance or regicide activates the three Han Chariots and Cannon. In the tutorial's marker convention, the Emperor becomes the receiving kingdom's royal marker.",
};
export const YAN_YI_CHAPTERS = [
  { title: "Board and armies", time: "00:48–03:19", paragraphs: ["Wei is blue at the top, Shu is red at the bottom, Wu is green at the right, and Han is gold at the left. Pieces occupy intersections: 225 playable points on a 17×17 cross. The four blank corners and the decorative outside border are never playable.", "Each player has 16 pieces: King ×1; Advisor, Elephant, Horse, Chariot and Cannon ×2 each; Soldier ×5. Han adds one Emperor, three Chariots and one Cannon. Total: 53 physical pieces, illustrated by 21 player-army designs and four yellow Han designs. The two outer Han Chariots share artwork; all three Chariots follow the same rules.", "Wu moves first, then Wei, then Shu. Your defensive line is the starting Soldier rank. Your national boundary is the next line toward the center."] },
  { title: "Movement and capture", time: "03:22–09:34", paragraphs: ["Move one controlled piece to a highlighted intersection. Friendly and allied destinations are blocked. A capture removes the enemy occupying your destination. Active kings are checkmated rather than captured directly.", "Horse legs and Elephant eyes cannot be blocked. A valid destination is insufficient if the Horse's or Elephant's route cuts across a missing corner. All routes must remain on the cross.", "The tutorial's first-round Cannon restriction stops at the defensive line. The 2020 written article instead permits the national boundary. This table follows the video."] },
  { title: "Check and turn order", time: "09:40–10:59; 20:33–22:20", paragraphs: ["A single checked faction responds immediately, even out of turn. Continue from that faction's next seat after its response. If multiple factions are checked, use normal Wu → Wei → Shu order. A mated king is removed immediately.", "Checking your previous seat may give you another move after its response. Repeating that check without changing the cycle is restricted. Choose six or nine checks before a warning; continuing the cycle forfeits your army to that previous seat. Checking the next seat is allowed.", "Protect your own king. In this tutorial edition, you must also protect your ally's king: you cannot move away a shielding piece and expose it. Allied pieces do not check one another. Wei and Shu may face directly; the ordinary Xiangqi flying-General restriction does not apply."] },
  { title: "Alliance and Han", time: "11:01–15:39", paragraphs: ["Move a Horse to the Shu, Wu or Wei alliance point beside the Emperor. Landing on another faction's point automatically allies you with it, even accidentally or without its consent. Your own point has no effect. The remaining faction immediately controls the three Han Chariots and Cannon.", "Alternatively, a Horse captures the inactive Emperor at Luoyang. The Horse's controller gains Han; the other two surviving factions automatically ally against it. The Han royal marker still represents its recipient's own King, with the same palace and identity.", "Allies cannot capture or check one another. No player may voluntarily cancel or replace an alliance. It ends when any participating kingdom is eliminated. Han activation is a one-time event; the receiving side keeps the reserve unless its army is inherited by a victor.", "The speaker proposes giving Han to the third kingdom when an early checkmate creates a large imbalance. It was only proposed to the designers. The separate 'Early-conquest Han balance' option is off by default."] },
  { title: "Inheritance and the ending", time: "15:46–20:26; 25:20–26:16", paragraphs: ["Checkmate defeats a kingdom and transfers all its surviving pieces to the direct checking faction. If the moving faction and another faction both directly checkmate it, prefer the moving faction. If only the other faction directly checks, that faction inherits. Han pieces already owned by the defeated kingdom transfer too.", "Inherited artwork keeps its original faction color. A new owner ring and label show who controls it. Soldiers use the new controller's boundary. Inherited Advisors can transfer into the controller's palace, one Advisor per whole move. Elephants can travel through the seven-point networks of controlled neighboring kingdoms; Wei–Shu transfers need the Han route because enemy Wu territory is unavailable.", "Resignation leaves the army where it stands, inactive and capturable; it is not inherited. The king is face down. Inactive pieces remain obstacles and Cannon screens. Defeated seats are skipped.", "The final surviving king wins. If the survivors cannot mate, they may agree to draw. The table automatically recognizes no remaining offensive force. The video omits stalemate adjudication; this edition explicitly uses the original patent's pass rule for a seat with no legal move and no check."] },
  { title: "Notation and tactics", time: "26:28–36:18", paragraphs: ["Files are numbered 1–17 from each controller's right to left. The central King file is 9; starting Chariots are on files 5 and 13. Han has no independent notation: inherited Han units use their controller's files.", "When identical pieces share a file, use front/rear for two, front/middle/rear for three, and ordinal numbers from the front for larger groups. 'Fourth Chariot to file 9' is different from 'Chariot on file 4 to file 9.' The game journal also records both source and destination coordinates.", "The narrator favors one full round as one historical year from AD 184, instead of the official AD 189 start or suggested monthly/seasonal scales. This is storytelling, not a move timer.", "Watch for borrowed-knife captures and Horse forks near Han. A Chariot can stop some Horse approaches using the four-square pattern, but other approaches need two Chariots. After an alliance, protect the newly activated Han Chariots from an immediate fork. The exact tutorial setups remain in the timestamped transcript; they are examples, not universal guarantees."] },
];
