export const RUMA_RULESET=Object.freeze({gameId:'ruma-ice-puzzle',rulesetVersion:'tchuka-ruma-campbell-chavey-1995-1.0.0',traditionalName:'Tchuka Ruma',defaultPits:4,defaultSeeds:2});
const clone=v=>JSON.parse(JSON.stringify(v));
export function createRumaState({pits=4,seeds=2,mode='classic'}={}){return{gameId:RUMA_RULESET.gameId,rulesetVersion:RUMA_RULESET.rulesetVersion,mode,pits:Array(pits).fill(seeds),ruma:0,move:1,status:'playing',lastMove:null,history:[],selected:null};}
export function getLegalActions(s){if(!s||s.status!=='playing')return[];return s.pits.map((n,i)=>({n,i})).filter(x=>x.n>0).map(x=>({type:'sow',pitIndex:x.i}));}
export function applyAction(state,action){if(!getLegalActions(state).some(a=>a.pitIndex===action?.pitIndex))return{state,error:'Choose a non-empty ice pit.'};const s=clone(state);let index=action.pitIndex,hand=s.pits[index];s.pits[index]=0;let chains=0,drops=0,last='';const seen=new Set();while(true){while(hand>0){index++;if(index===s.pits.length){s.ruma++;hand--;drops++;last='ruma';if(hand>0)index=-1;continue}s.pits[index]++;hand--;drops++;last=`pit-${index}`;}if(last==='ruma'){s.lastMove={start:action.pitIndex,chains,drops,ended:'ruma'};break;}if(s.pits[index]===1){s.status='lost';s.lastMove={start:action.pitIndex,chains,drops,ended:'empty'};break;}const signature=`${s.pits.join(',')}|${s.ruma}|${index}`;if(seen.has(signature)){s.status='lost';s.lastMove={start:action.pitIndex,chains,drops,ended:'loop'};break;}seen.add(signature);hand=s.pits[index];s.pits[index]=0;index=index;chains++;if(chains>500){s.status='lost';break;}}
if(s.pits.every(n=>n===0))s.status='won';s.history.push({move:s.move,...s.lastMove,pits:[...s.pits],ruma:s.ruma});s.move++;return{state:s,error:null};}
export function createRumaLesson(){const s=createRumaState();s.pits=[0,1,3,4];s.ruma=0;s.mode='lesson';return s;}
export function solveRuma(start,maxNodes=200000){const root=clone(start),seen=new Set();function dfs(s,path){const key=s.pits.join(',')+'|'+s.ruma;if(seen.has(key)||seen.size>maxNodes)return null;seen.add(key);if(s.status==='won'||s.pits.every(n=>n===0))return path;for(const a of getLegalActions(s)){const r=applyAction(s,a);if(r.state.status==='lost')continue;const found=dfs(r.state,[...path,a.pitIndex]);if(found)return found;}return null}return dfs(root,[]);}
export function statusTitle(s){return s.status==='won'?'Ruma complete':s.status==='lost'?'Chain broken':'Route every counter into the Ruma';}
